/*
 * Generated config.h for vendored dav1d build.
 * This is a template — the actual config.h is generated by build.rs
 * per-target. This file is kept as reference.
 */
#ifndef DAV1D_CONFIG_H
#define DAV1D_CONFIG_H

/* Bitdepth support */
#define CONFIG_8BPC 1
#define CONFIG_16BPC 1

/* No ASM in vendored scalar build */
#define HAVE_ASM 0

/* Trim DSP functions not matching compiled bitdepth */
#define TRIM_DSP_FUNCTIONS 1

/* Enable logging */
#define CONFIG_LOG 0

/* macOS kperf */
#define CONFIG_MACOS_KPERF 0

/* Endianness */
#define ENDIANNESS_BIG 0

/* Architecture detection — set by build.rs defines */
#ifndef ARCH_AARCH64
#define ARCH_AARCH64 0
#endif
#ifndef ARCH_ARM
#define ARCH_ARM 0
#endif
#ifndef ARCH_X86
#define ARCH_X86 0
#endif
#ifndef ARCH_X86_64
#define ARCH_X86_64 0
#endif
#ifndef ARCH_X86_32
#define ARCH_X86_32 0
#endif
#ifndef ARCH_PPC64LE
#define ARCH_PPC64LE 0
#endif
#ifndef ARCH_RISCV
#define ARCH_RISCV 0
#endif
#ifndef ARCH_RV32
#define ARCH_RV32 0
#endif
#ifndef ARCH_RV64
#define ARCH_RV64 0
#endif
#ifndef ARCH_LOONGARCH
#define ARCH_LOONGARCH 0
#endif
#ifndef ARCH_LOONGARCH32
#define ARCH_LOONGARCH32 0
#endif
#ifndef ARCH_LOONGARCH64
#define ARCH_LOONGARCH64 0
#endif

/* POSIX features — conservative defaults, overridden by build.rs */
#ifndef HAVE_POSIX_MEMALIGN
#if defined(__unix__) || defined(__APPLE__)
#define HAVE_POSIX_MEMALIGN 1
#else
#define HAVE_POSIX_MEMALIGN 0
#endif
#endif

#ifndef HAVE_MEMALIGN
#define HAVE_MEMALIGN 0
#endif

#ifndef HAVE_ALIGNED_ALLOC
#if defined(__GLIBC__) || defined(__APPLE__) || defined(__ANDROID__)
#define HAVE_ALIGNED_ALLOC 1
#else
#define HAVE_ALIGNED_ALLOC 0
#endif
#endif

#ifndef HAVE_DLSYM
#if defined(__unix__) || defined(__APPLE__)
#define HAVE_DLSYM 1
#else
#define HAVE_DLSYM 0
#endif
#endif

#ifndef HAVE_UNISTD_H
#if defined(__unix__) || defined(__APPLE__)
#define HAVE_UNISTD_H 1
#else
#define HAVE_UNISTD_H 0
#endif
#endif

#ifndef HAVE_IO_H
#if defined(_WIN32)
#define HAVE_IO_H 1
#else
#define HAVE_IO_H 0
#endif
#endif

#ifndef HAVE_SYS_TYPES_H
#define HAVE_SYS_TYPES_H 1
#endif

#ifndef HAVE_CLOCK_GETTIME
#if defined(__unix__) || defined(__APPLE__)
#define HAVE_CLOCK_GETTIME 1
#else
#define HAVE_CLOCK_GETTIME 0
#endif
#endif

#ifndef HAVE_PTHREAD_NP_H
#define HAVE_PTHREAD_NP_H 0
#endif

#ifndef HAVE_GETAUXVAL
#if defined(__linux__) && !defined(__ANDROID__)
#define HAVE_GETAUXVAL 1
#elif defined(__ANDROID__) && __ANDROID_API__ >= 18
#define HAVE_GETAUXVAL 1
#else
#define HAVE_GETAUXVAL 0
#endif
#endif

#ifndef HAVE_ELF_AUX_INFO
#define HAVE_ELF_AUX_INFO 0
#endif

#define HAVE_PTHREAD_GETAFFINITY_NP 0
#define HAVE_PTHREAD_SETAFFINITY_NP 0
#define HAVE_PTHREAD_SETNAME_NP 0
#define HAVE_PTHREAD_SET_NAME_NP 0

#define HAVE_C11_GENERIC 1

#endif /* DAV1D_CONFIG_H */
