#!/usr/bin/python3

import re
import sys
import urllib.request

UNICODE_BASE_URL = "https://www.unicode.org/Public/14.0.0/ucd"

def parse_code_value(string):
    try:
        value = int(string, 16)
    except ValueError:
        raise Exception("invalid unicode value")
    if value < 0 or value > 0x10FFFF:
        raise Exception("invalid unicode value")
    return value

def parse_code_range(string):
    bounds = string.split("..")
    if len(bounds) == 1:
        start = parse_code_value(bounds[0])
        end = start
    elif len(bounds) == 2:
        start = parse_code_value(bounds[0])
        end = parse_code_value(bounds[1])
    else:
        raise Exception("invalid unicode range")
    if start > end:
        raise Exception("invalid unicode range")
    return range(start, end + 1)

def parse_char_name(string):
    match = re.match("<(.*), (First|Last)>", string)
    if match is None:
        return (string[0], None)
    return match.groups()

def read_unicode_data(url):
    if url.startswith("https://"):
        stream = urllib.request.urlopen(url)
    else:
        stream = open(url, "rb")

    first = None
    expect_last = None
    for line in stream:
        line = line.decode("utf-8")

        hash = line.find("#")
        if hash >= 0:
            line = line[:hash]
        line = line.strip()
        if not line:
            continue

        fields = [field.strip() for field in line.split(";")]
        codes = parse_code_range(fields[0])
        (name, cont) = parse_char_name(fields[1])
        if expect_last is not None:
            if name != expect_last or cont != "Last":
                raise Exception("expected last line for %s", expect_last)
            if len(codes) != 1 or codes[0] < first:
                raise Exception("invalid last line")
            codes = range(first, codes[0] + 1)
            first = None
            expect_last = None
            yield [codes] + fields[1:]
        elif cont == "First":
            if len(codes) != 1:
                raise Exception("invalid first line")
            first = codes[0]
            expect_last = name
        else:
            yield [codes] + fields[1:]

def read_categories(unicode_base_url):
    categories = {}
    for [codes, _, category, *_] in read_unicode_data(unicode_base_url + "/UnicodeData.txt"):
        categories.setdefault(category, []).extend(codes)
        if len(category) > 1:
            short = category[0]
            categories.setdefault(short, []).extend(codes)
    return categories

def read_aliases(unicode_base_url):
    aliases = {}
    for [codes, alias, *_] in read_unicode_data(unicode_base_url + "/NameAliases.txt"):
        aliases.setdefault(alias, []).extend(codes)
    return aliases

def read_properties(unicode_base_url):
    properties = {}
    for [codes, property] in read_unicode_data(unicode_base_url + "/DerivedCoreProperties.txt"):
        properties.setdefault(property, []).extend(codes)
    return properties

def read_other_properties(unicode_base_url):
    other_properties = {}
    for [codes, other_property] in read_unicode_data(unicode_base_url + "/PropList.txt"):
        other_properties.setdefault(other_property, []).extend(codes)
    return other_properties

def read_case_folds(unicode_base_url):
    case_folds = {}
    for [codes, status, mapping, *_] in read_unicode_data(unicode_base_url + "/CaseFolding.txt"):
        if status not in ("C", "S"):
            continue
        mapping = parse_code_value(mapping)
        case_folds.setdefault(mapping, [mapping]).extend(codes)
    case_folds = list(case_folds.values())
    for codes in case_folds:
        codes.sort()
    case_folds.sort()
    return case_folds
        
def generate_ranges(codes):
    range = None
    for code in codes:
        if range is None:
            range = [code, code]
        else:
            if code == range[1] + 1:
                range[1] = code
            else:
                yield range
                range = [code, code]
    if range is not None:
        yield range

def print_group(name, codes):
    ranges = list(generate_ranges(sorted(codes)))
    print("pub static %s: [Range<char>; %d] = [" % (name, len(ranges)))
    for range in ranges:
        print("    Range::new('\\u{%X}', '\\u{%X}')," % (range[0], range[1]))
    print("];")

def main():
    if len(sys.argv) > 1:
        unicode_base_url = sys.argv[1]
    else:
        unicode_base_url = UNICODE_BASE_URL

    categories = read_categories(unicode_base_url)
    aliases = read_aliases(unicode_base_url)
    properties = read_properties(unicode_base_url)
    other_properties = read_other_properties(unicode_base_url)
    case_folds = read_case_folds(unicode_base_url)
    
    print("//! Generated by make_unicode.py")
    print("")
    print("use crate::range::Range;")
    print("")

    alnum = set()
    alnum.update(properties["Alphabetic"])
    alnum.update(categories["Nd"])
    print_group("ALNUM", alnum)
    print()

    alpha = set()
    alpha.update(properties["Alphabetic"])
    print_group("ALPHA", alpha)
    print()

    blank = set()
    blank.update(categories["Zs"])
    blank.update(aliases["CHARACTER TABULATION"])
    print_group("BLANK", blank)
    print()

    cntrl = set()
    cntrl.update(categories["Cc"])
    print_group("CNTRL", cntrl)
    print()

    digit = set()
    digit.update(categories["Nd"])
    print_group("DIGIT", digit)
    print()

    graph = set()
    graph.update(range(0, 0xD800))
    graph.update(range(0xE000, 0x110000))
    graph.difference_update(other_properties["White_Space"])
    graph.difference_update(categories["Cc"])
    graph.difference_update(categories["Cs"])
    print_group("GRAPH", graph)
    print()

    lower = set()
    lower.update(properties["Lowercase"])
    print_group("LOWER", lower)
    print()

    print_ = set()
    print_.update(range(0, 0xD800))
    print_.update(range(0xE000, 0x110000))
    print_.difference_update(other_properties["White_Space"])
    print_.difference_update(categories["Cc"])
    print_.difference_update(categories["Cs"])
    print_.update(categories["Zs"])
    print_.update(aliases["CHARACTER TABULATION"])
    print_.difference_update(categories["Cc"])
    print_group("PRINT", print_)
    print()

    punct = set()
    punct.update(categories["P"])
    print_group("PUNCT", punct)
    print()

    space = set()
    space.update(other_properties["White_Space"])
    print_group("SPACE", space)
    print()

    upper = set()
    upper.update(properties["Uppercase"])
    print_group("UPPER", upper)
    print()

    word = set()
    word.update(properties["Alphabetic"])
    word.update(categories["M"])
    word.update(categories["Nd"])
    word.update(categories["Pc"])
    word.update(other_properties["Join_Control"])
    print_group("WORD", word)
    print()

    xdigit = set()
    xdigit.update(categories["Nd"])
    xdigit.update(other_properties["Hex_Digit"])
    print_group("XDIGIT", xdigit)
    print()

    case_folds_by_code = []
    for case_fold in case_folds:
        for code in case_fold:
            case_folds_by_code.append([case_fold[0], case_fold])
    case_folds_by_code.sort()
    print("pub static CASE_FOLDS: [(char, &'static [char]); %d] = [" % len(case_folds_by_code))
    for [code, case_folds] in case_folds_by_code:
        print("    ('\\u{%X}', &[" % code, end="")
        for code in case_folds:
            print("'\\u{%X}'" % code, end = ", ")
        print("]),")
    print("];")

if __name__ == '__main__':
    main()
