//! Capability/auth policy store.
//!
//! Credential rule: the catalog never holds a secret. A token secret is
//! generated by the transport layer, shown once, and only its SHA-256 lands
//! here. Authentication failures are uniform (`Unauthenticated`) — unknown,
//! expired, revoked, and disabled principals are indistinguishable to a
//! caller, so the store cannot be used as an oracle.
//!
//! Authorization is explicit grants: (principal, capability, scope), where
//! scope is a namespace or `*`. No grant means denied; there is no default
//! allow anywhere.

use crate::catalog::validate_namespace;
use crate::error::{ServerError, ServerResult};
use crate::sqlite::Db;
use makepad_asset_data::sha256;

pub const AUTH_SCHEMA: &str = "
CREATE TABLE IF NOT EXISTS principals(
    principal_id BLOB PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    disabled INTEGER NOT NULL DEFAULT 0,
    created_ms INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS tokens(
    token_hash BLOB PRIMARY KEY,
    principal_id BLOB NOT NULL,
    expires_ms INTEGER NOT NULL,
    revoked INTEGER NOT NULL DEFAULT 0,
    created_ms INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS grants(
    principal_id BLOB NOT NULL,
    capability TEXT NOT NULL,
    scope TEXT NOT NULL,
    granted_ms INTEGER NOT NULL,
    PRIMARY KEY(principal_id, capability, scope)
);
";

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct PrincipalId(pub [u8; 16]);

/// Every operation class the core distinguishes. The HTTP layer maps routes
/// to exactly one of these; nothing is implied by another.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Capability {
    BlobWrite,
    AssetRegister,
    AssetPublish,
    AssetQuarantine,
    AliasWrite,
    GameRegister,
    GamePublish,
    JobEnqueue,
    JobWorker,
    JobCancel,
    AuthAdmin,
    /// Register/approve an external source collection (admin-shaped).
    ImportSource,
    /// Run a deterministic pack import into an approved source's namespace.
    ImportRun,
    /// Request derivations and freeze variant sets for a namespace's assets.
    DeriveRequest,
    /// Create/cancel/retry typed asset operations in a namespace. Reads of
    /// one's own operations need only ownership; this gates the mutations.
    OperationRun,
    /// Open and drive a chat session bound to a namespace. Tool execution
    /// still uses the caller's own grants (operation_run, catalog reads).
    Chat,
}

impl Capability {
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::BlobWrite => "blob_write",
            Self::AssetRegister => "asset_register",
            Self::AssetPublish => "asset_publish",
            Self::AssetQuarantine => "asset_quarantine",
            Self::AliasWrite => "alias_write",
            Self::GameRegister => "game_register",
            Self::GamePublish => "game_publish",
            Self::JobEnqueue => "job_enqueue",
            Self::JobWorker => "job_worker",
            Self::JobCancel => "job_cancel",
            Self::AuthAdmin => "auth_admin",
            Self::ImportSource => "import_source",
            Self::ImportRun => "import_run",
            Self::DeriveRequest => "derive_request",
            Self::OperationRun => "operation_run",
            Self::Chat => "chat",
        }
    }
}

/// Grant scope: one namespace, or every namespace.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Scope<'a> {
    All,
    Namespace(&'a str),
}

impl<'a> Scope<'a> {
    fn as_str(&self) -> &str {
        match self {
            Self::All => "*",
            Self::Namespace(ns) => ns,
        }
    }
}

/// Hash a transport-held secret into the only form this store accepts.
pub fn token_hash(secret: &[u8]) -> [u8; 32] {
    sha256(secret)
}

pub struct Auth<'a> {
    pub(crate) db: &'a Db,
}

impl<'a> Auth<'a> {
    pub fn create_principal(&self, principal: &PrincipalId, name: &str, now_ms: u64) -> ServerResult<()> {
        if name.is_empty() || name.len() > 128 {
            return Err(ServerError::InvalidInput { what: "principal name length" });
        }
        if self.principal_exists(principal)? {
            return Err(ServerError::Conflict { what: "principal id" });
        }
        let mut s = self.db.prepare(
            "create principal",
            "INSERT INTO principals(principal_id, name, created_ms) VALUES(?1, ?2, ?3)",
        )?;
        s.bind_blob(1, &principal.0)?;
        s.bind_text(2, name)?;
        s.bind_u64(3, now_ms)?;
        s.run()
    }

    pub fn principal_exists(&self, principal: &PrincipalId) -> ServerResult<bool> {
        let mut s = self.db.prepare(
            "principal exists",
            "SELECT 1 FROM principals WHERE principal_id = ?1",
        )?;
        s.bind_blob(1, &principal.0)?;
        s.step()
    }

    pub fn disable_principal(&self, principal: &PrincipalId) -> ServerResult<()> {
        let mut s = self.db.prepare(
            "disable principal",
            "UPDATE principals SET disabled=1 WHERE principal_id = ?1",
        )?;
        s.bind_blob(1, &principal.0)?;
        s.run()?;
        if self.db.changes() == 0 {
            return Err(ServerError::NotFound { what: "principal" });
        }
        Ok(())
    }

    /// Register a token by its hash. The secret itself never reaches the
    /// store; `expires_ms` is a hard wall-clock bound checked on every use.
    pub fn register_token(
        &self,
        principal: &PrincipalId,
        token_hash: &[u8; 32],
        expires_ms: u64,
        now_ms: u64,
    ) -> ServerResult<()> {
        if expires_ms <= now_ms {
            return Err(ServerError::InvalidInput { what: "token already expired" });
        }
        if !self.principal_exists(principal)? {
            return Err(ServerError::NotFound { what: "principal" });
        }
        let mut s = self.db.prepare(
            "register token",
            "INSERT INTO tokens(token_hash, principal_id, expires_ms, created_ms)
             VALUES(?1, ?2, ?3, ?4)",
        )?;
        s.bind_blob(1, token_hash)?;
        s.bind_blob(2, &principal.0)?;
        s.bind_u64(3, expires_ms)?;
        s.bind_u64(4, now_ms)?;
        s.run()
    }

    pub fn revoke_token(&self, token_hash: &[u8; 32]) -> ServerResult<()> {
        let mut s = self.db.prepare(
            "revoke token",
            "UPDATE tokens SET revoked=1 WHERE token_hash = ?1",
        )?;
        s.bind_blob(1, token_hash)?;
        s.run()?;
        if self.db.changes() == 0 {
            return Err(ServerError::NotFound { what: "token" });
        }
        Ok(())
    }

    /// Resolve a presented secret to its principal. Fail closed and uniform:
    /// any defect (unknown, expired, revoked, disabled) is `Unauthenticated`.
    pub fn authenticate(&self, secret: &[u8], now_ms: u64) -> ServerResult<PrincipalId> {
        let hash = token_hash(secret);
        let mut s = self.db.prepare(
            "authenticate",
            "SELECT t.principal_id, t.expires_ms, t.revoked, p.disabled
             FROM tokens t JOIN principals p ON p.principal_id = t.principal_id
             WHERE t.token_hash = ?1",
        )?;
        s.bind_blob(1, &hash)?;
        if !s.step()? {
            return Err(ServerError::Unauthenticated);
        }
        let principal = crate::catalog::fixed16(&s.column_blob(0), "token row")?;
        // Clamped read: a corrupt negative expiry authenticates nothing.
        let expires = s.column_u64(1);
        let revoked = s.column_i64(2) != 0;
        let disabled = s.column_i64(3) != 0;
        if revoked || disabled || expires <= now_ms {
            return Err(ServerError::Unauthenticated);
        }
        Ok(PrincipalId(principal))
    }

    pub fn grant(&self, principal: &PrincipalId, cap: Capability, scope: Scope<'_>, now_ms: u64) -> ServerResult<()> {
        if let Scope::Namespace(ns) = scope {
            validate_namespace(ns)?;
        }
        if !self.principal_exists(principal)? {
            return Err(ServerError::NotFound { what: "principal" });
        }
        let mut s = self.db.prepare(
            "grant",
            "INSERT OR IGNORE INTO grants(principal_id, capability, scope, granted_ms)
             VALUES(?1, ?2, ?3, ?4)",
        )?;
        s.bind_blob(1, &principal.0)?;
        s.bind_text(2, cap.as_str())?;
        s.bind_text(3, scope.as_str())?;
        s.bind_u64(4, now_ms)?;
        s.run()
    }

    pub fn revoke_grant(&self, principal: &PrincipalId, cap: Capability, scope: Scope<'_>) -> ServerResult<()> {
        let mut s = self.db.prepare(
            "revoke grant",
            "DELETE FROM grants WHERE principal_id=?1 AND capability=?2 AND scope=?3",
        )?;
        s.bind_blob(1, &principal.0)?;
        s.bind_text(2, cap.as_str())?;
        s.bind_text(3, scope.as_str())?;
        s.run()
    }

    /// Whether the principal holds the capability under ANY scope. Not an
    /// authorization primitive (it names no namespace) — used for honesty
    /// signals like worker liveness, where "could execute somewhere" is the
    /// fact being recorded.
    pub fn holds_anywhere(&self, principal: &PrincipalId, cap: Capability) -> ServerResult<bool> {
        let mut s = self.db.prepare(
            "holds capability anywhere",
            "SELECT 1 FROM grants WHERE principal_id=?1 AND capability=?2 LIMIT 1",
        )?;
        s.bind_blob(1, &principal.0)?;
        s.bind_text(2, cap.as_str())?;
        s.step()
    }

    /// Authorization check: the principal must hold the capability for the
    /// namespace, either directly or via a `*` grant. Missing means denied.
    pub fn require(&self, principal: &PrincipalId, cap: Capability, namespace: &str) -> ServerResult<()> {
        validate_namespace(namespace)?;
        let mut s = self.db.prepare(
            "require capability",
            "SELECT 1 FROM grants
             WHERE principal_id=?1 AND capability=?2 AND scope IN (?3, '*')",
        )?;
        s.bind_blob(1, &principal.0)?;
        s.bind_text(2, cap.as_str())?;
        s.bind_text(3, namespace)?;
        if s.step()? {
            Ok(())
        } else {
            Err(ServerError::Denied { capability: cap.as_str() })
        }
    }
}
