//! Generates core/num/int_impls.rs (inherent integer methods), core/num/float_impls.rs
//! (inherent f32/f64 methods) and core/num/prim_traits.rs (trait impls on the numeric
//! primitives and bool). The dialect has no macro_rules (R1), so the per-type code is written
//! out by this generator; edit the templates here, not the generated files.

use std::fmt::Write;

#[derive(Clone, Copy)]
struct Int {
    name: &'static str,
    bits: u32,
    signed: bool,
    /// the same-width unsigned type
    unsigned: &'static str,
    /// a type twice as wide for overflow checks, if any (<= 32 bits)
    wide: Option<&'static str>,
}

const INTS: [Int; 12] = [
    Int { name: "u8", bits: 8, signed: false, unsigned: "u8", wide: Some("u16") },
    Int { name: "u16", bits: 16, signed: false, unsigned: "u16", wide: Some("u32") },
    Int { name: "u32", bits: 32, signed: false, unsigned: "u32", wide: Some("u64") },
    Int { name: "u64", bits: 64, signed: false, unsigned: "u64", wide: None },
    Int { name: "u128", bits: 128, signed: false, unsigned: "u128", wide: None },
    Int { name: "usize", bits: 64, signed: false, unsigned: "usize", wide: None },
    Int { name: "i8", bits: 8, signed: true, unsigned: "u8", wide: Some("i16") },
    Int { name: "i16", bits: 16, signed: true, unsigned: "u16", wide: Some("i32") },
    Int { name: "i32", bits: 32, signed: true, unsigned: "u32", wide: Some("i64") },
    Int { name: "i64", bits: 64, signed: true, unsigned: "u64", wide: None },
    Int { name: "i128", bits: 128, signed: true, unsigned: "u128", wide: None },
    Int { name: "isize", bits: 64, signed: true, unsigned: "usize", wide: None },
];

fn min_of(t: &Int) -> i128 {
    if t.signed {
        if t.bits == 128 {
            i128::MIN
        } else {
            -(1i128 << (t.bits - 1))
        }
    } else {
        0
    }
}

/// max as u128
fn max_of(t: &Int) -> u128 {
    if t.signed {
        (1u128 << (t.bits - 1)) - 1
    } else if t.bits == 128 {
        u128::MAX
    } else {
        (1u128 << t.bits) - 1
    }
}

fn lit_min(t: &Int) -> String {
    if !t.signed {
        return "0".to_string();
    }
    // MIN cannot be written as a negative literal of its own type: -MAX - 1
    format!("-{} - 1", max_of(t))
}

fn header(out: &mut String, what: &str) {
    out.push_str("// GENERATED by tools/rapid/std-next/check/src/gen_num.rs (`rapid-std-gen num ../core`).\n");
    out.push_str("// Do not edit by hand: change the generator and re-run it.\n");
    let _ = writeln!(out, "//! {}", what);
    out.push('\n');
}

pub fn run(core: &str) {
    let mut a = String::new();
    header(&mut a, "Inherent methods of the integer types (Rapid only: impls on primitive types).");
    a.push_str("use crate::intrinsics_int as ii;\nuse crate::num::parse;\nuse crate::num::ParseIntError;\n\n");
    for t in INTS.iter() {
        gen_int(&mut a, t);
    }
    gen_u8_ascii(&mut a);
    std::fs::write(format!("{}/num/int_impls.rs", core), &a).expect("write int_impls.rs");
    std::fs::write(format!("{}/../check/src/num_int_check.rs", core), check_copy(&a)).expect("write num_int_check.rs");

    let mut f = String::new();
    header(&mut f, "Inherent methods and constants of f32/f64 (Rapid only).");
    f.push_str("use crate::intrinsics;\nuse crate::libm;\nuse crate::num::FpCategory;\nuse crate::cmp::Ordering;\n\n");
    gen_float(&mut f, "f64");
    gen_float(&mut f, "f32");
    std::fs::write(format!("{}/num/float_impls.rs", core), f).expect("write float_impls.rs");

    let mut p = String::new();
    header(&mut p, "Trait impls on the numeric primitives and bool (Rapid only).");
    p.push_str("use crate::cmp::Ordering;\nuse crate::iter::{Product, Step, Sum};\nuse crate::num::{IntErrorKind, ParseIntError, TryFromIntError};\nuse crate::ops::*;\nuse crate::str::FromStr;\n\n");
    for t in INTS.iter() {
        gen_int_traits(&mut p, t);
    }
    for fl in ["f32", "f64"] {
        gen_float_traits(&mut p, fl);
    }
    gen_bool_traits(&mut p);
    gen_conversions(&mut p);
    std::fs::write(format!("{}/num/prim_traits.rs", core), p).expect("write prim_traits.rs");
    eprintln!("gen_num: wrote num/int_impls.rs, num/float_impls.rs, num/prim_traits.rs");
}

fn gen_int(o: &mut String, t: &Int) {
    let n = t.name;
    let u = t.unsigned;
    let b = t.bits;
    let bytes = b / 8;
    let _ = writeln!(o, "#[cfg(not(rapid_check))]\nimpl {} {{", n);
    let _ = writeln!(o, "    pub const MIN: {n} = {};", lit_min(t));
    let _ = writeln!(o, "    pub const MAX: {n} = {};", max_of(t));
    let _ = writeln!(o, "    pub const BITS: u32 = {b};");
    let _ = writeln!(o, "    pub const fn min_value() -> {n} {{ {n}::MIN }}");
    let _ = writeln!(o, "    pub const fn max_value() -> {n} {{ {n}::MAX }}");
    // bit operations through intrinsics on the unsigned representation
    let _ = writeln!(o, "    pub const fn count_ones(self) -> u32 {{ unsafe {{ ii::ctpop(self as {u}) }} }}");
    let _ = writeln!(o, "    pub const fn count_zeros(self) -> u32 {{ {b} - self.count_ones() }}");
    let _ = writeln!(o, "    pub const fn leading_zeros(self) -> u32 {{ unsafe {{ ii::ctlz(self as {u}) }} }}");
    let _ = writeln!(o, "    pub const fn trailing_zeros(self) -> u32 {{ unsafe {{ ii::cttz(self as {u}) }} }}");
    let _ = writeln!(o, "    pub const fn leading_ones(self) -> u32 {{ (!self).leading_zeros() }}");
    let _ = writeln!(o, "    pub const fn trailing_ones(self) -> u32 {{ (!self).trailing_zeros() }}");
    let _ = writeln!(
        o,
        "    pub const fn rotate_left(self, n: u32) -> {n} {{ let k = n % {b}; if k == 0 {{ self }} else {{ (((self as {u}) << k) | ((self as {u}) >> ({b} - k))) as {n} }} }}"
    );
    let _ = writeln!(
        o,
        "    pub const fn rotate_right(self, n: u32) -> {n} {{ let k = n % {b}; if k == 0 {{ self }} else {{ (((self as {u}) >> k) | ((self as {u}) << ({b} - k))) as {n} }} }}"
    );
    if b == 8 {
        let _ = writeln!(o, "    pub const fn swap_bytes(self) -> {n} {{ self }}");
    } else {
        let _ = writeln!(o, "    pub const fn swap_bytes(self) -> {n} {{ unsafe {{ ii::bswap(self as {u}) as {n} }} }}");
    }
    let _ = writeln!(o, "    pub const fn reverse_bits(self) -> {n} {{ unsafe {{ ii::bitreverse(self as {u}) as {n} }} }}");
    let _ = writeln!(o, "    pub const fn from_be(x: {n}) -> {n} {{ x.swap_bytes() }}");
    let _ = writeln!(o, "    pub const fn from_le(x: {n}) -> {n} {{ x }}");
    let _ = writeln!(o, "    pub const fn to_be(self) -> {n} {{ self.swap_bytes() }}");
    let _ = writeln!(o, "    pub const fn to_le(self) -> {n} {{ self }}");
    // overflowing family
    if t.signed {
        let _ = writeln!(o, "    pub const fn overflowing_add(self, rhs: {n}) -> ({n}, bool) {{ let r = (self as {u}).wrapping_add(rhs as {u}) as {n}; (r, ((self ^ r) & (rhs ^ r)) < 0) }}");
        let _ = writeln!(o, "    pub const fn overflowing_sub(self, rhs: {n}) -> ({n}, bool) {{ let r = (self as {u}).wrapping_sub(rhs as {u}) as {n}; (r, ((self ^ rhs) & (self ^ r)) < 0) }}");
    } else {
        let _ = writeln!(o, "    pub const fn overflowing_add(self, rhs: {n}) -> ({n}, bool) {{ let r = self + rhs; (r, r < self) }}");
        let _ = writeln!(o, "    pub const fn overflowing_sub(self, rhs: {n}) -> ({n}, bool) {{ let r = self - rhs; (r, self < rhs) }}");
    }
    match t.wide {
        Some(w) => {
            let _ = writeln!(o, "    pub const fn overflowing_mul(self, rhs: {n}) -> ({n}, bool) {{ let wide = (self as {w}) * (rhs as {w}); let r = wide as {n}; (r, (r as {w}) != wide) }}");
        }
        None if t.signed => {
            let _ = writeln!(o, "    pub const fn overflowing_mul(self, rhs: {n}) -> ({n}, bool) {{");
            let _ = writeln!(o, "        let r = (self as {u}).wrapping_mul(rhs as {u}) as {n};");
            let _ = writeln!(o, "        let o = if self == 0 {{ false }} else if self == -1 {{ rhs == {n}::MIN }} else {{ r / self != rhs }};");
            let _ = writeln!(o, "        (r, o)\n    }}");
        }
        None => {
            let _ = writeln!(o, "    pub const fn overflowing_mul(self, rhs: {n}) -> ({n}, bool) {{ let r = self * rhs; (r, self != 0 && r / self != rhs) }}");
        }
    }
    if t.signed {
        let _ = writeln!(o, "    pub const fn overflowing_neg(self) -> ({n}, bool) {{ if self == {n}::MIN {{ ({n}::MIN, true) }} else {{ (-self, false) }} }}");
        let _ = writeln!(o, "    pub const fn overflowing_div(self, rhs: {n}) -> ({n}, bool) {{ if self == {n}::MIN && rhs == -1 {{ (self, true) }} else {{ (self / rhs, false) }} }}");
        let _ = writeln!(o, "    pub const fn overflowing_rem(self, rhs: {n}) -> ({n}, bool) {{ if rhs == -1 {{ (0, self == {n}::MIN) }} else {{ (self % rhs, false) }} }}");
        let _ = writeln!(o, "    pub const fn overflowing_abs(self) -> ({n}, bool) {{ if self < 0 {{ self.overflowing_neg() }} else {{ (self, false) }} }}");
    } else {
        let _ = writeln!(o, "    pub const fn overflowing_neg(self) -> ({n}, bool) {{ ((0 as {n}) - self, self != 0) }}");
        let _ = writeln!(o, "    pub const fn overflowing_div(self, rhs: {n}) -> ({n}, bool) {{ (self / rhs, false) }}");
        let _ = writeln!(o, "    pub const fn overflowing_rem(self, rhs: {n}) -> ({n}, bool) {{ (self % rhs, false) }}");
    }
    let _ = writeln!(o, "    pub const fn overflowing_shl(self, rhs: u32) -> ({n}, bool) {{ (((self as {u}) << (rhs & {})) as {n}, rhs >= {b}) }}", b - 1);
    let _ = writeln!(o, "    pub const fn overflowing_shr(self, rhs: u32) -> ({n}, bool) {{ (self >> (rhs & {}), rhs >= {b}) }}", b - 1);
    let _ = writeln!(o, "    pub const fn overflowing_pow(self, exp: u32) -> ({n}, bool) {{");
    let _ = writeln!(o, "        let mut base = self; let mut exp = exp; let mut acc: {n} = 1; let mut over = false;");
    let _ = writeln!(o, "        if exp == 0 {{ return (1, false); }}");
    let _ = writeln!(o, "        while exp > 1 {{ if (exp & 1) == 1 {{ let r = acc.overflowing_mul(base); acc = r.0; over |= r.1; }} exp /= 2; let r = base.overflowing_mul(base); base = r.0; over |= r.1; }}");
    let _ = writeln!(o, "        let r = acc.overflowing_mul(base); (r.0, over | r.1)\n    }}");
    // wrapping family
    for op in ["add", "sub", "mul", "neg", "div", "rem", "pow"] {
        let (args, call) = match op {
            "neg" => ("self".to_string(), "self.overflowing_neg()".to_string()),
            "pow" => (format!("self, exp: u32"), "self.overflowing_pow(exp)".to_string()),
            _ => (format!("self, rhs: {n}"), format!("self.overflowing_{op}(rhs)")),
        };
        let _ = writeln!(o, "    pub const fn wrapping_{op}({args}) -> {n} {{ {call}.0 }}");
    }
    let _ = writeln!(o, "    pub const fn wrapping_shl(self, rhs: u32) -> {n} {{ self.overflowing_shl(rhs).0 }}");
    let _ = writeln!(o, "    pub const fn wrapping_shr(self, rhs: u32) -> {n} {{ self.overflowing_shr(rhs).0 }}");
    if t.signed {
        let _ = writeln!(o, "    pub const fn wrapping_abs(self) -> {n} {{ self.overflowing_abs().0 }}");
    }
    // checked family
    for op in ["add", "sub", "mul"] {
        let _ = writeln!(o, "    pub const fn checked_{op}(self, rhs: {n}) -> Option<{n}> {{ let (r, o) = self.overflowing_{op}(rhs); if o {{ None }} else {{ Some(r) }} }}");
    }
    if t.signed {
        let _ = writeln!(o, "    pub const fn checked_div(self, rhs: {n}) -> Option<{n}> {{ if rhs == 0 || (self == {n}::MIN && rhs == -1) {{ None }} else {{ Some(self / rhs) }} }}");
        let _ = writeln!(o, "    pub const fn checked_rem(self, rhs: {n}) -> Option<{n}> {{ if rhs == 0 || (self == {n}::MIN && rhs == -1) {{ None }} else {{ Some(self % rhs) }} }}");
        let _ = writeln!(o, "    pub const fn checked_abs(self) -> Option<{n}> {{ if self == {n}::MIN {{ None }} else {{ Some(self.abs()) }} }}");
        let _ = writeln!(o, "    pub const fn checked_div_euclid(self, rhs: {n}) -> Option<{n}> {{ if rhs == 0 || (self == {n}::MIN && rhs == -1) {{ None }} else {{ Some(self.div_euclid(rhs)) }} }}");
        let _ = writeln!(o, "    pub const fn checked_rem_euclid(self, rhs: {n}) -> Option<{n}> {{ if rhs == 0 || (self == {n}::MIN && rhs == -1) {{ None }} else {{ Some(self.rem_euclid(rhs)) }} }}");
    } else {
        let _ = writeln!(o, "    pub const fn checked_div(self, rhs: {n}) -> Option<{n}> {{ if rhs == 0 {{ None }} else {{ Some(self / rhs) }} }}");
        let _ = writeln!(o, "    pub const fn checked_rem(self, rhs: {n}) -> Option<{n}> {{ if rhs == 0 {{ None }} else {{ Some(self % rhs) }} }}");
        let _ = writeln!(o, "    pub const fn checked_div_euclid(self, rhs: {n}) -> Option<{n}> {{ self.checked_div(rhs) }}");
        let _ = writeln!(o, "    pub const fn checked_rem_euclid(self, rhs: {n}) -> Option<{n}> {{ self.checked_rem(rhs) }}");
    }
    let _ = writeln!(o, "    pub const fn checked_neg(self) -> Option<{n}> {{ let (r, o) = self.overflowing_neg(); if o {{ None }} else {{ Some(r) }} }}");
    let _ = writeln!(o, "    pub const fn checked_shl(self, rhs: u32) -> Option<{n}> {{ if rhs < {b} {{ Some(self.wrapping_shl(rhs)) }} else {{ None }} }}");
    let _ = writeln!(o, "    pub const fn checked_shr(self, rhs: u32) -> Option<{n}> {{ if rhs < {b} {{ Some(self.wrapping_shr(rhs)) }} else {{ None }} }}");
    let _ = writeln!(o, "    pub const fn checked_pow(self, exp: u32) -> Option<{n}> {{ let (r, o) = self.overflowing_pow(exp); if o {{ None }} else {{ Some(r) }} }}");
    // saturating
    if t.signed {
        let _ = writeln!(o, "    pub const fn saturating_add(self, rhs: {n}) -> {n} {{ match self.checked_add(rhs) {{ Some(v) => v, None => if rhs > 0 {{ {n}::MAX }} else {{ {n}::MIN }} }} }}");
        let _ = writeln!(o, "    pub const fn saturating_sub(self, rhs: {n}) -> {n} {{ match self.checked_sub(rhs) {{ Some(v) => v, None => if rhs > 0 {{ {n}::MIN }} else {{ {n}::MAX }} }} }}");
        let _ = writeln!(o, "    pub const fn saturating_mul(self, rhs: {n}) -> {n} {{ match self.checked_mul(rhs) {{ Some(v) => v, None => if (self < 0) == (rhs < 0) {{ {n}::MAX }} else {{ {n}::MIN }} }} }}");
        let _ = writeln!(o, "    pub const fn saturating_pow(self, exp: u32) -> {n} {{ match self.checked_pow(exp) {{ Some(v) => v, None => if self < 0 && exp % 2 == 1 {{ {n}::MIN }} else {{ {n}::MAX }} }} }}");
        let _ = writeln!(o, "    pub const fn saturating_neg(self) -> {n} {{ if self == {n}::MIN {{ {n}::MAX }} else {{ -self }} }}");
        let _ = writeln!(o, "    pub const fn saturating_abs(self) -> {n} {{ if self == {n}::MIN {{ {n}::MAX }} else {{ self.abs() }} }}");
        let _ = writeln!(o, "    pub const fn saturating_div(self, rhs: {n}) -> {n} {{ match self.overflowing_div(rhs) {{ (r, false) => r, (_, true) => {n}::MAX }} }}");
    } else {
        let _ = writeln!(o, "    pub const fn saturating_add(self, rhs: {n}) -> {n} {{ match self.checked_add(rhs) {{ Some(v) => v, None => {n}::MAX }} }}");
        let _ = writeln!(o, "    pub const fn saturating_sub(self, rhs: {n}) -> {n} {{ if self > rhs {{ self - rhs }} else {{ 0 }} }}");
        let _ = writeln!(o, "    pub const fn saturating_mul(self, rhs: {n}) -> {n} {{ match self.checked_mul(rhs) {{ Some(v) => v, None => {n}::MAX }} }}");
        let _ = writeln!(o, "    pub const fn saturating_pow(self, exp: u32) -> {n} {{ match self.checked_pow(exp) {{ Some(v) => v, None => {n}::MAX }} }}");
        let _ = writeln!(o, "    pub const fn saturating_div(self, rhs: {n}) -> {n} {{ self / rhs }}");
    }
    // pow etc (release semantics: wrapping)
    let _ = writeln!(o, "    pub const fn pow(self, exp: u32) -> {n} {{ self.wrapping_pow(exp) }}");
    let _ = writeln!(o, "    pub const fn abs_diff(self, other: {n}) -> {u} {{ if self < other {{ (other as {u}).wrapping_sub(self as {u}) }} else {{ (self as {u}).wrapping_sub(other as {u}) }} }}");
    if t.signed {
        let _ = writeln!(o, "    pub const fn abs(self) -> {n} {{ if self < 0 {{ self.wrapping_neg() }} else {{ self }} }}");
        let _ = writeln!(o, "    pub const fn unsigned_abs(self) -> {u} {{ self.wrapping_abs() as {u} }}");
        let _ = writeln!(o, "    pub const fn signum(self) -> {n} {{ if self < 0 {{ -1 }} else if self == 0 {{ 0 }} else {{ 1 }} }}");
        let _ = writeln!(o, "    pub const fn is_positive(self) -> bool {{ self > 0 }}");
        let _ = writeln!(o, "    pub const fn is_negative(self) -> bool {{ self < 0 }}");
        let _ = writeln!(o, "    pub const fn rem_euclid(self, rhs: {n}) -> {n} {{ let r = self % rhs; if r < 0 {{ r.wrapping_add(rhs.wrapping_abs()) }} else {{ r }} }}");
        let _ = writeln!(o, "    pub const fn div_euclid(self, rhs: {n}) -> {n} {{ let q = self / rhs; if self % rhs < 0 {{ if rhs > 0 {{ q - 1 }} else {{ q + 1 }} }} else {{ q }} }}");
        let _ = writeln!(o, "    pub const fn cast_unsigned(self) -> {u} {{ self as {u} }}");
        let _ = writeln!(o, "    pub const fn overflowing_add_unsigned(self, rhs: {u}) -> ({n}, bool) {{ let rhs = rhs as {n}; let (res, o) = self.overflowing_add(rhs); (res, o ^ (rhs < 0)) }}");
        let _ = writeln!(o, "    pub const fn checked_add_unsigned(self, rhs: {u}) -> Option<{n}> {{ let (a, b) = self.overflowing_add_unsigned(rhs); if b {{ None }} else {{ Some(a) }} }}");
        let _ = writeln!(o, "    pub const fn saturating_add_unsigned(self, rhs: {u}) -> {n} {{ match self.checked_add_unsigned(rhs) {{ Some(v) => v, None => {n}::MAX }} }}");
        let _ = writeln!(o, "    pub const fn wrapping_add_unsigned(self, rhs: {u}) -> {n} {{ self.wrapping_add(rhs as {n}) }}");
    } else {
        let s = signed_of(n);
        let _ = writeln!(o, "    pub const fn rem_euclid(self, rhs: {n}) -> {n} {{ self % rhs }}");
        let _ = writeln!(o, "    pub const fn div_euclid(self, rhs: {n}) -> {n} {{ self / rhs }}");
        let _ = writeln!(o, "    pub const fn div_ceil(self, rhs: {n}) -> {n} {{ let d = self / rhs; let r = self % rhs; if r > 0 {{ d + 1 }} else {{ d }} }}");
        let _ = writeln!(o, "    pub const fn next_multiple_of(self, rhs: {n}) -> {n} {{ match self % rhs {{ 0 => self, r => self + (rhs - r) }} }}");
        let _ = writeln!(o, "    pub const fn checked_next_multiple_of(self, rhs: {n}) -> Option<{n}> {{ if rhs == 0 {{ return None; }} match self % rhs {{ 0 => Some(self), r => self.checked_add(rhs - r) }} }}");
        let _ = writeln!(o, "    pub const fn is_power_of_two(self) -> bool {{ self.count_ones() == 1 }}");
        let _ = writeln!(o, "    const fn one_less_than_next_power_of_two(self) -> {n} {{ if self <= 1 {{ return 0; }} let p = self - 1; let z = p.leading_zeros(); {n}::MAX >> z }}");
        let _ = writeln!(o, "    pub const fn next_power_of_two(self) -> {n} {{ self.one_less_than_next_power_of_two().wrapping_add(1) }}");
        let _ = writeln!(o, "    pub const fn checked_next_power_of_two(self) -> Option<{n}> {{ self.one_less_than_next_power_of_two().checked_add(1) }}");
        let _ = writeln!(o, "    pub const fn cast_signed(self) -> {s} {{ self as {s} }}");
        let _ = writeln!(o, "    pub const fn checked_add_signed(self, rhs: {s}) -> Option<{n}> {{ let (a, b) = self.overflowing_add(rhs as {n}); if b ^ (rhs < 0) {{ None }} else {{ Some(a) }} }}");
        let _ = writeln!(o, "    pub const fn wrapping_add_signed(self, rhs: {s}) -> {n} {{ self.wrapping_add(rhs as {n}) }}");
        let _ = writeln!(o, "    pub const fn saturating_add_signed(self, rhs: {s}) -> {n} {{ let (res, over) = self.overflowing_add(rhs as {n}); if over == (rhs < 0) {{ res }} else if over {{ {n}::MAX }} else {{ 0 }} }}");
        let _ = writeln!(o, "    pub const fn checked_sub_signed(self, rhs: {s}) -> Option<{n}> {{ if rhs >= 0 {{ self.checked_sub(rhs as {n}) }} else {{ self.checked_add(rhs.unsigned_abs()) }} }}");
        let _ = writeln!(o, "    pub const fn isqrt(self) -> {n} {{ if self < 2 {{ return self; }} let mut x = self; let mut c: {n} = 0; let mut d: {n} = 1 << ((({b} - 1) - self.leading_zeros()) & !1); while d != 0 {{ if x >= c + d {{ x -= c + d; c = (c >> 1) + d; }} else {{ c >>= 1; }} d >>= 2; }} c }}");
    }
    // logarithms
    let _ = writeln!(o, "    pub const fn checked_ilog2(self) -> Option<u32> {{ if self <= 0 {{ None }} else {{ Some({} - self.leading_zeros()) }} }}", b - 1);
    let _ = writeln!(o, "    pub const fn checked_ilog10(self) -> Option<u32> {{ if self <= 0 {{ return None; }} let mut n = 0u32; let mut v = self; while v >= 10 {{ v /= 10; n += 1; }} Some(n) }}");
    let _ = writeln!(o, "    pub const fn checked_ilog(self, base: {n}) -> Option<u32> {{ if self <= 0 || base < 2 {{ return None; }} let mut n = 0u32; let mut r = self; while r >= base {{ r /= base; n += 1; }} Some(n) }}");
    let _ = writeln!(o, "    #[track_caller]\n    pub const fn ilog2(self) -> u32 {{ match self.checked_ilog2() {{ Some(v) => v, None => crate::panicking::panic_str(\"argument of integer logarithm must be positive\") }} }}");
    let _ = writeln!(o, "    #[track_caller]\n    pub const fn ilog10(self) -> u32 {{ match self.checked_ilog10() {{ Some(v) => v, None => crate::panicking::panic_str(\"argument of integer logarithm must be positive\") }} }}");
    let _ = writeln!(o, "    #[track_caller]\n    pub const fn ilog(self, base: {n}) -> u32 {{ if base < 2 {{ crate::panicking::panic_str(\"base of integer logarithm must be at least 2\") }} match self.checked_ilog(base) {{ Some(v) => v, None => crate::panicking::panic_str(\"argument of integer logarithm must be positive\") }} }}");
    // bytes
    let _ = writeln!(o, "    pub const fn to_le_bytes(self) -> [u8; {bytes}] {{");
    let _ = writeln!(o, "        let v = self as {u};");
    let mut elems = Vec::new();
    for i in 0..bytes {
        elems.push(format!("(v >> {}) as u8", i * 8));
    }
    let _ = writeln!(o, "        [{}]\n    }}", elems.join(", "));
    let _ = writeln!(o, "    pub const fn to_be_bytes(self) -> [u8; {bytes}] {{ self.swap_bytes().to_le_bytes() }}");
    let _ = writeln!(o, "    pub const fn to_ne_bytes(self) -> [u8; {bytes}] {{ self.to_le_bytes() }}");
    let _ = writeln!(o, "    pub const fn from_le_bytes(bytes: [u8; {bytes}]) -> {n} {{");
    let mut terms = Vec::new();
    for i in 0..bytes {
        terms.push(format!("((bytes[{i}] as {u}) << {})", i * 8));
    }
    let _ = writeln!(o, "        ({}) as {n}\n    }}", terms.join(" | "));
    let _ = writeln!(o, "    pub const fn from_be_bytes(bytes: [u8; {bytes}]) -> {n} {{ {n}::from_le_bytes(bytes).swap_bytes() }}");
    let _ = writeln!(o, "    pub const fn from_ne_bytes(bytes: [u8; {bytes}]) -> {n} {{ {n}::from_le_bytes(bytes) }}");
    // parsing
    if t.bits == 128 {
        if t.signed {
            let _ = writeln!(o, "    pub fn from_str_radix(src: &str, radix: u32) -> Result<{n}, ParseIntError> {{ parse::parse_i128(src.as_bytes(), radix) }}");
        } else {
            let _ = writeln!(o, "    pub fn from_str_radix(src: &str, radix: u32) -> Result<{n}, ParseIntError> {{ parse::parse_u128(src.as_bytes(), radix) }}");
        }
    } else if t.signed {
        let _ = writeln!(
            o,
            "    pub fn from_str_radix(src: &str, radix: u32) -> Result<{n}, ParseIntError> {{ match parse::parse_signed(src.as_bytes(), radix, {n}::MIN as i64, {n}::MAX as i64) {{ Ok(v) => Ok(v as {n}), Err(e) => Err(e) }} }}"
        );
    } else {
        let _ = writeln!(
            o,
            "    pub fn from_str_radix(src: &str, radix: u32) -> Result<{n}, ParseIntError> {{ match parse::parse_unsigned(src.as_bytes(), radix, {n}::MAX as u64) {{ Ok(v) => Ok(v as {n}), Err(e) => Err(e) }} }}"
        );
    }
    o.push_str("}\n\n");
}

fn signed_of(u: &str) -> &'static str {
    match u {
        "u8" => "i8",
        "u16" => "i16",
        "u32" => "i32",
        "u64" => "i64",
        "u128" => "i128",
        _ => "isize",
    }
}

fn gen_u8_ascii(o: &mut String) {
    o.push_str(
        r#"#[cfg(not(rapid_check))]
impl u8 {
    pub const fn is_ascii(&self) -> bool { *self < 128 }
    pub const fn is_ascii_alphabetic(&self) -> bool { matches!(*self, b'A'..=b'Z' | b'a'..=b'z') }
    pub const fn is_ascii_uppercase(&self) -> bool { matches!(*self, b'A'..=b'Z') }
    pub const fn is_ascii_lowercase(&self) -> bool { matches!(*self, b'a'..=b'z') }
    pub const fn is_ascii_alphanumeric(&self) -> bool { matches!(*self, b'0'..=b'9' | b'A'..=b'Z' | b'a'..=b'z') }
    pub const fn is_ascii_digit(&self) -> bool { matches!(*self, b'0'..=b'9') }
    pub const fn is_ascii_octdigit(&self) -> bool { matches!(*self, b'0'..=b'7') }
    pub const fn is_ascii_hexdigit(&self) -> bool { matches!(*self, b'0'..=b'9' | b'A'..=b'F' | b'a'..=b'f') }
    pub const fn is_ascii_punctuation(&self) -> bool { matches!(*self, b'!'..=b'/' | b':'..=b'@' | b'['..=b'`' | b'{'..=b'~') }
    pub const fn is_ascii_graphic(&self) -> bool { matches!(*self, b'!'..=b'~') }
    pub const fn is_ascii_whitespace(&self) -> bool { matches!(*self, b'\t' | b'\n' | b'\x0C' | b'\r' | b' ') }
    pub const fn is_ascii_control(&self) -> bool { matches!(*self, b'\0'..=b'\x1F' | b'\x7F') }
    pub const fn to_ascii_uppercase(&self) -> u8 { if self.is_ascii_lowercase() { *self - 32 } else { *self } }
    pub const fn to_ascii_lowercase(&self) -> u8 { if self.is_ascii_uppercase() { *self + 32 } else { *self } }
    pub const fn eq_ignore_ascii_case(&self, other: &u8) -> bool { self.to_ascii_lowercase() == other.to_ascii_lowercase() }
    pub fn make_ascii_uppercase(&mut self) { *self = self.to_ascii_uppercase(); }
    pub fn make_ascii_lowercase(&mut self) { *self = self.to_ascii_lowercase(); }
}

"#,
    );
}

fn gen_float(o: &mut String, f: &str) {
    let is64 = f == "f64";
    let bits_t = if is64 { "u64" } else { "u32" };
    let sfx = if is64 { "" } else { "f" };
    let _ = writeln!(o, "#[cfg(not(rapid_check))]\nimpl {f} {{");
    if is64 {
        o.push_str(
            "    pub const RADIX: u32 = 2;
    pub const MANTISSA_DIGITS: u32 = 53;
    pub const DIGITS: u32 = 15;
    pub const EPSILON: f64 = 2.2204460492503131e-16_f64;
    pub const MIN: f64 = -1.7976931348623157e+308_f64;
    pub const MIN_POSITIVE: f64 = 2.2250738585072014e-308_f64;
    pub const MAX: f64 = 1.7976931348623157e+308_f64;
    pub const MIN_EXP: i32 = -1021;
    pub const MAX_EXP: i32 = 1024;
    pub const MIN_10_EXP: i32 = -307;
    pub const MAX_10_EXP: i32 = 308;
    pub const NAN: f64 = f64::from_bits(0x7ff8_0000_0000_0000);
    pub const INFINITY: f64 = f64::from_bits(0x7ff0_0000_0000_0000);
    pub const NEG_INFINITY: f64 = f64::from_bits(0xfff0_0000_0000_0000);
",
        );
    } else {
        o.push_str(
            "    pub const RADIX: u32 = 2;
    pub const MANTISSA_DIGITS: u32 = 24;
    pub const DIGITS: u32 = 6;
    pub const EPSILON: f32 = 1.19209290e-07_f32;
    pub const MIN: f32 = -3.40282347e+38_f32;
    pub const MIN_POSITIVE: f32 = 1.17549435e-38_f32;
    pub const MAX: f32 = 3.40282347e+38_f32;
    pub const MIN_EXP: i32 = -125;
    pub const MAX_EXP: i32 = 128;
    pub const MIN_10_EXP: i32 = -37;
    pub const MAX_10_EXP: i32 = 38;
    pub const NAN: f32 = f32::from_bits(0x7fc0_0000);
    pub const INFINITY: f32 = f32::from_bits(0x7f80_0000);
    pub const NEG_INFINITY: f32 = f32::from_bits(0xff80_0000);
",
        );
    }
    let (sign, expmask, manmask) = if is64 {
        ("0x8000_0000_0000_0000", "0x7ff0_0000_0000_0000", "0x000f_ffff_ffff_ffff")
    } else {
        ("0x8000_0000", "0x7f80_0000", "0x007f_ffff")
    };
    let _ = writeln!(o, "    pub const fn to_bits(self) -> {bits_t} {{ unsafe {{ intrinsics::to_bits_{f}(self) }} }}");
    let _ = writeln!(o, "    pub const fn from_bits(v: {bits_t}) -> {f} {{ unsafe {{ intrinsics::from_bits_{f}(v) }} }}");
    let _ = writeln!(o, "    pub const fn is_nan(self) -> bool {{ self != self }}");
    let _ = writeln!(o, "    pub const fn is_infinite(self) -> bool {{ (self.to_bits() & !{sign}) == {expmask} }}");
    let _ = writeln!(o, "    pub const fn is_finite(self) -> bool {{ (self.to_bits() & {expmask}) != {expmask} }}");
    let _ = writeln!(o, "    pub const fn is_subnormal(self) -> bool {{ matches!(self.classify(), FpCategory::Subnormal) }}");
    let _ = writeln!(o, "    pub const fn is_normal(self) -> bool {{ matches!(self.classify(), FpCategory::Normal) }}");
    let _ = writeln!(o, "    pub const fn classify(self) -> FpCategory {{ let b = self.to_bits(); match (b & {manmask}, b & {expmask}) {{ (0, {expmask}) => FpCategory::Infinite, (_, {expmask}) => FpCategory::Nan, (0, 0) => FpCategory::Zero, (_, 0) => FpCategory::Subnormal, _ => FpCategory::Normal }} }}");
    let _ = writeln!(o, "    pub const fn is_sign_positive(self) -> bool {{ !self.is_sign_negative() }}");
    let _ = writeln!(o, "    pub const fn is_sign_negative(self) -> bool {{ (self.to_bits() & {sign}) != 0 }}");
    let _ = writeln!(o, "    pub const fn abs(self) -> {f} {{ unsafe {{ intrinsics::fabs_{f}(self) }} }}");
    let _ = writeln!(o, "    pub const fn copysign(self, sign: {f}) -> {f} {{ {f}::from_bits((self.to_bits() & !{sign}) | (sign.to_bits() & {sign})) }}");
    let _ = writeln!(o, "    pub const fn signum(self) -> {f} {{ if self.is_nan() {{ {f}::NAN }} else {{ (1.0 as {f}).copysign(self) }} }}");
    for (m, i) in [("sqrt", "sqrt"), ("floor", "floor"), ("ceil", "ceil"), ("trunc", "trunc"), ("round_ties_even", "rint")] {
        let _ = writeln!(o, "    pub fn {m}(self) -> {f} {{ unsafe {{ intrinsics::{i}_{f}(self) }} }}");
    }
    let _ = writeln!(o, "    pub fn round(self) -> {f} {{ unsafe {{ libm::round{sfx}(self) }} }}");
    let _ = writeln!(o, "    pub fn fract(self) -> {f} {{ self - self.trunc() }}");
    let _ = writeln!(o, "    pub fn min(self, other: {f}) -> {f} {{ unsafe {{ intrinsics::fmin_{f}(self, other) }} }}");
    let _ = writeln!(o, "    pub fn max(self, other: {f}) -> {f} {{ unsafe {{ intrinsics::fmax_{f}(self, other) }} }}");
    let _ = writeln!(o, "    pub fn minimum(self, other: {f}) -> {f} {{ if self < other {{ self }} else if other < self {{ other }} else if self == other {{ if self.is_sign_negative() && other.is_sign_positive() {{ self }} else {{ other }} }} else {{ self + other }} }}");
    let _ = writeln!(o, "    pub fn maximum(self, other: {f}) -> {f} {{ if self > other {{ self }} else if other > self {{ other }} else if self == other {{ if self.is_sign_positive() && other.is_sign_negative() {{ self }} else {{ other }} }} else {{ self + other }} }}");
    let _ = writeln!(o, "    #[track_caller]\n    pub fn clamp(self, min: {f}, max: {f}) -> {f} {{ if !(min <= max) {{ crate::panicking::panic_fmt(format_args!(\"min > max, or either was NaN. min = {{min:?}}, max = {{max:?}}\")); }} let mut x = self; if x < min {{ x = min; }} if x > max {{ x = max; }} x }}");
    let _ = writeln!(o, "    pub fn mul_add(self, a: {f}, b: {f}) -> {f} {{ unsafe {{ libm::fma{sfx}(self, a, b) }} }}");
    let _ = writeln!(o, "    pub fn div_euclid(self, rhs: {f}) -> {f} {{ let q = (self / rhs).trunc(); if self % rhs < 0.0 {{ return if rhs > 0.0 {{ q - 1.0 }} else {{ q + 1.0 }}; }} q }}");
    let _ = writeln!(o, "    pub fn rem_euclid(self, rhs: {f}) -> {f} {{ let r = self % rhs; if r < 0.0 {{ r + rhs.abs() }} else {{ r }} }}");
    // compiler-rt __powidf2 / __powisf2
    let _ = writeln!(o, "    pub fn powi(self, n: i32) -> {f} {{ let recip = n < 0; let mut b = n; let mut a = self; let mut r: {f} = 1.0; loop {{ if (b & 1) != 0 {{ r *= a; }} b /= 2; if b == 0 {{ break; }} a *= a; }} if recip {{ 1.0 / r }} else {{ r }} }}");
    for (m, c) in [
        ("powf", "pow"),
    ] {
        let _ = writeln!(o, "    pub fn {m}(self, n: {f}) -> {f} {{ unsafe {{ libm::{c}{sfx}(self, n) }} }}");
    }
    for (m, c) in [
        ("exp", "exp"),
        ("exp2", "exp2"),
        ("exp_m1", "expm1"),
        ("ln", "log"),
        ("log2", "log2"),
        ("log10", "log10"),
        ("ln_1p", "log1p"),
        ("cbrt", "cbrt"),
        ("sin", "sin"),
        ("cos", "cos"),
        ("tan", "tan"),
        ("asin", "asin"),
        ("acos", "acos"),
        ("atan", "atan"),
        ("sinh", "sinh"),
        ("cosh", "cosh"),
        ("tanh", "tanh"),
    ] {
        let _ = writeln!(o, "    pub fn {m}(self) -> {f} {{ unsafe {{ libm::{c}{sfx}(self) }} }}");
    }
    let _ = writeln!(o, "    pub fn atan2(self, other: {f}) -> {f} {{ unsafe {{ libm::atan2{sfx}(self, other) }} }}");
    let _ = writeln!(o, "    pub fn hypot(self, other: {f}) -> {f} {{ unsafe {{ libm::hypot{sfx}(self, other) }} }}");
    let _ = writeln!(o, "    pub fn log(self, base: {f}) -> {f} {{ self.ln() / base.ln() }}");
    let _ = writeln!(o, "    pub fn sin_cos(self) -> ({f}, {f}) {{ (self.sin(), self.cos()) }}");
    let _ = writeln!(o, "    pub fn asinh(self) -> {f} {{ let ax = self.abs(); let ix = 1.0 / ax; (ax + (ax / ((1.0 as {f}).hypot(ix) + ix))).ln_1p().copysign(self) }}");
    let _ = writeln!(o, "    pub fn acosh(self) -> {f} {{ if self < 1.0 {{ {f}::NAN }} else {{ (self + ((self - 1.0).sqrt() * (self + 1.0).sqrt())).ln() }} }}");
    let _ = writeln!(o, "    pub fn atanh(self) -> {f} {{ 0.5 * ((2.0 * self) / (1.0 - self)).ln_1p() }}");
    if is64 {
        let _ = writeln!(o, "    pub fn to_degrees(self) -> f64 {{ self * (180.0f64 / crate::f64::consts::PI) }}");
        let _ = writeln!(o, "    pub fn to_radians(self) -> f64 {{ self * (crate::f64::consts::PI / 180.0) }}");
    } else {
        let _ = writeln!(o, "    pub fn to_degrees(self) -> f32 {{ const PIS_IN_180: f32 = 57.2957795130823208767981548141051703_f32; self * PIS_IN_180 }}");
        let _ = writeln!(o, "    pub fn to_radians(self) -> f32 {{ self * (crate::f32::consts::PI / 180.0f32) }}");
    }
    let _ = writeln!(o, "    pub fn recip(self) -> {f} {{ 1.0 / self }}");
    let ibits = if is64 { "i64" } else { "i32" };
    let shift = if is64 { 63 } else { 31 };
    let _ = writeln!(o, "    pub fn total_cmp(&self, other: &{f}) -> Ordering {{ let mut l = self.to_bits() as {ibits}; let mut r = other.to_bits() as {ibits}; l ^= (((l >> {shift}) as {bits_t}) >> 1) as {ibits}; r ^= (((r >> {shift}) as {bits_t}) >> 1) as {ibits}; l.cmp(&r) }}");
    let nb = if is64 { 8 } else { 4 };
    let _ = writeln!(o, "    pub fn to_le_bytes(self) -> [u8; {nb}] {{ self.to_bits().to_le_bytes() }}");
    let _ = writeln!(o, "    pub fn to_be_bytes(self) -> [u8; {nb}] {{ self.to_bits().to_be_bytes() }}");
    let _ = writeln!(o, "    pub fn to_ne_bytes(self) -> [u8; {nb}] {{ self.to_bits().to_ne_bytes() }}");
    let _ = writeln!(o, "    pub fn from_le_bytes(b: [u8; {nb}]) -> {f} {{ {f}::from_bits({bits_t}::from_le_bytes(b)) }}");
    let _ = writeln!(o, "    pub fn from_be_bytes(b: [u8; {nb}]) -> {f} {{ {f}::from_bits({bits_t}::from_be_bytes(b)) }}");
    let _ = writeln!(o, "    pub fn from_ne_bytes(b: [u8; {nb}]) -> {f} {{ {f}::from_bits({bits_t}::from_ne_bytes(b)) }}");
    let _ = writeln!(o, "    pub fn midpoint(self, other: {f}) -> {f} {{ ((self as f64 + other as f64) / 2.0) as {f} }}");
    o.push_str("}\n\n");
}

fn op_impls(o: &mut String, n: &str, ops: &[(&str, &str, &str)]) {
    for (tr, m, sym) in ops {
        let _ = writeln!(o, "impl {tr} for {n} {{ type Output = {n}; fn {m}(self, rhs: {n}) -> {n} {{ self {sym} rhs }} }}");
        let _ = writeln!(o, "impl<'a> {tr}<&'a {n}> for {n} {{ type Output = {n}; fn {m}(self, rhs: &'a {n}) -> {n} {{ self {sym} *rhs }} }}");
        let _ = writeln!(o, "impl<'a> {tr}<{n}> for &'a {n} {{ type Output = {n}; fn {m}(self, rhs: {n}) -> {n} {{ *self {sym} rhs }} }}");
        let _ = writeln!(o, "impl<'a, 'b> {tr}<&'a {n}> for &'b {n} {{ type Output = {n}; fn {m}(self, rhs: &'a {n}) -> {n} {{ *self {sym} *rhs }} }}");
        let _ = writeln!(o, "impl {tr}Assign for {n} {{ fn {m}_assign(&mut self, rhs: {n}) {{ *self = *self {sym} rhs; }} }}");
        let _ = writeln!(o, "impl<'a> {tr}Assign<&'a {n}> for {n} {{ fn {m}_assign(&mut self, rhs: &'a {n}) {{ *self = *self {sym} *rhs; }} }}");
    }
}

fn gen_int_traits(o: &mut String, t: &Int) {
    let n = t.name;
    let _ = writeln!(o, "// ---- {n}");
    let _ = writeln!(o, "impl Clone for {n} {{ fn clone(&self) -> {n} {{ *self }} }}");
    let _ = writeln!(o, "impl Copy for {n} {{}}");
    let _ = writeln!(o, "impl Default for {n} {{ fn default() -> {n} {{ 0 }} }}");
    let _ = writeln!(o, "impl PartialEq for {n} {{ fn eq(&self, other: &{n}) -> bool {{ *self == *other }} fn ne(&self, other: &{n}) -> bool {{ *self != *other }} }}");
    let _ = writeln!(o, "impl Eq for {n} {{}}");
    let _ = writeln!(o, "impl PartialOrd for {n} {{ fn partial_cmp(&self, other: &{n}) -> Option<Ordering> {{ Some(self.cmp(other)) }} fn lt(&self, other: &{n}) -> bool {{ *self < *other }} fn le(&self, other: &{n}) -> bool {{ *self <= *other }} fn gt(&self, other: &{n}) -> bool {{ *self > *other }} fn ge(&self, other: &{n}) -> bool {{ *self >= *other }} }}");
    let _ = writeln!(o, "impl Ord for {n} {{ fn cmp(&self, other: &{n}) -> Ordering {{ if *self < *other {{ Ordering::Less }} else if *self == *other {{ Ordering::Equal }} else {{ Ordering::Greater }} }} }}");
    op_impls(
        o,
        n,
        &[("Add", "add", "+"), ("Sub", "sub", "-"), ("Mul", "mul", "*"), ("Div", "div", "/"), ("Rem", "rem", "%"), ("BitAnd", "bitand", "&"), ("BitOr", "bitor", "|"), ("BitXor", "bitxor", "^")],
    );
    let mut rhs_types: Vec<&str> = vec![n];
    for r in ["u32", "i32", "usize"] {
        if r != n {
            rhs_types.push(r);
        }
    }
    for r in rhs_types {
        for (tr, m, sym) in [("Shl", "shl", "<<"), ("Shr", "shr", ">>")] {
            let _ = writeln!(o, "impl {tr}<{r}> for {n} {{ type Output = {n}; fn {m}(self, rhs: {r}) -> {n} {{ self {sym} rhs }} }}");
            let _ = writeln!(o, "impl {tr}Assign<{r}> for {n} {{ fn {m}_assign(&mut self, rhs: {r}) {{ *self = *self {sym} rhs; }} }}");
        }
    }
    let _ = writeln!(o, "impl Not for {n} {{ type Output = {n}; fn not(self) -> {n} {{ !self }} }}");
    let _ = writeln!(o, "impl<'a> Not for &'a {n} {{ type Output = {n}; fn not(self) -> {n} {{ !*self }} }}");
    if t.signed {
        let _ = writeln!(o, "impl Neg for {n} {{ type Output = {n}; fn neg(self) -> {n} {{ -self }} }}");
        let _ = writeln!(o, "impl<'a> Neg for &'a {n} {{ type Output = {n}; fn neg(self) -> {n} {{ -*self }} }}");
    }
    let _ = writeln!(o, "impl Sum for {n} {{ fn sum<I: Iterator<Item = {n}>>(iter: I) -> {n} {{ crate::iter::sum_from(0, iter) }} }}");
    let _ = writeln!(o, "impl<'a> Sum<&'a {n}> for {n} {{ fn sum<I: Iterator<Item = &'a {n}>>(iter: I) -> {n} {{ crate::iter::sum_from(0, iter.copied()) }} }}");
    let _ = writeln!(o, "impl Product for {n} {{ fn product<I: Iterator<Item = {n}>>(iter: I) -> {n} {{ crate::iter::product_from(1, iter) }} }}");
    let _ = writeln!(o, "impl<'a> Product<&'a {n}> for {n} {{ fn product<I: Iterator<Item = &'a {n}>>(iter: I) -> {n} {{ crate::iter::product_from(1, iter.copied()) }} }}");
    let _ = writeln!(o, "impl FromStr for {n} {{ type Err = ParseIntError; fn from_str(src: &str) -> Result<{n}, ParseIntError> {{ {n}::from_str_radix(src, 10) }} }}");
    gen_step(o, t);
    o.push('\n');
}

fn gen_step(o: &mut String, t: &Int) {
    let n = t.name;
    let u = t.unsigned;
    let _ = writeln!(o, "impl Step for {n} {{");
    // steps_between: number of successor steps, as core
    if t.bits <= 64 {
        let _ = writeln!(o, "    fn steps_between(start: &{n}, end: &{n}) -> (usize, Option<usize>) {{ if *start <= *end {{ let s = (*end as {u}).wrapping_sub(*start as {u}) as usize; (s, Some(s)) }} else {{ (0, None) }} }}");
    } else {
        let _ = writeln!(o, "    fn steps_between(start: &{n}, end: &{n}) -> (usize, Option<usize>) {{ if *start <= *end {{ let s = (*end as {u}).wrapping_sub(*start as {u}); if s <= usize::MAX as {u} {{ (s as usize, Some(s as usize)) }} else {{ (usize::MAX, None) }} }} else {{ (0, None) }} }}");
    }
    if t.signed {
        let _ = writeln!(o, "    fn forward_checked(start: {n}, n: usize) -> Option<{n}> {{ if (n as u128) > ({u}::MAX as u128) {{ return None; }} let w = start.wrapping_add(n as {u} as {n}); if w >= start {{ Some(w) }} else {{ None }} }}");
        let _ = writeln!(o, "    fn backward_checked(start: {n}, n: usize) -> Option<{n}> {{ if (n as u128) > ({u}::MAX as u128) {{ return None; }} let w = start.wrapping_sub(n as {u} as {n}); if w <= start {{ Some(w) }} else {{ None }} }}");
    } else {
        let _ = writeln!(o, "    fn forward_checked(start: {n}, n: usize) -> Option<{n}> {{ if (n as u128) > ({n}::MAX as u128) {{ return None; }} start.checked_add(n as {n}) }}");
        let _ = writeln!(o, "    fn backward_checked(start: {n}, n: usize) -> Option<{n}> {{ if (n as u128) > ({n}::MAX as u128) {{ return None; }} start.checked_sub(n as {n}) }}");
    }
    o.push_str("}\n");
}

fn gen_float_traits(o: &mut String, f: &str) {
    let _ = writeln!(o, "// ---- {f}");
    let _ = writeln!(o, "impl Clone for {f} {{ fn clone(&self) -> {f} {{ *self }} }}");
    let _ = writeln!(o, "impl Copy for {f} {{}}");
    let _ = writeln!(o, "impl Default for {f} {{ fn default() -> {f} {{ 0.0 }} }}");
    let _ = writeln!(o, "impl PartialEq for {f} {{ fn eq(&self, other: &{f}) -> bool {{ *self == *other }} fn ne(&self, other: &{f}) -> bool {{ *self != *other }} }}");
    let _ = writeln!(o, "impl PartialOrd for {f} {{ fn partial_cmp(&self, other: &{f}) -> Option<Ordering> {{ if *self < *other {{ Some(Ordering::Less) }} else if *self > *other {{ Some(Ordering::Greater) }} else if *self == *other {{ Some(Ordering::Equal) }} else {{ None }} }} fn lt(&self, other: &{f}) -> bool {{ *self < *other }} fn le(&self, other: &{f}) -> bool {{ *self <= *other }} fn gt(&self, other: &{f}) -> bool {{ *self > *other }} fn ge(&self, other: &{f}) -> bool {{ *self >= *other }} }}");
    op_impls(o, f, &[("Add", "add", "+"), ("Sub", "sub", "-"), ("Mul", "mul", "*"), ("Div", "div", "/"), ("Rem", "rem", "%")]);
    let _ = writeln!(o, "impl Neg for {f} {{ type Output = {f}; fn neg(self) -> {f} {{ -self }} }}");
    let _ = writeln!(o, "impl<'a> Neg for &'a {f} {{ type Output = {f}; fn neg(self) -> {f} {{ -*self }} }}");
    let _ = writeln!(o, "impl Sum for {f} {{ fn sum<I: Iterator<Item = {f}>>(iter: I) -> {f} {{ crate::iter::sum_from(-0.0, iter) }} }}");
    let _ = writeln!(o, "impl<'a> Sum<&'a {f}> for {f} {{ fn sum<I: Iterator<Item = &'a {f}>>(iter: I) -> {f} {{ crate::iter::sum_from(-0.0, iter.copied()) }} }}");
    let _ = writeln!(o, "impl Product for {f} {{ fn product<I: Iterator<Item = {f}>>(iter: I) -> {f} {{ crate::iter::product_from(1.0, iter) }} }}");
    let _ = writeln!(o, "impl<'a> Product<&'a {f}> for {f} {{ fn product<I: Iterator<Item = &'a {f}>>(iter: I) -> {f} {{ crate::iter::product_from(1.0, iter.copied()) }} }}");
    let _ = writeln!(o, "impl FromStr for {f} {{ type Err = crate::num::ParseFloatError; fn from_str(src: &str) -> Result<{f}, crate::num::ParseFloatError> {{ crate::num::dec2flt::parse_{f}(src) }} }}");
    o.push('\n');
}

fn gen_bool_traits(o: &mut String) {
    o.push_str(
        "// ---- bool
impl Clone for bool { fn clone(&self) -> bool { *self } }
impl Copy for bool {}
impl Default for bool { fn default() -> bool { false } }
impl PartialEq for bool { fn eq(&self, other: &bool) -> bool { *self == *other } }
impl Eq for bool {}
impl PartialOrd for bool { fn partial_cmp(&self, other: &bool) -> Option<Ordering> { Some(self.cmp(other)) } }
impl Ord for bool { fn cmp(&self, other: &bool) -> Ordering { (*self as u8).cmp(&(*other as u8)) } }
impl Not for bool { type Output = bool; fn not(self) -> bool { !self } }
impl<'a> Not for &'a bool { type Output = bool; fn not(self) -> bool { !*self } }
impl BitAnd for bool { type Output = bool; fn bitand(self, rhs: bool) -> bool { self & rhs } }
impl BitOr for bool { type Output = bool; fn bitor(self, rhs: bool) -> bool { self | rhs } }
impl BitXor for bool { type Output = bool; fn bitxor(self, rhs: bool) -> bool { self ^ rhs } }
impl BitAndAssign for bool { fn bitand_assign(&mut self, rhs: bool) { *self = *self & rhs; } }
impl BitOrAssign for bool { fn bitor_assign(&mut self, rhs: bool) { *self = *self | rhs; } }
impl BitXorAssign for bool { fn bitxor_assign(&mut self, rhs: bool) { *self = *self ^ rhs; } }

#[cfg(not(rapid_check))]
impl bool {
    pub fn then_some<T>(self, t: T) -> Option<T> { if self { Some(t) } else { None } }
    pub fn then<T, F: FnOnce() -> T>(self, f: F) -> Option<T> { if self { Some(f()) } else { None } }
}

",
    );
}

/// value-preserving for every value of `from`?
fn lossless(from: &Int, to: &Int) -> bool {
    min_of(to) <= min_of(from) && max_of(to) >= max_of(from)
}

fn gen_conversions(o: &mut String) {
    o.push_str("// ---- conversions (From where real core has it, TryFrom for every other pair)\n");
    for from in INTS.iter() {
        for to in INTS.iter() {
            if from.name == to.name {
                continue;
            }
            if has_from(from, to) {
                let _ = writeln!(o, "impl From<{}> for {} {{ fn from(v: {}) -> {} {{ v as {} }} }}", from.name, to.name, from.name, to.name, to.name);
            } else {
                // range check written in the source type; core reports which side overflowed
                let mut body = String::new();
                if from.signed && min_of(to) > min_of(from) {
                    let lo = if min_of(to) == 0 { "0".to_string() } else { format!("({}) as {}", lit_min(to), from.name) };
                    body.push_str(&format!("if v < {lo} {{ return Err(TryFromIntError(IntErrorKind::NegOverflow)); }} "));
                }
                if max_of(to) < max_of(from) {
                    body.push_str(&format!("if v > {} as {} {{ return Err(TryFromIntError(IntErrorKind::PosOverflow)); }} ", max_of(to), from.name));
                }
                let _ = writeln!(
                    o,
                    "impl TryFrom<{f}> for {t} {{ type Error = TryFromIntError; fn try_from(v: {f}) -> Result<{t}, TryFromIntError> {{ {body}Ok(v as {t}) }} }}",
                    f = from.name,
                    t = to.name
                );
            }
        }
        let _ = writeln!(o, "impl From<bool> for {} {{ fn from(v: bool) -> {} {{ v as {} }} }}", from.name, from.name, from.name);
    }
    for (from, to) in [("i8", "f32"), ("i16", "f32"), ("u8", "f32"), ("u16", "f32"), ("i8", "f64"), ("i16", "f64"), ("i32", "f64"), ("u8", "f64"), ("u16", "f64"), ("u32", "f64"), ("f32", "f64")] {
        let _ = writeln!(o, "impl From<{from}> for {to} {{ fn from(v: {from}) -> {to} {{ v as {to} }} }}");
    }
    let _ = writeln!(o, "impl From<bool> for f32 {{ fn from(v: bool) -> f32 {{ v as u8 as f32 }} }}");
    let _ = writeln!(o, "impl From<bool> for f64 {{ fn from(v: bool) -> f64 {{ v as u8 as f64 }} }}");
}

/// Real core's lossless From impls between integers: widening within signedness, unsigned to
/// a strictly wider signed type, and usize/isize only from u8/u16 (bool separately); never
/// into or out of usize/isize otherwise.
fn has_from(from: &Int, to: &Int) -> bool {
    let size_types = |t: &Int| t.name == "usize" || t.name == "isize";
    if size_types(to) {
        return match (from.name, to.name) {
            ("u8", "usize") | ("u16", "usize") | ("u8", "isize") | ("i8", "isize") | ("i16", "isize") => true,
            _ => false,
        };
    }
    if size_types(from) {
        return false;
    }
    lossless(from, to)
}

fn is_ident(c: u8) -> bool {
    c == b'_' || c.is_ascii_alphanumeric()
}

/// Replaces the token `self` with `self.0`.
fn replace_self(line: &str) -> String {
    let b = line.as_bytes();
    let mut out = String::new();
    let mut i = 0;
    while i < b.len() {
        if line[i..].starts_with("self") && (i == 0 || !is_ident(b[i - 1])) && (i + 4 >= b.len() || !is_ident(b[i + 4])) {
            out.push_str("self.0");
            i += 4;
        } else {
            out.push(b[i] as char);
            i += 1;
        }
    }
    out
}

/// The rustc-checkable copy of int_impls.rs: each `impl T` becomes `impl H_T` on a newtype,
/// with `self` in bodies as `self.0`, so every generated method body runs under rustc with
/// the real methods it calls and is compared against the real method of the same name
/// (check/tests/core_num.rs).
fn check_copy(src: &str) -> String {
    let mut out = String::new();
    out.push_str("// GENERATED by check/src/gen_num.rs from core/num/int_impls.rs (rustc-checkable copy).\n");
    out.push_str("#![allow(non_camel_case_types, unused_parens, clippy::all)]\n");
    out.push_str("use crate::intrinsics_int as ii;\nuse crate::num::parse;\nuse crate::num::ParseIntError;\n\n");
    let mut cur = String::new();
    let mut skip = false;
    let mut seen_u8 = false;
    for line in src.lines() {
        if line.starts_with("use ") || line.starts_with("//") || line.starts_with("#[cfg(") {
            continue;
        }
        if let Some(rest) = line.strip_prefix("impl ") {
            let name = rest.trim_end_matches(" {").to_string();
            if name == "u8" && seen_u8 {
                skip = true;
                continue;
            }
            if name == "u8" {
                seen_u8 = true;
            }
            cur = name.clone();
            out.push_str(&format!("#[derive(Clone, Copy)]\npub struct H_{0}(pub {0});\nimpl H_{0} {{\n", name));
            continue;
        }
        if skip {
            if line == "}" {
                skip = false;
            }
            continue;
        }
        let l = line.replace("pub const fn ", "pub fn ").replace("    const fn ", "    fn ");
        let t = l.trim_start();
        let mut r = if t.starts_with("pub const ") {
            l.clone()
        } else {
            replace_self(&l)
        };
        if t.starts_with("pub fn ") || t.starts_with("fn ") {
            if let Some(p) = r.find('(') {
                let close = r[p..].find(')').map(|x| x + p).unwrap_or(r.len());
                let sig = r[p..close].replace("self.0", "self");
                r = format!("{}{}{}", &r[..p], sig, &r[close..]);
            }
        }
        r = r.replace("self.0.one_less_than_next_power_of_two()", &format!("H_{}(self.0).one_less_than_next_power_of_two()", cur));
        out.push_str(&r);
        out.push('\n');
    }
    out
}
