//! Writes core/unicode/tables.rs: char property ranges and case mappings, derived by
//! querying this rustc's real std over every code point, so Rapid's std answers exactly
//! as real std does (same Unicode version).

use std::fmt::Write as _;

/// Ranges of code points where `pred` holds. Surrogates (not chars) continue the current
/// state so ranges may span them (they are never queried).
fn ranges(pred: &dyn Fn(char) -> bool) -> Vec<(u32, u32)> {
    let mut out: Vec<(u32, u32)> = Vec::new();
    let mut state = false;
    let mut start = 0u32;
    for cp in 0..=0x10FFFFu32 {
        let v = match char::from_u32(cp) {
            Some(c) => pred(c),
            None => state,
        };
        if v && !state {
            start = cp;
        }
        if !v && state {
            out.push((start, cp - 1));
        }
        state = v;
    }
    if state {
        out.push((start, 0x10FFFF));
    }
    out
}

fn emit_ranges(out: &mut String, name: &str, doc: &str, r: &[(u32, u32)]) {
    writeln!(out, "/// {}", doc).unwrap();
    writeln!(out, "pub(crate) static {}: [(u32, u32); {}] = [", name, r.len()).unwrap();
    for chunk in r.chunks(6) {
        out.push_str("   ");
        for (a, b) in chunk {
            write!(out, " (0x{:x}, 0x{:x}),", a, b).unwrap();
        }
        out.push('\n');
    }
    out.push_str("];\n\n");
}

fn emit_case(out: &mut String, name: &str, lower: bool) {
    let mut single: Vec<(u32, u32)> = Vec::new();
    let mut multi: Vec<(u32, [u32; 3])> = Vec::new();
    for cp in 0..=0x10FFFFu32 {
        let c = match char::from_u32(cp) {
            Some(c) => c,
            None => continue,
        };
        let m: Vec<char> = if lower { c.to_lowercase().collect() } else { c.to_uppercase().collect() };
        if m.len() == 1 {
            if m[0] != c {
                single.push((cp, m[0] as u32));
            }
        } else {
            let mut a = [0u32; 3];
            for (i, x) in m.iter().enumerate() {
                a[i] = *x as u32;
            }
            multi.push((cp, a));
        }
    }
    writeln!(out, "/// to_{}case mappings to a single char (code point -> code point), sorted.", if lower { "lower" } else { "upper" }).unwrap();
    writeln!(out, "pub(crate) static {}_SINGLE: [(u32, u32); {}] = [", name, single.len()).unwrap();
    for chunk in single.chunks(6) {
        out.push_str("   ");
        for (a, b) in chunk {
            write!(out, " (0x{:x}, 0x{:x}),", a, b).unwrap();
        }
        out.push('\n');
    }
    out.push_str("];\n\n");
    writeln!(out, "/// to_{}case mappings to 2-3 chars (0 = unused), sorted.", if lower { "lower" } else { "upper" }).unwrap();
    writeln!(out, "pub(crate) static {}_MULTI: [(u32, [u32; 3]); {}] = [", name, multi.len()).unwrap();
    for chunk in multi.chunks(3) {
        out.push_str("   ");
        for (a, b) in chunk {
            write!(out, " (0x{:x}, [0x{:x}, 0x{:x}, 0x{:x}]),", a, b[0], b[1], b[2]).unwrap();
        }
        out.push('\n');
    }
    out.push_str("];\n\n");
}

fn is_special_escape(c: char) -> bool {
    matches!(c, '\0' | '\t' | '\r' | '\n' | '\\' | '"' | '\'')
}

/// escape_debug of `c` when it is not the first char of a str (grapheme extenders raw).
fn printable(c: char) -> bool {
    if is_special_escape(c) {
        return true;
    }
    let s: String = ['a', c].iter().collect();
    let e = s.escape_debug().to_string();
    e[1..] == c.to_string()
}

fn gext_printable(c: char) -> bool {
    if is_special_escape(c) {
        return false;
    }
    printable(c) && c.escape_debug().to_string() != c.to_string()
}

fn ends_final_sigma(s: String) -> bool {
    s.to_lowercase().ends_with('ς')
}

/// Cased and not Case_Ignorable: "{c}Σ" lowercases to a final sigma.
fn cased_not_ignorable(c: char) -> bool {
    ends_final_sigma(format!("{}Σ", c))
}

/// Case_Ignorable (only the non-cased-ness matters to the final-sigma rule).
fn case_ignorable(c: char) -> bool {
    !cased_not_ignorable(c) && ends_final_sigma(format!("A{}Σ", c))
}

pub fn run(core: &str) {
    let mut out = String::new();
    let (ma, mi, pa) = char::UNICODE_VERSION;
    writeln!(out, "//! Generated by tools/rapid/std-next/check/src/gen_unicode.rs").unwrap();
    writeln!(out, "//! (`cargo run --release --bin rapid-std-gen -- unicode ../core` in std-next/check)").unwrap();
    writeln!(out, "//! from the real std of the rustc that ran it (Unicode {}.{}.{}). Do not edit.\n", ma, mi, pa).unwrap();
    writeln!(out, "pub const UNICODE_VERSION: (u8, u8, u8) = ({}, {}, {});\n", ma, mi, pa).unwrap();
    emit_ranges(&mut out, "ALPHABETIC", "char::is_alphabetic", &ranges(&|c| c.is_alphabetic()));
    emit_ranges(&mut out, "LOWERCASE", "char::is_lowercase", &ranges(&|c| c.is_lowercase()));
    emit_ranges(&mut out, "UPPERCASE", "char::is_uppercase", &ranges(&|c| c.is_uppercase()));
    emit_ranges(&mut out, "WHITE_SPACE", "char::is_whitespace", &ranges(&|c| c.is_whitespace()));
    emit_ranges(&mut out, "NUMERIC", "char::is_numeric", &ranges(&|c| c.is_numeric()));
    emit_ranges(
        &mut out,
        "PRINTABLE",
        "escape_debug leaves the char as is (when not the first char of a str)",
        &ranges(&printable),
    );
    emit_ranges(
        &mut out,
        "GRAPHEME_EXTEND_PRINTABLE",
        "printable, but escaped by escape_debug where grapheme extenders are escaped",
        &ranges(&gext_printable),
    );
    emit_ranges(&mut out, "CASE_IGNORABLE", "Case_Ignorable as the final-sigma rule sees it", &ranges(&case_ignorable));
    emit_ranges(
        &mut out,
        "CASED",
        "Cased and not Case_Ignorable (what the final-sigma rule tests after skipping ignorables)",
        &ranges(&cased_not_ignorable),
    );
    emit_case(&mut out, "TO_LOWER", true);
    emit_case(&mut out, "TO_UPPER", false);
    let path = format!("{}/unicode/tables.rs", core);
    std::fs::write(&path, out).expect("write tables.rs");
    eprintln!("wrote {}", path);
}
