[package]
name = "makepad-example-text-flow"
version = "1.0.0"
authors = ["Makepad <info@makepad.nl>"]
edition = "2021"
description = "Makepad text-flowy example"
license = "MIT OR Apache-2.0"
metadata.makepad-auto-version = "ck5jkSkJBt0HxJjOTzCTOxO_xbM="

[dependencies]
makepad-widgets = { path = "../../widgets", version = "1.0.0" }
