[package]
name = "makepad-app-flow-ui"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
makepad-widgets = { path = "../../widgets" }
makepad-code-editor = { path = "../../code_editor" }
makepad-strict-json = { path = "../../libs/strict_json" }
makepad-flow = { path = "../../libs/flow", features = ["host"] }
makepad-aichat = { path = "../aichat" }
makepad-ai-services = { path = "../../libs/ai/services" }
