//! Generates core/tuple.rs: Clone, Copy, Default, PartialEq, Eq, PartialOrd, Ord and Debug for
//! tuples of 1..=12 elements (Hash is in hash/mod.rs). Lexicographic like real core.

use std::fmt::Write;

pub fn run(core: &str) {
    let mut o = String::new();
    o.push_str("// GENERATED by tools/hotrust/std-next/check/src/gen_tuple.rs (`hotrust-std-gen tuple ../core`).\n");
    o.push_str("// Do not edit by hand: change the generator and re-run it.\n");
    o.push_str("//! Trait impls for tuples (HotRust only).\n\n");
    o.push_str("use crate::cmp::Ordering;\nuse crate::fmt;\n\n");
    let names = ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L"];
    for n in 1..=12usize {
        let ts = &names[..n];
        let tys = ts.join(", ");
        let tup = if n == 1 { format!("({},)", tys) } else { format!("({})", tys) };
        let bound = |b: &str| ts.iter().map(|t| format!("{t}: {b}")).collect::<Vec<_>>().join(", ");
        let idx: Vec<String> = (0..n).map(|i| i.to_string()).collect();
        let _ = writeln!(o, "impl<{}> Clone for {tup} {{ fn clone(&self) -> {tup} {{ ({}{}) }} }}", bound("Clone"), idx.iter().map(|i| format!("self.{i}.clone()")).collect::<Vec<_>>().join(", "), if n == 1 { "," } else { "" });
        let _ = writeln!(o, "impl<{}> Copy for {tup} {{}}", bound("Copy"));
        let _ = writeln!(o, "impl<{}> Default for {tup} {{ fn default() -> {tup} {{ ({}{}) }} }}", bound("Default"), ts.iter().map(|t| format!("{t}::default()")).collect::<Vec<_>>().join(", "), if n == 1 { "," } else { "" });
        let _ = writeln!(o, "impl<{}> PartialEq for {tup} {{ fn eq(&self, other: &{tup}) -> bool {{ {} }} }}", bound("PartialEq"), idx.iter().map(|i| format!("self.{i} == other.{i}")).collect::<Vec<_>>().join(" && "));
        let _ = writeln!(o, "impl<{}> Eq for {tup} {{}}", bound("Eq"));
        // partial_cmp: first non-equal element decides
        let mut pc = String::new();
        for (k, i) in idx.iter().enumerate() {
            if k + 1 == n {
                let _ = write!(pc, "self.{i}.partial_cmp(&other.{i})");
            } else {
                let _ = write!(pc, "match self.{i}.partial_cmp(&other.{i}) {{ Some(Ordering::Equal) => {{}} c => return c }} ");
            }
        }
        let _ = writeln!(o, "impl<{}> PartialOrd for {tup} {{ fn partial_cmp(&self, other: &{tup}) -> Option<Ordering> {{ {pc} }} }}", bound("PartialOrd"));
        let mut c = String::new();
        for (k, i) in idx.iter().enumerate() {
            if k + 1 == n {
                let _ = write!(c, "self.{i}.cmp(&other.{i})");
            } else {
                let _ = write!(c, "match self.{i}.cmp(&other.{i}) {{ Ordering::Equal => {{}} c => return c }} ");
            }
        }
        let _ = writeln!(o, "impl<{}> Ord for {tup} {{ fn cmp(&self, other: &{tup}) -> Ordering {{ {c} }} }}", bound("Ord"));
        let _ = writeln!(
            o,
            "impl<{}> fmt::Debug for {tup} {{ fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {{ let mut b = f.debug_tuple(\"\"); {} b.finish() }} }}",
            bound("fmt::Debug"),
            idx.iter().map(|i| format!("b.field(&self.{i});")).collect::<Vec<_>>().join(" ")
        );
        o.push('\n');
    }
    std::fs::write(format!("{}/tuple.rs", core), o).expect("write tuple.rs");
    eprintln!("gen_tuple: wrote tuple.rs");
}
