[package]
name = "makepad-network"
version = "1.0.0"
edition = "2021"
description = "Networking runtime for Makepad UI and CLI apps"
license = "MIT OR Apache-2.0"

[dependencies]
makepad-error-log = { path = "../../libs/error_log", version = "1.0.0" }
makepad-live-id = { path = "../../libs/live_id", version = "1.0.0" }
makepad-micro-serde = { path = "../../libs/micro_serde", version = "1.0.0" }

[target.'cfg(any(target_os = "macos", target_os = "ios", target_os = "tvos"))'.dependencies]
makepad-apple-sys = { path = "../../libs/apple_sys", version = "1.0.0" }

[target.'cfg(windows)'.dependencies.windows]
package = "makepad-windows-sys"
path = "../../libs/windows/sys"
version = "0.1.0"
