[package]
name = "makepad-canvas"
version = "0.1.0"
edition = "2024"

[dependencies]
makepad-widgets = { path = "../../widgets" }
makepad-code-editor = { path = "../../code_editor" }
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = { version = "0.24", default-features = false, features = ["handshake"] }
futures-util = "0.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
uuid = { version = "1", features = ["v4"] }
symphonia = { version = "0.5", features = ["mp3", "isomp4", "aac"] }
rustfft = "6.2"
