[package]
name = "makepad-example-render-to-texture"
version = "1.0.0"
edition = "2021"

[dependencies]
makepad-widgets = { path = "../../widgets", version = "2.0.0" }

[dev-dependencies]
makepad-test = { path = "../../libs/makepad_test", version = "0.1.0" }
makepad-zune-png = { path = "../../libs/zune/zune-png", version = "0.5.2" }
