[application]
name = "makepad-example-text-input"

[bundle]
identifier = "com.example.MakepadExampleTextInput"
version = "1.0.0"

[permissions]
camera = { description = "This app needs access to the camera for video capture functionality." }
microphone = { description = "This app needs access to the microphone for audio recording functionality." }

[ios]
deployment_target = "15.0"

