#!/system/bin/sh
# GENERATED by `cargo makepad android dyn-pack` — shipped as lib/arm64-v8a/libmk-host-ld.so.
# Link driver for host (musl) proc-macro dylibs. rustc passes `-flavor gnu`
# because this file's name ends in `-ld`. llvm-lld only honors that if argv0
# is `ld.lld` / `rust-lld`; exec via libld-musl.so otherwise looks like a
# generic `lld` and errors: unknown argument '-flavor'.
D="$MAKEPAD_DYN_DIR"
N="$MAKEPAD_DYN_NLIB"
LLD="$D/tc/lib/rustlib/@RUST_HOST@/bin/rust-lld"
exec "$N/libld-musl.so" --argv0 ld.lld "$LLD" "$@"
