#!/system/bin/sh
# GENERATED by `cargo makepad android dyn-pack` — shipped as lib/arm64-v8a/librustc-wrap.so.
# The on-device rustc: the musl-host rustc started through its own loader
# (execve of files/ is denied on Android 10+, mmap-exec is not; the loader
# and this script live in nativeLibraryDir). `-vV` answers with the Mac's
# text so cargo's fingerprints (hash of the full -vV output) match the
# target/ tree the APK ships; the linker cargo names (the Mac NDK clang, a
# string cargo hashes too) is rewritten to the device link driver.
D="$MAKEPAD_DYN_DIR"
N="$MAKEPAD_DYN_NLIB"
if [ "$#" = 1 ] && [ "$1" = "-vV" ]; then
  cat <<'VV'
@VV@
VV
  exit 0
fi
host=1
n=$#
i=0
while [ "$i" -lt "$n" ]; do
  a=$1
  shift
  case "$a" in
    --target|--target=*) host=0 ;;
    linker=*) a="linker=$N/libmk-ld.so" ;;
  esac
  set -- "$@" "$a"
  i=$((i + 1))
done
if [ "$host" = 1 ]; then
  # Host units (the proc-macro bootstrap): no linker from cargo, so the
  # musl self-contained link through rust-lld, rpath to the toolchain's
  # libgcc_s for the dylib rustc dlopens.
  set -- "$@" -C "linker=$N/libmk-host-ld.so" -C linker-flavor=ld.lld -C link-self-contained=yes -C "link-arg=-rpath=$D/tc/lib"
fi
# The Mac cross-build remapped its directories the same way (cargo-makepad's
# rustc wrapper, `makepad-dyn-rustc`): a crate rebuilt here gets the SVH the
# engine recorded.
case " $* " in
  *" --print"*|*" --print="*) exec "$N/libld-musl.so" "$D/tc/bin/rustc" --sysroot "$D/tc" "$@" ;;
esac
exec "$N/libld-musl.so" "$D/tc/bin/rustc" --sysroot "$D/tc" "$@" \
  --remap-path-prefix="$PWD=/wmdyn" --remap-path-prefix="$CARGO_TARGET_DIR=/wmdyn-target"
