// GENERATED by tools/rapid/std-next/check/src/gen_num.rs (`rapid-std-gen num ../core`).
// Do not edit by hand: change the generator and re-run it.
//! Inherent methods and constants of f32/f64 (Rapid only).

use crate::intrinsics;
use crate::libm;
use crate::num::FpCategory;
use crate::cmp::Ordering;

#[cfg(not(rapid_check))]
impl f64 {
    pub const RADIX: u32 = 2;
    pub const MANTISSA_DIGITS: u32 = 53;
    pub const DIGITS: u32 = 15;
    pub const EPSILON: f64 = 2.2204460492503131e-16_f64;
    pub const MIN: f64 = -1.7976931348623157e+308_f64;
    pub const MIN_POSITIVE: f64 = 2.2250738585072014e-308_f64;
    pub const MAX: f64 = 1.7976931348623157e+308_f64;
    pub const MIN_EXP: i32 = -1021;
    pub const MAX_EXP: i32 = 1024;
    pub const MIN_10_EXP: i32 = -307;
    pub const MAX_10_EXP: i32 = 308;
    pub const NAN: f64 = f64::from_bits(0x7ff8_0000_0000_0000);
    pub const INFINITY: f64 = f64::from_bits(0x7ff0_0000_0000_0000);
    pub const NEG_INFINITY: f64 = f64::from_bits(0xfff0_0000_0000_0000);
    pub const fn to_bits(self) -> u64 { unsafe { intrinsics::to_bits_f64(self) } }
    pub const fn from_bits(v: u64) -> f64 { unsafe { intrinsics::from_bits_f64(v) } }
    pub const fn is_nan(self) -> bool { self != self }
    pub const fn is_infinite(self) -> bool { (self.to_bits() & !0x8000_0000_0000_0000) == 0x7ff0_0000_0000_0000 }
    pub const fn is_finite(self) -> bool { (self.to_bits() & 0x7ff0_0000_0000_0000) != 0x7ff0_0000_0000_0000 }
    pub const fn is_subnormal(self) -> bool { matches!(self.classify(), FpCategory::Subnormal) }
    pub const fn is_normal(self) -> bool { matches!(self.classify(), FpCategory::Normal) }
    pub const fn classify(self) -> FpCategory { let b = self.to_bits(); match (b & 0x000f_ffff_ffff_ffff, b & 0x7ff0_0000_0000_0000) { (0, 0x7ff0_0000_0000_0000) => FpCategory::Infinite, (_, 0x7ff0_0000_0000_0000) => FpCategory::Nan, (0, 0) => FpCategory::Zero, (_, 0) => FpCategory::Subnormal, _ => FpCategory::Normal } }
    pub const fn is_sign_positive(self) -> bool { !self.is_sign_negative() }
    pub const fn is_sign_negative(self) -> bool { (self.to_bits() & 0x8000_0000_0000_0000) != 0 }
    pub const fn abs(self) -> f64 { unsafe { intrinsics::fabs_f64(self) } }
    pub const fn copysign(self, sign: f64) -> f64 { f64::from_bits((self.to_bits() & !0x8000_0000_0000_0000) | (sign.to_bits() & 0x8000_0000_0000_0000)) }
    pub const fn signum(self) -> f64 { if self.is_nan() { f64::NAN } else { (1.0 as f64).copysign(self) } }
    pub fn sqrt(self) -> f64 { unsafe { intrinsics::sqrt_f64(self) } }
    pub fn floor(self) -> f64 { unsafe { intrinsics::floor_f64(self) } }
    pub fn ceil(self) -> f64 { unsafe { intrinsics::ceil_f64(self) } }
    pub fn trunc(self) -> f64 { unsafe { intrinsics::trunc_f64(self) } }
    pub fn round_ties_even(self) -> f64 { unsafe { intrinsics::rint_f64(self) } }
    pub fn round(self) -> f64 { unsafe { libm::round(self) } }
    pub fn fract(self) -> f64 { self - self.trunc() }
    pub fn min(self, other: f64) -> f64 { unsafe { intrinsics::fmin_f64(self, other) } }
    pub fn max(self, other: f64) -> f64 { unsafe { intrinsics::fmax_f64(self, other) } }
    pub fn minimum(self, other: f64) -> f64 { if self < other { self } else if other < self { other } else if self == other { if self.is_sign_negative() && other.is_sign_positive() { self } else { other } } else { self + other } }
    pub fn maximum(self, other: f64) -> f64 { if self > other { self } else if other > self { other } else if self == other { if self.is_sign_positive() && other.is_sign_negative() { self } else { other } } else { self + other } }
    #[track_caller]
    pub fn clamp(self, min: f64, max: f64) -> f64 { if !(min <= max) { crate::panicking::panic_fmt(format_args!("min > max, or either was NaN. min = {min:?}, max = {max:?}")); } let mut x = self; if x < min { x = min; } if x > max { x = max; } x }
    pub fn mul_add(self, a: f64, b: f64) -> f64 { unsafe { libm::fma(self, a, b) } }
    pub fn div_euclid(self, rhs: f64) -> f64 { let q = (self / rhs).trunc(); if self % rhs < 0.0 { return if rhs > 0.0 { q - 1.0 } else { q + 1.0 }; } q }
    pub fn rem_euclid(self, rhs: f64) -> f64 { let r = self % rhs; if r < 0.0 { r + rhs.abs() } else { r } }
    pub fn powi(self, n: i32) -> f64 { let recip = n < 0; let mut b = n; let mut a = self; let mut r: f64 = 1.0; loop { if (b & 1) != 0 { r *= a; } b /= 2; if b == 0 { break; } a *= a; } if recip { 1.0 / r } else { r } }
    pub fn powf(self, n: f64) -> f64 { unsafe { libm::pow(self, n) } }
    pub fn exp(self) -> f64 { unsafe { libm::exp(self) } }
    pub fn exp2(self) -> f64 { unsafe { libm::exp2(self) } }
    pub fn exp_m1(self) -> f64 { unsafe { libm::expm1(self) } }
    pub fn ln(self) -> f64 { unsafe { libm::log(self) } }
    pub fn log2(self) -> f64 { unsafe { libm::log2(self) } }
    pub fn log10(self) -> f64 { unsafe { libm::log10(self) } }
    pub fn ln_1p(self) -> f64 { unsafe { libm::log1p(self) } }
    pub fn cbrt(self) -> f64 { unsafe { libm::cbrt(self) } }
    pub fn sin(self) -> f64 { unsafe { libm::sin(self) } }
    pub fn cos(self) -> f64 { unsafe { libm::cos(self) } }
    pub fn tan(self) -> f64 { unsafe { libm::tan(self) } }
    pub fn asin(self) -> f64 { unsafe { libm::asin(self) } }
    pub fn acos(self) -> f64 { unsafe { libm::acos(self) } }
    pub fn atan(self) -> f64 { unsafe { libm::atan(self) } }
    pub fn sinh(self) -> f64 { unsafe { libm::sinh(self) } }
    pub fn cosh(self) -> f64 { unsafe { libm::cosh(self) } }
    pub fn tanh(self) -> f64 { unsafe { libm::tanh(self) } }
    pub fn atan2(self, other: f64) -> f64 { unsafe { libm::atan2(self, other) } }
    pub fn hypot(self, other: f64) -> f64 { unsafe { libm::hypot(self, other) } }
    pub fn log(self, base: f64) -> f64 { self.ln() / base.ln() }
    pub fn sin_cos(self) -> (f64, f64) { (self.sin(), self.cos()) }
    pub fn asinh(self) -> f64 { let ax = self.abs(); let ix = 1.0 / ax; (ax + (ax / ((1.0 as f64).hypot(ix) + ix))).ln_1p().copysign(self) }
    pub fn acosh(self) -> f64 { if self < 1.0 { f64::NAN } else { (self + ((self - 1.0).sqrt() * (self + 1.0).sqrt())).ln() } }
    pub fn atanh(self) -> f64 { 0.5 * ((2.0 * self) / (1.0 - self)).ln_1p() }
    pub fn to_degrees(self) -> f64 { self * (180.0f64 / crate::f64::consts::PI) }
    pub fn to_radians(self) -> f64 { self * (crate::f64::consts::PI / 180.0) }
    pub fn recip(self) -> f64 { 1.0 / self }
    pub fn total_cmp(&self, other: &f64) -> Ordering { let mut l = self.to_bits() as i64; let mut r = other.to_bits() as i64; l ^= (((l >> 63) as u64) >> 1) as i64; r ^= (((r >> 63) as u64) >> 1) as i64; l.cmp(&r) }
    pub fn to_le_bytes(self) -> [u8; 8] { self.to_bits().to_le_bytes() }
    pub fn to_be_bytes(self) -> [u8; 8] { self.to_bits().to_be_bytes() }
    pub fn to_ne_bytes(self) -> [u8; 8] { self.to_bits().to_ne_bytes() }
    pub fn from_le_bytes(b: [u8; 8]) -> f64 { f64::from_bits(u64::from_le_bytes(b)) }
    pub fn from_be_bytes(b: [u8; 8]) -> f64 { f64::from_bits(u64::from_be_bytes(b)) }
    pub fn from_ne_bytes(b: [u8; 8]) -> f64 { f64::from_bits(u64::from_ne_bytes(b)) }
    pub fn midpoint(self, other: f64) -> f64 { ((self as f64 + other as f64) / 2.0) as f64 }
}

#[cfg(not(rapid_check))]
impl f32 {
    pub const RADIX: u32 = 2;
    pub const MANTISSA_DIGITS: u32 = 24;
    pub const DIGITS: u32 = 6;
    pub const EPSILON: f32 = 1.19209290e-07_f32;
    pub const MIN: f32 = -3.40282347e+38_f32;
    pub const MIN_POSITIVE: f32 = 1.17549435e-38_f32;
    pub const MAX: f32 = 3.40282347e+38_f32;
    pub const MIN_EXP: i32 = -125;
    pub const MAX_EXP: i32 = 128;
    pub const MIN_10_EXP: i32 = -37;
    pub const MAX_10_EXP: i32 = 38;
    pub const NAN: f32 = f32::from_bits(0x7fc0_0000);
    pub const INFINITY: f32 = f32::from_bits(0x7f80_0000);
    pub const NEG_INFINITY: f32 = f32::from_bits(0xff80_0000);
    pub const fn to_bits(self) -> u32 { unsafe { intrinsics::to_bits_f32(self) } }
    pub const fn from_bits(v: u32) -> f32 { unsafe { intrinsics::from_bits_f32(v) } }
    pub const fn is_nan(self) -> bool { self != self }
    pub const fn is_infinite(self) -> bool { (self.to_bits() & !0x8000_0000) == 0x7f80_0000 }
    pub const fn is_finite(self) -> bool { (self.to_bits() & 0x7f80_0000) != 0x7f80_0000 }
    pub const fn is_subnormal(self) -> bool { matches!(self.classify(), FpCategory::Subnormal) }
    pub const fn is_normal(self) -> bool { matches!(self.classify(), FpCategory::Normal) }
    pub const fn classify(self) -> FpCategory { let b = self.to_bits(); match (b & 0x007f_ffff, b & 0x7f80_0000) { (0, 0x7f80_0000) => FpCategory::Infinite, (_, 0x7f80_0000) => FpCategory::Nan, (0, 0) => FpCategory::Zero, (_, 0) => FpCategory::Subnormal, _ => FpCategory::Normal } }
    pub const fn is_sign_positive(self) -> bool { !self.is_sign_negative() }
    pub const fn is_sign_negative(self) -> bool { (self.to_bits() & 0x8000_0000) != 0 }
    pub const fn abs(self) -> f32 { unsafe { intrinsics::fabs_f32(self) } }
    pub const fn copysign(self, sign: f32) -> f32 { f32::from_bits((self.to_bits() & !0x8000_0000) | (sign.to_bits() & 0x8000_0000)) }
    pub const fn signum(self) -> f32 { if self.is_nan() { f32::NAN } else { (1.0 as f32).copysign(self) } }
    pub fn sqrt(self) -> f32 { unsafe { intrinsics::sqrt_f32(self) } }
    pub fn floor(self) -> f32 { unsafe { intrinsics::floor_f32(self) } }
    pub fn ceil(self) -> f32 { unsafe { intrinsics::ceil_f32(self) } }
    pub fn trunc(self) -> f32 { unsafe { intrinsics::trunc_f32(self) } }
    pub fn round_ties_even(self) -> f32 { unsafe { intrinsics::rint_f32(self) } }
    pub fn round(self) -> f32 { unsafe { libm::roundf(self) } }
    pub fn fract(self) -> f32 { self - self.trunc() }
    pub fn min(self, other: f32) -> f32 { unsafe { intrinsics::fmin_f32(self, other) } }
    pub fn max(self, other: f32) -> f32 { unsafe { intrinsics::fmax_f32(self, other) } }
    pub fn minimum(self, other: f32) -> f32 { if self < other { self } else if other < self { other } else if self == other { if self.is_sign_negative() && other.is_sign_positive() { self } else { other } } else { self + other } }
    pub fn maximum(self, other: f32) -> f32 { if self > other { self } else if other > self { other } else if self == other { if self.is_sign_positive() && other.is_sign_negative() { self } else { other } } else { self + other } }
    #[track_caller]
    pub fn clamp(self, min: f32, max: f32) -> f32 { if !(min <= max) { crate::panicking::panic_fmt(format_args!("min > max, or either was NaN. min = {min:?}, max = {max:?}")); } let mut x = self; if x < min { x = min; } if x > max { x = max; } x }
    pub fn mul_add(self, a: f32, b: f32) -> f32 { unsafe { libm::fmaf(self, a, b) } }
    pub fn div_euclid(self, rhs: f32) -> f32 { let q = (self / rhs).trunc(); if self % rhs < 0.0 { return if rhs > 0.0 { q - 1.0 } else { q + 1.0 }; } q }
    pub fn rem_euclid(self, rhs: f32) -> f32 { let r = self % rhs; if r < 0.0 { r + rhs.abs() } else { r } }
    pub fn powi(self, n: i32) -> f32 { let recip = n < 0; let mut b = n; let mut a = self; let mut r: f32 = 1.0; loop { if (b & 1) != 0 { r *= a; } b /= 2; if b == 0 { break; } a *= a; } if recip { 1.0 / r } else { r } }
    pub fn powf(self, n: f32) -> f32 { unsafe { libm::powf(self, n) } }
    pub fn exp(self) -> f32 { unsafe { libm::expf(self) } }
    pub fn exp2(self) -> f32 { unsafe { libm::exp2f(self) } }
    pub fn exp_m1(self) -> f32 { unsafe { libm::expm1f(self) } }
    pub fn ln(self) -> f32 { unsafe { libm::logf(self) } }
    pub fn log2(self) -> f32 { unsafe { libm::log2f(self) } }
    pub fn log10(self) -> f32 { unsafe { libm::log10f(self) } }
    pub fn ln_1p(self) -> f32 { unsafe { libm::log1pf(self) } }
    pub fn cbrt(self) -> f32 { unsafe { libm::cbrtf(self) } }
    pub fn sin(self) -> f32 { unsafe { libm::sinf(self) } }
    pub fn cos(self) -> f32 { unsafe { libm::cosf(self) } }
    pub fn tan(self) -> f32 { unsafe { libm::tanf(self) } }
    pub fn asin(self) -> f32 { unsafe { libm::asinf(self) } }
    pub fn acos(self) -> f32 { unsafe { libm::acosf(self) } }
    pub fn atan(self) -> f32 { unsafe { libm::atanf(self) } }
    pub fn sinh(self) -> f32 { unsafe { libm::sinhf(self) } }
    pub fn cosh(self) -> f32 { unsafe { libm::coshf(self) } }
    pub fn tanh(self) -> f32 { unsafe { libm::tanhf(self) } }
    pub fn atan2(self, other: f32) -> f32 { unsafe { libm::atan2f(self, other) } }
    pub fn hypot(self, other: f32) -> f32 { unsafe { libm::hypotf(self, other) } }
    pub fn log(self, base: f32) -> f32 { self.ln() / base.ln() }
    pub fn sin_cos(self) -> (f32, f32) { (self.sin(), self.cos()) }
    pub fn asinh(self) -> f32 { let ax = self.abs(); let ix = 1.0 / ax; (ax + (ax / ((1.0 as f32).hypot(ix) + ix))).ln_1p().copysign(self) }
    pub fn acosh(self) -> f32 { if self < 1.0 { f32::NAN } else { (self + ((self - 1.0).sqrt() * (self + 1.0).sqrt())).ln() } }
    pub fn atanh(self) -> f32 { 0.5 * ((2.0 * self) / (1.0 - self)).ln_1p() }
    pub fn to_degrees(self) -> f32 { const PIS_IN_180: f32 = 57.2957795130823208767981548141051703_f32; self * PIS_IN_180 }
    pub fn to_radians(self) -> f32 { self * (crate::f32::consts::PI / 180.0f32) }
    pub fn recip(self) -> f32 { 1.0 / self }
    pub fn total_cmp(&self, other: &f32) -> Ordering { let mut l = self.to_bits() as i32; let mut r = other.to_bits() as i32; l ^= (((l >> 31) as u32) >> 1) as i32; r ^= (((r >> 31) as u32) >> 1) as i32; l.cmp(&r) }
    pub fn to_le_bytes(self) -> [u8; 4] { self.to_bits().to_le_bytes() }
    pub fn to_be_bytes(self) -> [u8; 4] { self.to_bits().to_be_bytes() }
    pub fn to_ne_bytes(self) -> [u8; 4] { self.to_bits().to_ne_bytes() }
    pub fn from_le_bytes(b: [u8; 4]) -> f32 { f32::from_bits(u32::from_le_bytes(b)) }
    pub fn from_be_bytes(b: [u8; 4]) -> f32 { f32::from_bits(u32::from_be_bytes(b)) }
    pub fn from_ne_bytes(b: [u8; 4]) -> f32 { f32::from_bits(u32::from_ne_bytes(b)) }
    pub fn midpoint(self, other: f32) -> f32 { ((self as f64 + other as f64) / 2.0) as f32 }
}

