//! Every extended authoring resource is inspected through bounded flat rows.
use crate::{*,json::{self,Value},schema::{transform_value,vec_value}};
pub const EXTENDED_INSPECTION_DOMAINS:&[&str]=&["scene_nodes","modifiers","modifier_values","lights","sockets","vehicle_wheels","colliders","lods","surface_materials","surface_layers","surface_pixels","vertex_colors","rig_rests","poses","pose_joints","constraints","morphs","morph_deltas","clip_options","clip_events","clip_event_payload","morph_keys","weight_locks","uv_islands","uv_island_faces","uv_pins","solid","selections","selection_vertices","selection_faces"];
fn n(v:usize)->Value{Value::Int(v as i64)}
fn id(v:u64)->Value{json::s(v.to_string())}
fn obj(v:Vec<(&str,Value)>)->Value{json::obj(v)}
struct Page{offset:usize,limit:usize,total:usize,rows:Vec<Value>}
impl Page{
    fn section(&mut self,count:usize,ctx:&mut mesh::Context<'_>,mut value:impl FnMut(usize)->Result<Value>)->Result<()>{ctx.checkpoint(1)?;let start=self.offset.saturating_sub(self.total).min(count);let available=self.limit.saturating_sub(self.rows.len());for i in start..count.min(start.saturating_add(available)){ctx.checkpoint(1)?;self.rows.push(value(i)?);}self.total=self.total.saturating_add(count);Ok(())}
    fn one(&mut self,ctx:&mut mesh::Context<'_>,value:impl FnOnce()->Value)->Result<()>{let mut value=Some(value);self.section(1,ctx,|_|Ok(value.take().unwrap()()))}
}
fn flatten(value:&Value,path:&str,base:&[(&str,Value)],page:&mut Page,ctx:&mut mesh::Context<'_>)->Result<()>{ctx.checkpoint(1)?;match value{
    Value::Arr(items)if !items.is_empty()=>for(i,v)in items.iter().enumerate(){flatten(v,&format!("{path}/{i}"),base,page,ctx)?;},
    Value::Obj(items)if !items.is_empty()=>for(k,v)in items{flatten(v,&format!("{path}/{}",k.replace('~',"~0").replace('/',"~1")),base,page,ctx)?;},
    _=>page.one(ctx,||{let mut fields=base.to_vec();fields.push(("path",json::s(path)));fields.push(("value",value.clone()));obj(fields)})?,
}Ok(())}
fn summary(value:&Value)->Value{match value{Value::Arr(v)=>obj(vec![("count",n(v.len())),("values_domain",json::s("modifier_values"))]),Value::Obj(v)=>Value::Obj(v.iter().map(|(k,v)|(k.clone(),summary(v))).collect()),_=>value.clone()}}
fn surface_factors(id:u32,m:&SurfaceMaterial)->Value{obj(vec![("material",n(id as usize)),("base_color",vec_value(&m.base_color)),("metallic",Value::F64(m.metallic)),("roughness",Value::F64(m.roughness)),("normal_scale",Value::F64(m.normal_scale)),("occlusion_strength",Value::F64(m.occlusion_strength)),("emissive",vec_value(&m.emissive)),("emissive_strength",Value::F64(m.emissive_strength)),("alpha",json::s(match m.alpha{SurfaceAlpha::Opaque=>"opaque",SurfaceAlpha::Mask=>"mask",SurfaceAlpha::Blend=>"blend"})),("alpha_cutoff",Value::F64(m.alpha_cutoff)),("double_sided",Value::Bool(m.double_sided)),("layers",n(m.channels.values().map(Vec::len).sum()))])}
pub(super) fn inspect(doc:&Document,object:Option<&str>,domain:&str,offset:usize,limit:usize,ctx:&mut mesh::Context<'_>)->Result<Option<(usize,Vec<Value>)>>{
    if !EXTENDED_INSPECTION_DOMAINS.contains(&domain){return Ok(None)}
    let mut page=Page{offset,limit,total:0,rows:Vec::new()};let scene=doc.scene();let rig=doc.rig();let surface=doc.surface();
    match domain{
        "selections"|"selection_vertices"|"selection_faces"=>for g in doc.selections().groups.values(){if object.is_some_and(|o|o!=g.object){continue}let base=vec![("object",json::s(&g.object)),("name",json::s(&g.name)),("stale",Value::Bool(g.stale))];if domain=="selections"{page.one(ctx,||{let mut f=base.clone();f.extend([("vertices",n(g.vertices.len())),("faces",n(g.faces.len()))]);obj(f)})?;}else if domain=="selection_vertices"{page.section(g.vertices.len(),ctx,|i|{let mut f=base.clone();f.push(("vertex",id(g.vertices[i].0)));Ok(obj(f))})?;}else{page.section(g.faces.len(),ctx,|i|{let mut f=base.clone();f.push(("face",id(g.faces[i].0)));Ok(obj(f))})?;}},
        "scene_nodes"=>for(name,_)in doc.objects().filter(|(name,_)|object.is_none_or(|o|o==*name)){let node=scene.nodes.get(name).cloned().unwrap_or_default();page.one(ctx,||obj(vec![("object",json::s(name)),("parent",node.parent.as_ref().map(json::s).unwrap_or(Value::Null)),("linked_to",node.linked_to.as_ref().map(json::s).unwrap_or(Value::Null)),("transform",transform_value(&node.transform))]))?;},
        "modifiers"|"modifier_values"=>for(name,stack)in &scene.modifiers{if object.is_some_and(|o|o!=name){continue}for(index,m)in stack.iter().enumerate(){ctx.checkpoint(1)?;let value=m.operation.value();let base=[("object",json::s(name)),("modifier",json::s(&m.name)),("index",n(index))];if domain=="modifier_values"{flatten(&value,"",&base,&mut page,ctx)?;}else{page.one(ctx,||{let mut fields=base.to_vec();fields.push(("enabled",Value::Bool(m.enabled)));fields.push(("operation",summary(&value)));obj(fields)})?;}}},
        "lights"=>for light in scene.emitters.values(){page.one(ctx,||SceneOperation::Light(light.clone()).value())?;},
        "sockets"=>for socket in scene.sockets.values(){page.one(ctx,||SceneOperation::Socket(socket.clone()).value())?;},
        "vehicle_wheels"=>for(name,wheel)in &scene.wheels{if object.is_none_or(|o|o==name){page.one(ctx,||SceneOperation::VehicleWheel{object:name.clone(),wheel:wheel.clone()}.value())?;}},
        "colliders"=>for(name,proxy)in &scene.colliders{page.one(ctx,||SceneOperation::Collider{object:name.clone(),proxy:proxy.clone()}.value())?;},
        "lods"=>for(name,levels)in &scene.lods{page.section(levels.len(),ctx,|i|{let l=&levels[i];Ok(obj(vec![("object",json::s(name)),("level",n(i)),("target_faces",n(l.target_faces)),("max_error",Value::F64(l.max_error)),("distance",Value::F64(l.distance))]))})?;},
        "surface_materials"=>for(&id,m)in &surface.materials{page.one(ctx,||surface_factors(id,m))?;},
        "surface_layers"|"surface_pixels"=>for(&id,m)in &surface.materials{for(&channel,layers)in &m.channels{for(index,layer)in layers.iter().enumerate(){let base=vec![("material",n(id as usize)),("channel",json::s(channel.name())),("layer",json::s(&layer.id)),("index",n(index))];if domain=="surface_layers"{page.one(ctx,||{let mut fields=base.clone();fields.extend([("width",n(layer.image.width as usize)),("height",n(layer.image.height as usize)),("opacity",Value::F64(layer.opacity)),("visible",Value::Bool(layer.visible)),("blend",json::s(match layer.blend{SurfaceBlend::Over=>"over",SurfaceBlend::Multiply=>"multiply",SurfaceBlend::Add=>"add",SurfaceBlend::Subtract=>"subtract"})),("has_mask",Value::Bool(layer.mask.is_some())),("mip_levels",n(layer.mips.len())),("pattern",layer.pattern.as_ref().map(|p|obj(vec![("kind",json::s(p.kind.name())),("color_a",vec_value(&p.color_a)),("color_b",vec_value(&p.color_b)),("scale",vec_value(&p.scale)),("seed",id_value(p.seed))])).unwrap_or(Value::Null))]);obj(fields)})?;}else{for(level,image)in std::iter::once(&layer.image).chain(&layer.mips).enumerate(){page.section(image.pixels.len()/4,ctx,|i|{let mut fields=base.clone();fields.extend([("level",n(level)),("x",n(i%image.width as usize)),("y",n(i/image.width as usize)),("rgba",Value::Arr(image.pixels[i*4..i*4+4].iter().map(|v|n(*v as usize)).collect())),("mask",if level==0{layer.mask.as_ref().map(|m|n(m[i] as usize)).unwrap_or(Value::Null)}else{Value::Null})]);Ok(obj(fields))})?;}}}}},
        "vertex_colors"=>for((name,vertex),color)in &surface.vertex_colors{if object.is_none_or(|o|o==name){page.one(ctx,||obj(vec![("object",json::s(name)),("vertex",id(vertex.0)),("color",vec_value(color))]))?;}},
        "rig_rests"=>if let Some(s)=doc.skeleton(){page.section(s.joints.len(),ctx,|i|Ok(obj(vec![("joint",n(i)),("transform",transform_value(&rig.local_rest(s,i)?)),("override",Value::Bool(rig.rests.contains_key(&(i as u32))))])))?;},
        "poses"=>for pose in rig.poses.values(){page.one(ctx,||obj(vec![("name",json::s(&pose.name)),("joints",n(pose.joints.len()))]))?;},
        "pose_joints"=>for pose in rig.poses.values(){for(joint,t)in &pose.joints{page.one(ctx,||obj(vec![("pose",json::s(&pose.name)),("joint",n(*joint as usize)),("transform",transform_value(t))]))?;}},
        "constraints"=>for c in rig.constraints.values(){page.one(ctx,||RigOperation::Constraint(c.clone()).value())?;},
        "morphs"=>for m in rig.morphs.values(){page.one(ctx,||obj(vec![("name",json::s(&m.name)),("object",json::s(&m.object)),("topology",json::s(m.topology.iter().map(|b|format!("{b:02x}")).collect::<String>())),("deltas",n(m.deltas.len())),("weight",Value::F64(m.weight))]))?;},
        "morph_deltas"=>for m in rig.morphs.values(){for(vertex,delta)in &m.deltas{page.one(ctx,||obj(vec![("morph",json::s(&m.name)),("object",json::s(&m.object)),("vertex",id(vertex.0)),("delta",vec_value(delta))]))?;}},
        "clip_options"=>for(name,o)in &rig.clip_options{page.one(ctx,||obj(vec![("clip",json::s(name)),("interpolation",json::s(match o.interpolation{Interpolation::Linear=>"linear",Interpolation::Step=>"step",Interpolation::Cubic=>"cubic"})),("root_motion",Value::Bool(o.root_motion)),("events",n(o.events.len())),("morph_targets",n(o.morph_keys.len())),("morph_key_count",n(o.morph_keys.values().map(Vec::len).sum()))]))?;},
        "clip_events"=>for(name,o)in &rig.clip_options{page.section(o.events.len(),ctx,|i|{let e=&o.events[i];let end=prefix_end(&e.payload,512);Ok(obj(vec![("clip",json::s(name)),("index",n(i)),("time",Value::F64(e.time)),("name",json::s(&e.name)),("payload",json::s(&e.payload[..end])),("payload_bytes",n(e.payload.len())),("payload_omitted",n(e.payload.len()-end))]))})?;},
        "clip_event_payload"=>for(name,o)in &rig.clip_options{for(event,e)in o.events.iter().enumerate(){let mut offset=0;while offset<e.payload.len(){let count=prefix_end(&e.payload[offset..],512);page.one(ctx,||obj(vec![("clip",json::s(name)),("event",n(event)),("byte_offset",n(offset)),("bytes",n(count)),("text",json::s(&e.payload[offset..offset+count]))]))?;offset+=count;}}},
        "morph_keys"=>for(name,o)in &rig.clip_options{for(morph,keys)in &o.morph_keys{page.section(keys.len(),ctx,|i|{let k=&keys[i];Ok(obj(vec![("clip",json::s(name)),("morph",json::s(morph)),("index",n(i)),("time",Value::F64(k.time)),("weight",Value::F64(k.weight))]))})?;}},
        "weight_locks"=>for(name,joints)in &rig.locked_groups{for j in joints{page.one(ctx,||obj(vec![("object",json::s(name)),("joint",n(*j as usize))]))?;}},
        "uv_islands"|"uv_island_faces"|"uv_pins"=>{let object=object.ok_or(Error::Invalid("UV inspection requires object"))?;let mesh=doc.object(object).ok_or_else(||Error::MissingObject(object.into()))?;if domain=="uv_pins"{for corner in mesh.uv_pins(){page.one(ctx,||obj(vec![("corner",id(corner.0))]))?;}}else{let faces=mesh.faces().iter().map(|f|f.id).collect::<Vec<_>>();let islands=mesh.uv_islands(&faces,ctx)?;for(index,island)in islands.iter().enumerate(){if domain=="uv_islands"{page.one(ctx,||obj(vec![("island",n(index)),("faces",n(island.faces.len())),("corners",n(island.corners.len())),("bounds",Value::Arr(island.bounds.iter().map(|v|vec_value(v)).collect())),("area",Value::F64(island.area)),("pinned",n(island.pinned))]))?;}else{page.section(island.faces.len(),ctx,|i|Ok(obj(vec![("island",n(index)),("face",id(island.faces[i].0))])))?;}}}},
        "solid"=>{let object=object.ok_or(Error::Invalid("solid inspection requires object"))?;let mesh=doc.object(object).ok_or_else(||Error::MissingObject(object.into()))?;let report=mesh.validate_global(ctx)?;page.one(ctx,||obj(vec![("is_valid_solid",Value::Bool(report.is_valid_solid)),("is_embedded_surface",Value::Bool(report.is_embedded_surface)),("components",n(report.components)),("orientation_errors",n(report.orientation_errors)),("candidate_pairs",n(report.candidate_pairs)),("tested_pairs",n(report.tested_pairs)),("intersection_count",n(report.intersection_count)),("intersections_omitted",n(report.intersections_omitted)),("intersections",Value::Arr(report.intersections.iter().map(|p|obj(vec![("a",id(p.a.0)),("b",id(p.b.0))])).collect()))]))?;},
        _=>unreachable!(),
    }Ok(Some((page.total,page.rows)))
}
fn id_value(v:u64)->Value{id(v)}

fn prefix_end(s:&str,max:usize)->usize{let mut end=s.len().min(max);while !s.is_char_boundary(end){end-=1;}end}
