[package]
name = "makepad-example-todo"
version = "0.9.0"
authors = ["Makepad <info@makepad.nl>"]
edition = "2021"
description = "Makepad todo example"
license = "MIT OR Apache-2.0"
metadata.makepad-auto-version = "9KF4i37MnpGn83Ib1ahWOBOhBNs="

[dependencies]
makepad-widgets = { path = "../../widgets", version = "0.9.0" }

