[package]
name = "makepad-example-ui-zoo"
version = "1.0.0"
authors = ["Makepad <info@makepad.nl>"]
edition = "2021"
description = "Makepad ui-zoo example"
license = "MIT OR Apache-2.0"
metadata.makepad-auto-version = "p0KeHFesbgoS18r2_nhKxi7ZF50="

[dependencies]
makepad-widgets = { path = "../../widgets", version = "1.0.0" }
