//! The hand-curated alias table — the heart of the asset library.
//!
//! A model nobody can name is a model that does not exist. Filename tokens
//! are the *floor* (the indexer always folds them in); everything here is the
//! curation on top, written along six axes:
//!
//! 1. synonyms — truck/lorry/van/pickup
//! 2. kid vocabulary and misspellings — "digger", "baddie", "vehical"
//! 3. function and use — "something to drive", "somewhere to hide"
//! 4. visual qualities — colour, size class, material
//! 5. setting and theme — city, medieval, racing, sci-fi
//! 6. phrasing a 7-year-old or an LLM would actually type
//!
//! Axis 3 earns its keep the most: a kid says what they want to DO, and an
//! agent says what it needs the model FOR. Neither says "vehicle-truck-yellow".

/// One curated row. `key` is `<pack>/<file-stem>`, which is anchored to where
/// the file lives — so ids stay stable when categories are retuned.
pub struct Alias {
    pub key: &'static str,
    pub name: &'static str,
    pub categories: &'static [&'static str],
    pub aliases: &'static [&'static str],
}

/// Category hierarchy, stated in one sentence: things you drive, characters,
/// nature, buildings, roads you drive on, ground you stand on, props you use,
/// and effects. Items may sit in more than one.
pub const CATEGORIES: &[&str] = &[
    "vehicle/ground",
    "character/player",
    "character/enemy",
    "nature/tree",
    "nature/plant",
    "nature/sky",
    "building/residential",
    "building/structure",
    "road/street",
    "road/track",
    "terrain/platform",
    "terrain/floor",
    "terrain/wall",
    "terrain/stairs",
    "prop/decoration",
    "prop/weapon",
    "prop/pickup",
    "effect/particle",
];

/// Query-time expansion: a term the user typed -> terms we search for.
/// Includes British/American pairs and the misspellings a child actually
/// produces, because a 7-year-old's spelling should still hit.
pub const SYNONYMS: &[(&str, &[&str])] = &[
    // vehicles
    ("lorry", &["truck"]),
    ("van", &["truck"]),
    ("pickup", &["truck"]),
    ("hauler", &["truck"]),
    ("semi", &["truck"]),
    ("auto", &["car", "vehicle"]),
    ("automobile", &["car", "vehicle"]),
    ("motor", &["car", "vehicle"]),
    ("racecar", &["car", "racer"]),
    ("motorbike", &["motorcycle"]),
    ("moto", &["motorcycle"]),
    ("bike", &["motorcycle"]),
    ("scooter", &["motorcycle"]),
    ("motercycle", &["motorcycle"]),   // misspelling
    ("motorcyle", &["motorcycle"]),    // misspelling
    ("vehical", &["vehicle"]),         // misspelling
    ("vehicel", &["vehicle"]),         // misspelling
    ("bycicle", &["bicycle", "motorcycle"]),
    ("truk", &["truck"]),              // misspelling
    // aircraft (no models yet — expansions ready for the next pack)
    ("aeroplane", &["plane", "aircraft"]),
    ("airplane", &["plane", "aircraft"]),
    ("jet", &["plane", "aircraft"]),
    ("aircraft", &["plane"]),
    ("chopper", &["helicopter"]),
    ("heli", &["helicopter"]),
    ("hilicopter", &["helicopter"]),   // misspelling
    // construction
    ("digger", &["excavator", "construction"]),
    ("jcb", &["excavator", "construction"]),
    ("bulldozer", &["excavator", "construction"]),
    // characters
    ("baddie", &["enemy"]),
    ("baddy", &["enemy"]),
    ("villain", &["enemy"]),
    ("monster", &["enemy"]),
    ("mob", &["enemy"]),
    ("foe", &["enemy"]),
    ("alien", &["enemy"]),
    ("dude", &["character"]),
    ("guy", &["character"]),
    ("man", &["character"]),
    ("person", &["character"]),
    ("avatar", &["character"]),
    ("hero", &["character", "player"]),
    ("charecter", &["character"]),     // misspelling
    ("caracter", &["character"]),      // misspelling
    ("knight", &["character", "medieval", "warrior"]),
    ("warrior", &["character", "soldier"]),
    ("army", &["soldier", "military"]),
    // nature
    ("boulder", &["rock"]),
    ("stone", &["rock"]),
    ("pine", &["tree", "conifer"]),
    ("oak", &["tree"]),
    ("fir", &["tree", "conifer"]),
    ("conifer", &["tree"]),
    ("woods", &["forest", "tree"]),
    ("wood", &["forest", "tree"]),
    ("bush", &["grass", "plant", "shrub"]),
    ("shrub", &["grass", "plant"]),
    ("plant", &["grass"]),
    ("greenery", &["grass", "plant"]),
    ("lawn", &["grass"]),
    ("meadow", &["grass", "field"]),
    ("tre", &["tree"]),                // misspelling
    ("treee", &["tree"]),              // misspelling
    // buildings
    ("home", &["house"]),
    ("cottage", &["house"]),
    ("hut", &["house"]),
    ("cabin", &["house"]),
    ("shack", &["house"]),
    ("shop", &["building", "house"]),
    ("store", &["building", "house"]),
    ("skyscraper", &["building"]),
    ("tower", &["building"]),
    ("hows", &["house"]),              // misspelling
    ("hosue", &["house"]),             // misspelling
    // roads and ground
    ("tarmac", &["road", "asphalt"]),
    ("asphalt", &["road"]),
    ("highway", &["road"]),
    ("motorway", &["road"]),
    ("street", &["road"]),
    ("sidewalk", &["pavement"]),
    ("footpath", &["pavement", "path"]),
    ("walkway", &["pavement", "path"]),
    ("kerb", &["border", "curb"]),
    ("curb", &["border"]),
    ("crossroads", &["intersection"]),
    ("junction", &["intersection"]),
    ("roundabout", &["intersection"]),
    ("bend", &["corner"]),
    ("turn", &["corner"]),
    ("curve", &["corner"]),
    // structures
    ("staircase", &["stairs"]),
    ("steps", &["stairs"]),
    ("ladder", &["stairs"]),
    ("fence", &["wall", "barrier"]),
    ("barrier", &["wall"]),
    ("gateway", &["gate"]),
    ("doorway", &["gate", "door"]),
    ("entrance", &["gate"]),
    ("arch", &["gate"]),
    ("pillar", &["column"]),
    ("post", &["column"]),
    ("ledge", &["platform"]),
    ("stairs", &["steps"]),
    // props
    ("blade", &["sword"]),
    ("sworde", &["sword"]),            // misspelling
    ("lance", &["spear"]),
    ("pike", &["spear"]),
    ("gun", &["blaster", "weapon"]),
    ("pistol", &["blaster", "weapon"]),
    ("rifle", &["blaster", "weapon"]),
    ("laser", &["blaster"]),
    ("cup", &["trophy"]),
    ("prize", &["trophy"]),
    ("award", &["trophy"]),
    ("money", &["coin"]),
    ("gold", &["coin"]),
    ("cash", &["coin"]),
    ("collectible", &["coin", "pickup"]),
    ("powerup", &["coin", "pickup", "block-coin"]),
    ("treasure", &["coin", "trophy"]),
    ("crate", &["block", "box"]),
    ("box", &["block", "crate"]),
    ("cube", &["block"]),
    ("banner", &["flag"]),
    ("pennant", &["flag"]),
    ("chequered", &["finish", "checkered"]),
    ("checkered", &["finish"]),
    ("fountain", &["water"]),
    ("statue", &["sculpture", "monument"]),
    ("sculpture", &["statue"]),
    // effects and weather
    ("smoke", &["dust", "puff"]),
    ("puff", &["dust"]),
    ("sky", &["cloud"]),
    ("weather", &["cloud"]),
    // function phrases — the axis that matters most
    ("drive", &["vehicle", "car", "truck", "road", "track"]),
    ("driving", &["vehicle", "car", "truck", "road"]),
    ("ride", &["motorcycle", "vehicle"]),
    ("riding", &["motorcycle", "vehicle"]),
    ("race", &["racing", "track", "vehicle"]),
    ("racing", &["track", "vehicle"]),
    ("shoot", &["enemy", "blaster", "target"]),
    ("shooting", &["enemy", "blaster"]),
    ("hide", &["wall", "cover", "obstacle"]),
    ("hiding", &["wall", "cover"]),
    ("cover", &["wall", "obstacle"]),
    ("jump", &["platform"]),
    ("jumping", &["platform"]),
    ("stand", &["platform", "floor"]),
    ("standing", &["platform", "floor"]),
    ("climb", &["stairs", "ladder"]),
    ("climbing", &["stairs"]),
    ("collect", &["coin", "pickup"]),
    ("collecting", &["coin", "pickup"]),
    ("decorate", &["decoration"]),
    ("decor", &["decoration"]),
    ("scenery", &["decoration"]),
    ("obstacle", &["block", "wall"]),
    ("play", &["character", "player"]),
    // size and quality
    ("big", &["large"]),
    ("huge", &["large"]),
    ("giant", &["large"]),
    ("massive", &["large"]),
    ("tiny", &["small"]),
    ("little", &["small"]),
    ("lowpoly", &["blocky"]),
    ("blocky", &["lowpoly"]),
    // --- catalogue-aware expansions -------------------------------------
    // Added after measuring real misses against the full 4400-model library:
    // Kenney's space pack names everything "craft_*", its pets are "animal-*",
    // and kids do not use either word.
    ("spaceship", &["craft", "speeder", "space"]),
    ("rocket", &["craft", "speeder", "space"]),
    ("spacecraft", &["craft", "speeder"]),
    ("ufo", &["craft", "alien", "space"]),
    ("shuttle", &["craft", "space"]),
    ("kitten", &["cat"]),
    ("puppy", &["dog"]),
    ("doggy", &["dog"]),
    ("rabbit", &["bunny"]),
    ("hare", &["bunny"]),
    ("bird", &["parrot", "chick"]),
    ("birdie", &["parrot", "chick"]),
    ("piggy", &["pig", "hog"]),
    ("bear", &["polar", "koala"]),
    ("teddy", &["bear", "koala"]),
    ("dino", &["dinosaur"]),
    ("couch", &["sofa"]),
    ("settee", &["sofa"]),
    ("armchair", &["chair"]),
    ("telly", &["television", "tv"]),
    ("fridge", &["refrigerator", "kitchen"]),
    ("cooker", &["stove", "oven", "kitchen"]),
    ("burger", &["hamburger", "cheeseburger"]),
    ("fries", &["chips", "fry"]),
    ("sweets", &["candy"]),
    ("lolly", &["candy", "lollipop"]),
    ("veg", &["vegetable", "carrot", "broccoli"]),
    ("skyscraper", &["building", "tower", "commercial"]),
    ("cop", &["police"]),
    ("ambulance", &["emergency", "hospital"]),
    ("firetruck", &["fire", "emergency"]),
    ("digger", &["excavator", "tractor", "construction"]),
    ("tractor", &["farm"]),
    ("choo", &["train", "locomotive"]),
    ("carriage", &["wagon", "train"]),
    ("yacht", &["boat", "sail"]),
    ("canoe", &["boat", "row"]),
    ("submarine", &["boat", "ship"]),
    ("zombie", &["monster", "enemy", "spooky"]),
    ("skeleton", &["bones", "spooky", "graveyard"]),
    ("pumpkin", &["halloween", "graveyard"]),
    ("gravestone", &["grave", "tombstone", "graveyard"]),
    ("tombstone", &["grave", "graveyard"]),
    ("xmas", &["christmas", "holiday"]),
    ("santa", &["christmas", "holiday"]),
    ("snowman", &["snow", "winter", "holiday"]),
    ("conveyor", &["belt", "factory"]),
    ("crane", &["construction", "factory"]),
    ("hoop", &["ring", "arch"]),
    ("ramp", &["jump", "slope"]),
    // theme
    ("town", &["city", "urban"]),
    ("urban", &["city"]),
    ("outdoors", &["nature"]),
    ("outdoor", &["nature"]),
    ("scifi", &["space", "sci-fi"]),
    ("space", &["sci-fi"]),
    ("fantasy", &["medieval"]),
    ("castle", &["medieval", "fortress"]),
    ("fortress", &["medieval", "castle"]),
    ("roman", &["ancient"]),
    ("greek", &["ancient"]),
];

/// The curated catalogue. Keyed by `<pack>/<stem>`.
pub const ALIASES: &[Alias] = &[
    // ------------------------------------------------------- nature: rocks
    // Landscape rocks lost "boulder" to `tower-defense-kit/weapon-ammo-boulder`
    // — catapult ammo — purely because that filename says the word and these
    // reach it only through the boulder->rock synonym. A confidently wrong top
    // hit is worse than a miss here, because a composer places it five times.
    Alias { key: "nature-kit/rock_largeA", name: "Boulder", categories: &["nature/rock"],
        aliases: &["boulder", "rock", "stone", "big rock", "large rock", "landscape", "scenery", "nature", "outcrop"] },
    Alias { key: "nature-kit/rock_largeB", name: "Boulder", categories: &["nature/rock"],
        aliases: &["boulder", "rock", "stone", "big rock", "large rock", "landscape", "scenery", "nature", "outcrop"] },
    Alias { key: "nature-kit/rock_largeC", name: "Boulder", categories: &["nature/rock"],
        aliases: &["boulder", "rock", "stone", "big rock", "large rock", "landscape", "scenery", "nature", "outcrop"] },
    Alias { key: "nature-kit/rock_largeD", name: "Boulder", categories: &["nature/rock"],
        aliases: &["boulder", "rock", "stone", "big rock", "large rock", "landscape", "scenery", "nature", "outcrop"] },
    Alias { key: "nature-kit/rock_largeE", name: "Boulder", categories: &["nature/rock"],
        aliases: &["boulder", "rock", "stone", "big rock", "large rock", "landscape", "scenery", "nature", "outcrop"] },
    Alias { key: "nature-kit/rock_largeF", name: "Boulder", categories: &["nature/rock"],
        aliases: &["boulder", "rock", "stone", "big rock", "large rock", "landscape", "scenery", "nature", "outcrop"] },
    Alias { key: "nature-kit/rock_smallA", name: "Rock", categories: &["nature/rock"],
        aliases: &["rock", "stone", "boulder", "small rock", "pebble", "landscape", "scenery", "nature"] },
    Alias { key: "nature-kit/rock_smallB", name: "Rock", categories: &["nature/rock"],
        aliases: &["rock", "stone", "boulder", "small rock", "pebble", "landscape", "scenery", "nature"] },
    // ---------------------------------------------------------------- arena
    Alias { key: "arena/banner", name: "Banner", categories: &["prop/decoration"],
        aliases: &["banner", "flag", "pennant", "cloth", "hanging", "decoration", "medieval", "castle", "scenery", "wall hanging"] },
    Alias { key: "arena/block", name: "Stone Block", categories: &["prop/decoration", "terrain/platform"],
        aliases: &["block", "cube", "box", "crate", "stone block", "obstacle", "building block", "medieval", "stone", "something to jump on", "push"] },
    Alias { key: "arena/border-corner", name: "Border Corner", categories: &["terrain/floor"],
        aliases: &["border", "corner", "kerb", "curb", "edge", "trim", "boundary", "arena edge", "medieval"] },
    Alias { key: "arena/border-straight", name: "Border", categories: &["terrain/floor"],
        aliases: &["border", "straight", "kerb", "curb", "edge", "trim", "boundary", "arena edge", "medieval"] },
    Alias { key: "arena/bricks", name: "Rubble", categories: &["prop/decoration"],
        aliases: &["bricks", "rubble", "debris", "stones", "pile", "ruins", "broken", "scenery", "medieval", "wreckage"] },
    Alias { key: "arena/character-soldier", name: "Soldier", categories: &["character/player"],
        aliases: &["soldier", "character", "guy", "man", "person", "player", "fighter", "warrior", "army", "military", "someone to play as", "hero", "dude", "avatar"] },
    Alias { key: "arena/column-damaged", name: "Broken Column", categories: &["building/structure", "prop/decoration"],
        aliases: &["column", "pillar", "broken column", "ruined pillar", "ruin", "ancient", "temple", "greek", "roman", "obstacle", "cover", "medieval", "damaged"] },
    Alias { key: "arena/column", name: "Column", categories: &["building/structure"],
        aliases: &["column", "pillar", "post", "temple", "ancient", "greek", "roman", "support", "obstacle", "cover", "somewhere to hide", "medieval"] },
    Alias { key: "arena/floor-detail", name: "Detailed Floor", categories: &["terrain/floor"],
        aliases: &["floor", "ground", "tile", "paving", "surface", "somewhere to stand", "detailed floor", "arena floor", "medieval", "stone floor"] },
    Alias { key: "arena/floor", name: "Floor", categories: &["terrain/floor"],
        aliases: &["floor", "ground", "tile", "paving", "surface", "somewhere to stand", "arena floor", "medieval", "stone floor", "platform"] },
    Alias { key: "arena/stairs-corner-inner", name: "Inner Corner Stairs", categories: &["terrain/stairs"],
        aliases: &["stairs", "steps", "staircase", "corner stairs", "inner corner", "climb", "way up", "medieval"] },
    Alias { key: "arena/stairs-corner", name: "Corner Stairs", categories: &["terrain/stairs"],
        aliases: &["stairs", "steps", "staircase", "corner stairs", "climb", "way up", "medieval"] },
    Alias { key: "arena/stairs", name: "Stairs", categories: &["terrain/stairs"],
        aliases: &["stairs", "steps", "staircase", "climb", "way up", "ramp", "medieval", "somewhere to climb"] },
    Alias { key: "arena/statue", name: "Statue", categories: &["prop/decoration"],
        aliases: &["statue", "sculpture", "monument", "figure", "landmark", "decoration", "stone figure", "medieval", "ancient", "scenery"] },
    Alias { key: "arena/tree", name: "Tree", categories: &["nature/tree"],
        aliases: &["tree", "oak", "leafy tree", "plant", "nature", "forest", "wood", "shade", "scenery", "greenery", "big tree"] },
    Alias { key: "arena/trophy", name: "Trophy", categories: &["prop/pickup", "prop/decoration"],
        aliases: &["trophy", "cup", "prize", "award", "winner", "goal", "reward", "treasure", "gold cup", "champion", "something to win"] },
    Alias { key: "arena/wall-corner", name: "Wall Corner", categories: &["terrain/wall"],
        aliases: &["wall", "corner wall", "barrier", "cover", "obstacle", "fortress", "castle", "medieval", "somewhere to hide"] },
    Alias { key: "arena/wall-gate", name: "Gate", categories: &["terrain/wall", "building/structure"],
        aliases: &["gate", "gateway", "doorway", "entrance", "arch", "wall with door", "castle gate", "way in", "portal", "medieval", "door"] },
    Alias { key: "arena/wall", name: "Wall", categories: &["terrain/wall"],
        aliases: &["wall", "barrier", "block", "cover", "obstacle", "fence", "fortress", "castle", "medieval", "somewhere to hide", "something to hide behind"] },
    Alias { key: "arena/weapon-rack", name: "Weapon Rack", categories: &["prop/decoration"],
        aliases: &["weapon rack", "rack", "armoury", "armory", "stand", "weapons", "decoration", "medieval", "castle", "scenery"] },
    Alias { key: "arena/weapon-spear", name: "Spear", categories: &["prop/weapon"],
        aliases: &["spear", "lance", "pike", "polearm", "weapon", "medieval", "pointy stick", "stabby", "knight weapon"] },
    Alias { key: "arena/weapon-sword", name: "Sword", categories: &["prop/weapon"],
        aliases: &["sword", "blade", "weapon", "knight sword", "medieval", "sharp", "fighting", "something to fight with"] },
    // ----------------------------------------------------------------- city
    Alias { key: "city/building-garage", name: "Garage", categories: &["building/residential"],
        aliases: &["garage", "carport", "workshop", "shed", "building", "car park", "urban", "city", "town", "somewhere to park"] },
    Alias { key: "city/building-small-a", name: "Small House A", categories: &["building/residential"],
        aliases: &["house", "home", "building", "small house", "cottage", "hut", "shop", "urban", "city", "town", "somewhere to live", "residential"] },
    Alias { key: "city/building-small-b", name: "Small House B", categories: &["building/residential"],
        aliases: &["house", "home", "building", "small house", "cottage", "hut", "shop", "urban", "city", "town", "somewhere to live", "residential"] },
    Alias { key: "city/building-small-c", name: "Small House C", categories: &["building/residential"],
        aliases: &["house", "home", "building", "small house", "cottage", "hut", "shop", "urban", "city", "town", "somewhere to live", "residential"] },
    Alias { key: "city/building-small-d", name: "Small House D", categories: &["building/residential"],
        aliases: &["house", "home", "building", "small house", "cottage", "hut", "shop", "urban", "city", "town", "somewhere to live", "residential"] },
    Alias { key: "city/grass-trees-tall", name: "Tall Trees", categories: &["nature/tree"],
        aliases: &["trees", "tall trees", "forest", "woods", "nature", "park", "greenery", "scenery", "treeline", "trees for a forest"] },
    Alias { key: "city/grass-trees", name: "Trees", categories: &["nature/tree"],
        aliases: &["trees", "forest", "woods", "nature", "park", "greenery", "scenery", "grass with trees", "trees for a forest"] },
    Alias { key: "city/grass", name: "Grass", categories: &["nature/plant", "terrain/floor"],
        aliases: &["grass", "lawn", "field", "green", "ground", "nature", "park", "meadow", "somewhere to stand", "greenery"] },
    Alias { key: "city/pavement-fountain", name: "Fountain", categories: &["prop/decoration"],
        aliases: &["fountain", "water", "water feature", "plaza", "square", "decoration", "park", "town centre", "town center", "city", "scenery"] },
    Alias { key: "city/pavement", name: "Pavement", categories: &["terrain/floor", "road/street"],
        aliases: &["pavement", "sidewalk", "paving", "path", "walkway", "footpath", "ground", "street", "city", "somewhere to walk"] },
    Alias { key: "city/road-corner", name: "Road Corner", categories: &["road/street"],
        aliases: &["road", "street", "corner", "bend", "turn", "curve", "tarmac", "asphalt", "drive on", "city", "something to drive on"] },
    Alias { key: "city/road-intersection", name: "Crossroads", categories: &["road/street"],
        aliases: &["road", "crossroads", "intersection", "junction", "four way", "street", "drive on", "city", "traffic"] },
    Alias { key: "city/road-split", name: "T Junction", categories: &["road/street"],
        aliases: &["road", "junction", "t junction", "split", "fork", "street", "drive on", "city", "intersection"] },
    Alias { key: "city/road-straight-lightposts", name: "Road with Lights", categories: &["road/street"],
        aliases: &["road", "street", "straight road", "lamp posts", "street lights", "lighting", "drive on", "city", "lit road", "lampposts"] },
    Alias { key: "city/road-straight", name: "Straight Road", categories: &["road/street"],
        aliases: &["road", "street", "straight", "tarmac", "asphalt", "drive on", "highway", "city", "something to drive on"] },
    // ------------------------------------------------------------------ fps
    Alias { key: "fps/blaster-repeater", name: "Repeater Blaster", categories: &["prop/weapon"],
        aliases: &["blaster", "gun", "rifle", "repeater", "weapon", "laser gun", "shooter", "sci-fi", "space gun", "rapid fire", "machine gun", "something to shoot with"] },
    Alias { key: "fps/blaster", name: "Blaster", categories: &["prop/weapon"],
        aliases: &["blaster", "gun", "pistol", "weapon", "laser", "shooter", "sci-fi", "space gun", "raygun", "something to shoot with"] },
    Alias { key: "fps/cloud", name: "Cloud", categories: &["nature/sky"],
        aliases: &["cloud", "sky", "weather", "floating", "decoration", "fluffy", "white cloud", "scenery"] },
    Alias { key: "fps/enemy-flying", name: "Flying Enemy", categories: &["character/enemy"],
        aliases: &["enemy", "baddie", "bad guy", "monster", "flying enemy", "drone", "alien", "something to shoot at", "villain", "foe", "mob", "scary", "flying monster", "boss"] },
    Alias { key: "fps/grass-small", name: "Small Grass", categories: &["nature/plant"],
        aliases: &["grass", "small grass", "tuft", "plant", "bush", "nature", "ground cover", "greenery", "little grass"] },
    Alias { key: "fps/grass", name: "Grass Tuft", categories: &["nature/plant"],
        aliases: &["grass", "plant", "bush", "shrub", "nature", "greenery", "ground cover", "foliage"] },
    Alias { key: "fps/platform-large-grass", name: "Large Grass Platform", categories: &["terrain/platform"],
        aliases: &["platform", "grass platform", "ledge", "floating island", "somewhere to stand", "jump on", "large platform", "big platform", "island"] },
    Alias { key: "fps/platform", name: "Platform", categories: &["terrain/platform"],
        aliases: &["platform", "ledge", "floating platform", "somewhere to stand", "jump on", "step", "block"] },
    Alias { key: "fps/wall-high", name: "High Wall", categories: &["terrain/wall"],
        aliases: &["wall", "high wall", "tall wall", "barrier", "cover", "obstacle", "somewhere to hide", "big wall", "something to hide behind"] },
    Alias { key: "fps/wall-low", name: "Low Wall", categories: &["terrain/wall"],
        aliases: &["wall", "low wall", "barrier", "cover", "crouch behind", "obstacle", "somewhere to hide", "small wall", "something to hide behind"] },
    // ----------------------------------------------------------- platformer
    Alias { key: "platformer/block-coin", name: "Coin Block", categories: &["prop/pickup"],
        aliases: &["coin block", "question block", "mystery box", "item block", "powerup box", "hit block", "surprise", "bonus", "mario block"] },
    Alias { key: "platformer/brick-particle", name: "Brick Chunk", categories: &["effect/particle"],
        aliases: &["brick particle", "debris", "chunk", "rubble", "effect", "broken piece", "smash", "fragment"] },
    Alias { key: "platformer/brick", name: "Brick Block", categories: &["prop/decoration", "terrain/platform"],
        aliases: &["brick", "block", "breakable block", "wall block", "obstacle", "smash", "break", "something to jump on"] },
    Alias { key: "platformer/character", name: "Platformer Character", categories: &["character/player"],
        aliases: &["character", "player", "guy", "hero", "dude", "person", "someone to play as", "avatar", "mascot", "little guy", "my guy"] },
    Alias { key: "platformer/cloud", name: "Cloud", categories: &["nature/sky"],
        aliases: &["cloud", "sky", "floating", "weather", "decoration", "fluffy", "white cloud"] },
    Alias { key: "platformer/coin", name: "Coin", categories: &["prop/pickup"],
        aliases: &["coin", "money", "gold", "pickup", "collectible", "treasure", "points", "score", "collect", "something to collect", "reward"] },
    Alias { key: "platformer/dust", name: "Dust Puff", categories: &["effect/particle"],
        aliases: &["dust", "puff", "smoke", "effect", "particle", "cloud", "landing effect", "poof"] },
    Alias { key: "platformer/flag", name: "Flag", categories: &["prop/decoration"],
        aliases: &["flag", "goal", "finish", "checkpoint", "banner", "end of level", "marker", "target", "somewhere to reach"] },
    Alias { key: "platformer/grass-small", name: "Small Grass", categories: &["nature/plant"],
        aliases: &["grass", "small grass", "tuft", "plant", "nature", "greenery", "little grass"] },
    Alias { key: "platformer/grass", name: "Grass", categories: &["nature/plant"],
        aliases: &["grass", "plant", "bush", "nature", "greenery", "foliage"] },
    Alias { key: "platformer/platform-falling", name: "Falling Platform", categories: &["terrain/platform"],
        aliases: &["falling platform", "crumbling platform", "unstable", "trap", "platform", "hazard", "danger", "collapsing"] },
    Alias { key: "platformer/platform-grass-large-round", name: "Round Grass Platform", categories: &["terrain/platform"],
        aliases: &["round platform", "grass platform", "island", "large platform", "somewhere to stand", "big platform", "circle platform"] },
    Alias { key: "platformer/platform-large", name: "Large Platform", categories: &["terrain/platform"],
        aliases: &["large platform", "big platform", "ledge", "somewhere to stand", "jump on", "wide platform"] },
    Alias { key: "platformer/platform-medium", name: "Medium Platform", categories: &["terrain/platform"],
        aliases: &["medium platform", "platform", "ledge", "jump on", "somewhere to stand"] },
    Alias { key: "platformer/platform", name: "Small Platform", categories: &["terrain/platform"],
        aliases: &["platform", "ledge", "block", "somewhere to stand", "jump on", "small platform", "step"] },
    // --------------------------------------------------------------- racing
    Alias { key: "racing/decoration-empty", name: "Empty Roadside", categories: &["prop/decoration"],
        aliases: &["decoration", "empty", "plain", "scenery", "filler", "roadside", "blank", "racing"] },
    Alias { key: "racing/decoration-forest", name: "Roadside Forest", categories: &["nature/tree", "prop/decoration"],
        aliases: &["forest", "trees", "woods", "roadside trees", "scenery", "nature", "decoration", "racing", "trees for a forest", "treeline"] },
    Alias { key: "racing/decoration-tents", name: "Roadside Tents", categories: &["prop/decoration"],
        aliases: &["tents", "camp", "marquee", "spectators", "event", "scenery", "decoration", "race day", "racing", "crowd"] },
    Alias { key: "racing/track-bump", name: "Track Bump", categories: &["road/track"],
        aliases: &["track", "bump", "jump", "ramp", "hump", "race track", "obstacle", "racing", "something to jump off"] },
    Alias { key: "racing/track-corner", name: "Track Corner", categories: &["road/track"],
        aliases: &["track", "corner", "bend", "turn", "curve", "race track", "drive on", "racing", "something to drive on"] },
    Alias { key: "racing/track-finish", name: "Finish Line", categories: &["road/track"],
        aliases: &["finish line", "start line", "finish", "goal", "chequered", "checkered", "race track", "end", "racing", "winner", "start"] },
    Alias { key: "racing/track-straight", name: "Straight Track", categories: &["road/track"],
        aliases: &["track", "straight", "race track", "drive on", "road", "racing", "something to drive on"] },
    Alias { key: "racing/track-tents", name: "Track with Tents", categories: &["road/track"],
        aliases: &["track with tents", "race track", "grandstand", "spectators", "event", "racing", "crowd", "pit lane"] },
    Alias { key: "racing/vehicle-motorcycle", name: "Motorcycle", categories: &["vehicle/ground"],
        aliases: &["motorcycle", "motorbike", "bike", "moto", "motor bike", "two wheeler", "something to ride", "fast", "racer", "racing", "speed", "vehicle"] },
    Alias { key: "racing/vehicle-truck-green", name: "Green Truck", categories: &["vehicle/ground"],
        aliases: &["truck", "lorry", "van", "pickup", "hauler", "car", "green truck", "green", "something to drive", "racer", "racing", "vehicle", "fast"] },
    Alias { key: "racing/vehicle-truck-purple", name: "Purple Truck", categories: &["vehicle/ground"],
        aliases: &["truck", "lorry", "van", "pickup", "hauler", "car", "purple truck", "purple", "something to drive", "racer", "racing", "vehicle", "fast"] },
    Alias { key: "racing/vehicle-truck-red", name: "Red Truck", categories: &["vehicle/ground"],
        aliases: &["truck", "lorry", "van", "pickup", "hauler", "car", "red truck", "red", "something to drive", "racer", "racing", "vehicle", "fast"] },
    Alias { key: "racing/vehicle-truck-yellow", name: "Yellow Truck", categories: &["vehicle/ground"],
        aliases: &["truck", "lorry", "van", "pickup", "hauler", "car", "yellow truck", "yellow", "something to drive", "racer", "racing", "vehicle", "fast"] },
    // ------------------------------------------------------------- kaykit
    Alias { key: "characters/knight", name: "Knight", categories: &["character/player"],
        aliases: &["knight", "character", "player", "hero", "warrior", "soldier", "armour", "armor", "medieval", "fighter", "someone to play as", "guy", "dude", "man", "person", "avatar", "animated", "rigged", "walking"] },
];

/// Look up a curated row by `<pack>/<stem>`.
pub fn lookup(key: &str) -> Option<&'static Alias> {
    ALIASES.iter().find(|a| a.key == key)
}

/// Expand one query term into the terms we should search for. Consults the
/// model table and the audio table, so one query ranks across both libraries.
/// Deterministic order: model table, then audio table.
pub fn expand(term: &str) -> Vec<&'static str> {
    let mut out = Vec::new();
    for (from, to) in SYNONYMS.iter().chain(crate::audio_aliases::AUDIO_SYNONYMS) {
        if *from == term {
            for t in *to {
                if !out.contains(t) {
                    out.push(*t);
                }
            }
        }
    }
    out
}
