//! Curated aliases for the sound library, keyed by *family* rather than file.
//!
//! Kenney's audio ships in numbered variants (`footstep_wood_000..004`), so the
//! curation lives on the family and every variant inherits it — 550-odd files
//! collapse to ~116 rows a human can actually maintain.
//!
//! Audio needs axes the models don't:
//!
//! - **event/trigger**: hit, crash, jump, land, shoot, pickup, win, click
//! - **material**: wood, metal, glass, stone, dirt — an impact is chosen by
//!   *what hit what*, so these are load-bearing for automatic emission
//! - **mood/intensity**: soft/hard, small/big, retro/modern, happy/tense
//! - **function**: "sound for when you get hit", "music for a race"
//!
//! Music is marked so a game never fires a 30-second track as a hit sound.

use crate::AssetKind;

pub struct AudioAlias {
    /// `<pack>/<family>` — family is the filename with its variant number
    /// stripped.
    pub key: &'static str,
    pub name: &'static str,
    pub kind: AssetKind,
    pub categories: &'static [&'static str],
    pub aliases: &'static [&'static str],
}

/// Sound categories, kept parallel in spirit to the model tree.
pub const AUDIO_CATEGORIES: &[&str] = &[
    "sound/footstep",
    "sound/impact",
    "sound/weapon",
    "sound/ui",
    "sound/pickup",
    "sound/engine",
    "sound/ambient",
    "sound/voice",
    "music/jingle",
];

pub const AUDIO_ALIASES: &[AudioAlias] = &[
    // ------------------------------------------------------ footsteps
    AudioAlias { key: "impact-sounds/footstep_carpet", name: "Footstep (carpet)", kind: AssetKind::Sound,
        categories: &["sound/footstep"],
        aliases: &["footstep", "step", "walk", "walking", "running", "carpet", "soft", "indoor", "quiet", "sound when you walk"] },
    AudioAlias { key: "impact-sounds/footstep_concrete", name: "Footstep (concrete)", kind: AssetKind::Sound,
        categories: &["sound/footstep"],
        aliases: &["footstep", "step", "walk", "walking", "running", "concrete", "stone", "pavement", "hard", "city", "sound when you walk"] },
    AudioAlias { key: "impact-sounds/footstep_grass", name: "Footstep (grass)", kind: AssetKind::Sound,
        categories: &["sound/footstep"],
        aliases: &["footstep", "step", "walk", "walking", "running", "grass", "outdoor", "nature", "soft", "sound when you walk"] },
    AudioAlias { key: "impact-sounds/footstep_snow", name: "Footstep (snow)", kind: AssetKind::Sound,
        categories: &["sound/footstep"],
        aliases: &["footstep", "step", "walk", "walking", "snow", "ice", "winter", "crunch", "cold"] },
    AudioAlias { key: "impact-sounds/footstep_wood", name: "Footstep (wood)", kind: AssetKind::Sound,
        categories: &["sound/footstep"],
        aliases: &["footstep", "step", "walk", "walking", "running", "wood", "wooden", "plank", "floorboard", "footsteps on wood"] },
    AudioAlias { key: "rpg-audio/footstep", name: "Footstep", kind: AssetKind::Sound,
        categories: &["sound/footstep"],
        aliases: &["footstep", "step", "walk", "walking", "running", "medieval", "rpg"] },
    // --------------------------------------------------------- impacts
    AudioAlias { key: "impact-sounds/impactGeneric_light", name: "Light Impact", kind: AssetKind::Sound,
        categories: &["sound/impact"],
        aliases: &["impact", "hit", "bump", "tap", "knock", "light", "small", "soft", "gentle", "sound when you get hit", "collide"] },
    AudioAlias { key: "impact-sounds/impactBell_heavy", name: "Bell Impact", kind: AssetKind::Sound,
        categories: &["sound/impact"],
        aliases: &["impact", "bell", "clang", "ring", "chime", "metal", "heavy", "gong", "hit"] },
    AudioAlias { key: "impact-sounds/impactGlass_light", name: "Glass Impact (light)", kind: AssetKind::Sound,
        categories: &["sound/impact"],
        aliases: &["impact", "glass", "tink", "clink", "light", "small", "break", "shatter", "hit", "fragile"] },
    AudioAlias { key: "impact-sounds/impactGlass_medium", name: "Glass Impact", kind: AssetKind::Sound,
        categories: &["sound/impact"],
        aliases: &["impact", "glass", "clink", "break", "shatter", "smash", "medium", "hit", "fragile", "window"] },
    AudioAlias { key: "impact-sounds/impactGlass_heavy", name: "Glass Smash", kind: AssetKind::Sound,
        categories: &["sound/impact"],
        aliases: &["impact", "glass", "smash", "shatter", "break", "crash", "heavy", "big", "window", "hit hard"] },
    AudioAlias { key: "impact-sounds/impactMetal_light", name: "Metal Impact (light)", kind: AssetKind::Sound,
        categories: &["sound/impact"],
        aliases: &["impact", "metal", "clink", "ting", "light", "small", "hit", "metallic"] },
    AudioAlias { key: "impact-sounds/impactMetal_medium", name: "Metal Impact", kind: AssetKind::Sound,
        categories: &["sound/impact"],
        aliases: &["impact", "metal", "clang", "bang", "hit", "medium", "metallic", "car", "crash into metal"] },
    AudioAlias { key: "impact-sounds/impactMetal_heavy", name: "Metal Crash", kind: AssetKind::Sound,
        categories: &["sound/impact"],
        aliases: &["impact", "metal", "clang", "crash", "bang", "heavy", "big", "hard", "car crash", "smash", "collision"] },
    AudioAlias { key: "sci-fi-sounds/impactMetal", name: "Sci-Fi Metal Impact", kind: AssetKind::Sound,
        categories: &["sound/impact"],
        aliases: &["impact", "metal", "clang", "sci-fi", "space", "hit", "robot", "mech"] },
    AudioAlias { key: "impact-sounds/impactWood_light", name: "Wood Impact (light)", kind: AssetKind::Sound,
        categories: &["sound/impact"],
        aliases: &["impact", "wood", "wooden", "knock", "tap", "light", "small", "hit"] },
    AudioAlias { key: "impact-sounds/impactWood_medium", name: "Wood Impact", kind: AssetKind::Sound,
        categories: &["sound/impact"],
        aliases: &["impact", "wood", "wooden", "thud", "knock", "hit", "medium", "crate", "box"] },
    AudioAlias { key: "impact-sounds/impactWood_heavy", name: "Wood Crash", kind: AssetKind::Sound,
        categories: &["sound/impact"],
        aliases: &["impact", "wood", "wooden", "crash", "smash", "break", "heavy", "big", "crate", "hit hard"] },
    AudioAlias { key: "impact-sounds/impactPlank_medium", name: "Plank Impact", kind: AssetKind::Sound,
        categories: &["sound/impact"],
        aliases: &["impact", "plank", "wood", "board", "thud", "hit", "wooden"] },
    AudioAlias { key: "impact-sounds/impactPlate_light", name: "Plate Impact (light)", kind: AssetKind::Sound,
        categories: &["sound/impact"],
        aliases: &["impact", "plate", "metal", "sheet", "light", "hit", "ting"] },
    AudioAlias { key: "impact-sounds/impactPlate_medium", name: "Plate Impact", kind: AssetKind::Sound,
        categories: &["sound/impact"],
        aliases: &["impact", "plate", "metal", "sheet", "hit", "clang", "medium"] },
    AudioAlias { key: "impact-sounds/impactPlate_heavy", name: "Plate Crash", kind: AssetKind::Sound,
        categories: &["sound/impact"],
        aliases: &["impact", "plate", "metal", "sheet", "crash", "clang", "heavy", "big", "loud"] },
    AudioAlias { key: "impact-sounds/impactPunch_medium", name: "Punch", kind: AssetKind::Sound,
        categories: &["sound/impact"],
        aliases: &["punch", "hit", "impact", "fight", "thump", "melee", "attack", "sound when you get hit", "smack"] },
    AudioAlias { key: "impact-sounds/impactPunch_heavy", name: "Heavy Punch", kind: AssetKind::Sound,
        categories: &["sound/impact"],
        aliases: &["punch", "hit", "impact", "fight", "thump", "melee", "attack", "heavy", "big", "hard", "smack"] },
    AudioAlias { key: "impact-sounds/impactSoft_medium", name: "Soft Impact", kind: AssetKind::Sound,
        categories: &["sound/impact"],
        aliases: &["impact", "soft", "thud", "muffled", "land", "landing", "body", "hit", "gentle"] },
    AudioAlias { key: "impact-sounds/impactSoft_heavy", name: "Heavy Soft Impact", kind: AssetKind::Sound,
        categories: &["sound/impact"],
        aliases: &["impact", "soft", "thud", "heavy", "land", "landing", "big", "body", "fall"] },
    AudioAlias { key: "impact-sounds/impactTin_medium", name: "Tin Impact", kind: AssetKind::Sound,
        categories: &["sound/impact"],
        aliases: &["impact", "tin", "can", "metal", "rattle", "hit", "clank"] },
    AudioAlias { key: "impact-sounds/impactMining", name: "Mining Impact", kind: AssetKind::Sound,
        categories: &["sound/impact"],
        aliases: &["mining", "pickaxe", "dig", "digging", "rock", "stone", "hit", "mine", "quarry"] },
    // ---------------------------------------------------------- weapons
    AudioAlias { key: "sci-fi-sounds/laserSmall", name: "Small Laser", kind: AssetKind::Sound,
        categories: &["sound/weapon"],
        aliases: &["laser", "shoot", "shot", "pew", "blaster", "gun", "small", "sci-fi", "space", "zap", "laser gun", "fire"] },
    AudioAlias { key: "sci-fi-sounds/laserLarge", name: "Large Laser", kind: AssetKind::Sound,
        categories: &["sound/weapon"],
        aliases: &["laser", "shoot", "shot", "blaster", "gun", "big", "large", "heavy", "sci-fi", "cannon", "laser gun", "fire"] },
    AudioAlias { key: "sci-fi-sounds/laserRetro", name: "Retro Laser", kind: AssetKind::Sound,
        categories: &["sound/weapon"],
        aliases: &["laser", "shoot", "retro", "arcade", "8-bit", "pew", "blaster", "gun", "old school", "classic"] },
    AudioAlias { key: "digital-audio/laser", name: "Digital Laser", kind: AssetKind::Sound,
        categories: &["sound/weapon"],
        aliases: &["laser", "shoot", "zap", "blaster", "gun", "retro", "8-bit", "arcade", "pew", "digital"] },
    AudioAlias { key: "digital-audio/zap", name: "Zap", kind: AssetKind::Sound,
        categories: &["sound/weapon"],
        aliases: &["zap", "shock", "electric", "laser", "shoot", "retro", "arcade", "8-bit", "hit"] },
    AudioAlias { key: "digital-audio/zapTwoTone", name: "Zap (two tone)", kind: AssetKind::Sound,
        categories: &["sound/weapon"],
        aliases: &["zap", "shoot", "laser", "retro", "arcade", "8-bit", "electric"] },
    AudioAlias { key: "digital-audio/zapThreeToneUp", name: "Zap Up", kind: AssetKind::Sound,
        categories: &["sound/weapon", "sound/pickup"],
        aliases: &["zap", "up", "rising", "powerup", "retro", "arcade", "8-bit", "collect"] },
    AudioAlias { key: "digital-audio/zapThreeToneDown", name: "Zap Down", kind: AssetKind::Sound,
        categories: &["sound/weapon"],
        aliases: &["zap", "down", "falling", "lose", "retro", "arcade", "8-bit", "fail"] },
    AudioAlias { key: "sci-fi-sounds/explosionCrunch", name: "Explosion", kind: AssetKind::Sound,
        categories: &["sound/impact"],
        aliases: &["explosion", "boom", "blast", "crunch", "bang", "destroy", "big", "crash", "blow up", "die"] },
    AudioAlias { key: "sci-fi-sounds/lowFrequency_explosion", name: "Deep Explosion", kind: AssetKind::Sound,
        categories: &["sound/impact"],
        aliases: &["explosion", "boom", "blast", "deep", "low", "rumble", "big", "heavy", "destroy", "blow up"] },
    AudioAlias { key: "rpg-audio/knifeSlice", name: "Knife Slice", kind: AssetKind::Sound,
        categories: &["sound/weapon"],
        aliases: &["knife", "slice", "slash", "sword", "cut", "blade", "attack", "swing", "melee", "medieval"] },
    AudioAlias { key: "rpg-audio/drawKnife", name: "Draw Knife", kind: AssetKind::Sound,
        categories: &["sound/weapon"],
        aliases: &["knife", "draw", "unsheathe", "sword", "blade", "equip", "medieval", "weapon"] },
    AudioAlias { key: "rpg-audio/chop", name: "Chop", kind: AssetKind::Sound,
        categories: &["sound/weapon"],
        aliases: &["chop", "axe", "cut", "wood", "hit", "attack", "melee", "hack"] },
    // ---------------------------------------------------------- engines
    AudioAlias { key: "sci-fi-sounds/spaceEngine", name: "Space Engine", kind: AssetKind::Sound,
        categories: &["sound/engine"],
        aliases: &["engine", "motor", "rocket", "thrust", "sci-fi", "space", "hum", "flying", "loop"] },
    AudioAlias { key: "sci-fi-sounds/spaceEngineSmall", name: "Small Space Engine", kind: AssetKind::Sound,
        categories: &["sound/engine"],
        aliases: &["engine", "motor", "small", "thrust", "sci-fi", "space", "hum", "loop"] },
    AudioAlias { key: "sci-fi-sounds/spaceEngineLarge", name: "Large Space Engine", kind: AssetKind::Sound,
        categories: &["sound/engine"],
        aliases: &["engine", "motor", "big", "large", "thrust", "sci-fi", "space", "rumble", "loop"] },
    AudioAlias { key: "sci-fi-sounds/spaceEngineLow", name: "Low Space Engine", kind: AssetKind::Sound,
        categories: &["sound/engine"],
        aliases: &["engine", "motor", "low", "deep", "sci-fi", "space", "rumble", "hum", "loop"] },
    AudioAlias { key: "sci-fi-sounds/engineCircular", name: "Circular Engine", kind: AssetKind::Sound,
        categories: &["sound/engine"],
        aliases: &["engine", "motor", "machine", "loop", "hum", "whirr", "sci-fi", "machinery"] },
    AudioAlias { key: "sci-fi-sounds/thrusterFire", name: "Thruster", kind: AssetKind::Sound,
        categories: &["sound/engine"],
        aliases: &["thruster", "rocket", "boost", "jet", "engine", "fire", "sci-fi", "space", "launch"] },
    // -------------------------------------------------------- ui / menu
    AudioAlias { key: "interface-sounds/click", name: "Click", kind: AssetKind::Sound,
        categories: &["sound/ui"],
        aliases: &["click", "button", "press", "tap", "ui", "menu", "select", "interface", "tick"] },
    AudioAlias { key: "ui-audio/click", name: "UI Click", kind: AssetKind::Sound,
        categories: &["sound/ui"],
        aliases: &["click", "button", "press", "ui", "menu", "interface", "select"] },
    AudioAlias { key: "ui-audio/mouseclick", name: "Mouse Click", kind: AssetKind::Sound,
        categories: &["sound/ui"],
        aliases: &["click", "mouse", "button", "press", "ui", "menu", "interface"] },
    AudioAlias { key: "ui-audio/mouserelease", name: "Mouse Release", kind: AssetKind::Sound,
        categories: &["sound/ui"],
        aliases: &["release", "click", "mouse", "button", "unpress", "ui", "menu"] },
    AudioAlias { key: "ui-audio/rollover", name: "Rollover", kind: AssetKind::Sound,
        categories: &["sound/ui"],
        aliases: &["rollover", "hover", "highlight", "ui", "menu", "focus", "interface"] },
    AudioAlias { key: "interface-sounds/select", name: "Select", kind: AssetKind::Sound,
        categories: &["sound/ui"],
        aliases: &["select", "choose", "pick", "ui", "menu", "confirm", "interface"] },
    AudioAlias { key: "interface-sounds/confirmation", name: "Confirm", kind: AssetKind::Sound,
        categories: &["sound/ui"],
        aliases: &["confirm", "ok", "accept", "yes", "success", "ui", "menu", "positive", "good"] },
    AudioAlias { key: "interface-sounds/error", name: "Error", kind: AssetKind::Sound,
        categories: &["sound/ui"],
        aliases: &["error", "wrong", "fail", "bad", "no", "denied", "buzz", "ui", "menu", "negative", "lose"] },
    AudioAlias { key: "interface-sounds/question", name: "Question", kind: AssetKind::Sound,
        categories: &["sound/ui"],
        aliases: &["question", "prompt", "ask", "ui", "menu", "dialog", "notify"] },
    AudioAlias { key: "interface-sounds/back", name: "Back", kind: AssetKind::Sound,
        categories: &["sound/ui"],
        aliases: &["back", "cancel", "return", "undo", "ui", "menu", "escape", "previous"] },
    AudioAlias { key: "interface-sounds/close", name: "Close", kind: AssetKind::Sound,
        categories: &["sound/ui"],
        aliases: &["close", "shut", "dismiss", "ui", "menu", "window", "exit"] },
    AudioAlias { key: "interface-sounds/open", name: "Open", kind: AssetKind::Sound,
        categories: &["sound/ui"],
        aliases: &["open", "show", "reveal", "ui", "menu", "window", "appear"] },
    AudioAlias { key: "interface-sounds/maximize", name: "Maximize", kind: AssetKind::Sound,
        categories: &["sound/ui"],
        aliases: &["maximize", "expand", "grow", "bigger", "ui", "window", "up"] },
    AudioAlias { key: "interface-sounds/minimize", name: "Minimize", kind: AssetKind::Sound,
        categories: &["sound/ui"],
        aliases: &["minimize", "shrink", "smaller", "collapse", "ui", "window", "down"] },
    AudioAlias { key: "interface-sounds/toggle", name: "Toggle", kind: AssetKind::Sound,
        categories: &["sound/ui"],
        aliases: &["toggle", "switch", "flip", "on", "off", "ui", "menu", "checkbox"] },
    AudioAlias { key: "interface-sounds/switch", name: "Switch", kind: AssetKind::Sound,
        categories: &["sound/ui"],
        aliases: &["switch", "toggle", "change", "flip", "ui", "menu", "lever"] },
    AudioAlias { key: "ui-audio/switch", name: "UI Switch", kind: AssetKind::Sound,
        categories: &["sound/ui"],
        aliases: &["switch", "toggle", "change", "ui", "menu"] },
    AudioAlias { key: "interface-sounds/scroll", name: "Scroll", kind: AssetKind::Sound,
        categories: &["sound/ui"],
        aliases: &["scroll", "wheel", "list", "ui", "menu", "move"] },
    AudioAlias { key: "interface-sounds/tick", name: "Tick", kind: AssetKind::Sound,
        categories: &["sound/ui"],
        aliases: &["tick", "click", "small", "ui", "menu", "increment", "timer"] },
    AudioAlias { key: "interface-sounds/drop", name: "Drop", kind: AssetKind::Sound,
        categories: &["sound/ui", "sound/impact"],
        aliases: &["drop", "place", "put", "release", "ui", "inventory", "item"] },
    AudioAlias { key: "interface-sounds/pluck", name: "Pluck", kind: AssetKind::Sound,
        categories: &["sound/ui"],
        aliases: &["pluck", "pop", "pick", "ui", "menu", "string", "note"] },
    AudioAlias { key: "interface-sounds/bong", name: "Bong", kind: AssetKind::Sound,
        categories: &["sound/ui"],
        aliases: &["bong", "bell", "chime", "gong", "notify", "alert", "ui", "deep"] },
    AudioAlias { key: "interface-sounds/glass", name: "Glass UI", kind: AssetKind::Sound,
        categories: &["sound/ui"],
        aliases: &["glass", "chime", "ting", "ui", "menu", "delicate", "clean"] },
    AudioAlias { key: "interface-sounds/glitch", name: "Glitch", kind: AssetKind::Sound,
        categories: &["sound/ui"],
        aliases: &["glitch", "error", "digital", "broken", "static", "corrupt", "sci-fi", "bad"] },
    AudioAlias { key: "interface-sounds/scratch", name: "Scratch", kind: AssetKind::Sound,
        categories: &["sound/ui"],
        aliases: &["scratch", "scrape", "rough", "record", "ui", "rub"] },
    // ------------------------------------------------------- pickups etc
    AudioAlias { key: "digital-audio/powerUp", name: "Power Up", kind: AssetKind::Sound,
        categories: &["sound/pickup"],
        aliases: &["powerup", "power up", "collect", "pickup", "coin", "bonus", "good", "reward", "retro", "8-bit", "arcade", "level up", "get"] },
    AudioAlias { key: "digital-audio/pepSound", name: "Pep Sound", kind: AssetKind::Sound,
        categories: &["sound/pickup"],
        aliases: &["pep", "blip", "collect", "pickup", "coin", "point", "retro", "8-bit", "arcade", "positive"] },
    AudioAlias { key: "digital-audio/highUp", name: "High Up", kind: AssetKind::Sound,
        categories: &["sound/pickup"],
        aliases: &["up", "rising", "high", "collect", "pickup", "jump", "positive", "good", "retro", "8-bit"] },
    AudioAlias { key: "digital-audio/highDown", name: "High Down", kind: AssetKind::Sound,
        categories: &["sound/ui"],
        aliases: &["down", "falling", "high", "lose", "negative", "bad", "retro", "8-bit"] },
    AudioAlias { key: "digital-audio/lowDown", name: "Low Down", kind: AssetKind::Sound,
        categories: &["sound/ui"],
        aliases: &["down", "low", "falling", "lose", "fail", "negative", "bad", "die", "retro", "8-bit", "game over"] },
    AudioAlias { key: "digital-audio/phaseJump", name: "Phase Jump", kind: AssetKind::Sound,
        categories: &["sound/pickup"],
        aliases: &["jump", "warp", "teleport", "phase", "retro", "8-bit", "arcade", "sci-fi", "hop"] },
    AudioAlias { key: "digital-audio/phaserUp", name: "Phaser Up", kind: AssetKind::Sound,
        categories: &["sound/pickup"],
        aliases: &["phaser", "up", "rising", "charge", "powerup", "retro", "8-bit", "sci-fi"] },
    AudioAlias { key: "digital-audio/phaserDown", name: "Phaser Down", kind: AssetKind::Sound,
        categories: &["sound/ui"],
        aliases: &["phaser", "down", "falling", "power down", "retro", "8-bit", "sci-fi", "lose"] },
    AudioAlias { key: "digital-audio/tone", name: "Tone", kind: AssetKind::Sound,
        categories: &["sound/ui"],
        aliases: &["tone", "beep", "note", "blip", "simple", "retro", "8-bit"] },
    AudioAlias { key: "digital-audio/twoTone", name: "Two Tone", kind: AssetKind::Sound,
        categories: &["sound/ui"],
        aliases: &["two tone", "beep", "notify", "alert", "retro", "8-bit", "double"] },
    AudioAlias { key: "digital-audio/threeTone", name: "Three Tone", kind: AssetKind::Sound,
        categories: &["sound/ui"],
        aliases: &["three tone", "beep", "notify", "alert", "retro", "8-bit", "triple", "jingle"] },
    AudioAlias { key: "digital-audio/lowThreeTone", name: "Low Three Tone", kind: AssetKind::Sound,
        categories: &["sound/ui"],
        aliases: &["three tone", "low", "deep", "beep", "alert", "retro", "8-bit", "warning"] },
    AudioAlias { key: "digital-audio/lowRandom", name: "Low Random", kind: AssetKind::Sound,
        categories: &["sound/ui"],
        aliases: &["low", "random", "noise", "beep", "retro", "8-bit", "glitch"] },
    AudioAlias { key: "digital-audio/spaceTrash", name: "Space Trash", kind: AssetKind::Sound,
        categories: &["sound/ui"],
        aliases: &["noise", "static", "trash", "junk", "sci-fi", "space", "retro", "8-bit", "glitch"] },
    // --------------------------------------------------------- sci-fi misc
    AudioAlias { key: "sci-fi-sounds/computerNoise", name: "Computer Noise", kind: AssetKind::Sound,
        categories: &["sound/ambient"],
        aliases: &["computer", "beep", "data", "terminal", "sci-fi", "tech", "processing", "machine"] },
    AudioAlias { key: "sci-fi-sounds/forceField", name: "Force Field", kind: AssetKind::Sound,
        categories: &["sound/ambient"],
        aliases: &["force field", "shield", "barrier", "energy", "hum", "sci-fi", "loop", "protect"] },
    AudioAlias { key: "sci-fi-sounds/slime", name: "Slime", kind: AssetKind::Sound,
        categories: &["sound/ambient"],
        aliases: &["slime", "squelch", "goo", "wet", "gross", "monster", "splat", "organic"] },
    AudioAlias { key: "sci-fi-sounds/doorOpen", name: "Sci-Fi Door Open", kind: AssetKind::Sound,
        categories: &["sound/ambient"],
        aliases: &["door", "open", "sci-fi", "space", "hiss", "automatic", "airlock"] },
    AudioAlias { key: "sci-fi-sounds/doorClose", name: "Sci-Fi Door Close", kind: AssetKind::Sound,
        categories: &["sound/ambient"],
        aliases: &["door", "close", "shut", "sci-fi", "space", "hiss", "automatic", "airlock"] },
    // -------------------------------------------------------------- rpg
    AudioAlias { key: "rpg-audio/doorOpen", name: "Door Open", kind: AssetKind::Sound,
        categories: &["sound/ambient"],
        aliases: &["door", "open", "creak", "wooden", "medieval", "rpg", "enter"] },
    AudioAlias { key: "rpg-audio/doorClose", name: "Door Close", kind: AssetKind::Sound,
        categories: &["sound/ambient"],
        aliases: &["door", "close", "shut", "slam", "wooden", "medieval", "rpg"] },
    AudioAlias { key: "rpg-audio/creak", name: "Creak", kind: AssetKind::Sound,
        categories: &["sound/ambient"],
        aliases: &["creak", "squeak", "wood", "old", "spooky", "scary", "door", "medieval"] },
    AudioAlias { key: "rpg-audio/handleCoins", name: "Coins", kind: AssetKind::Sound,
        categories: &["sound/pickup"],
        aliases: &["coins", "money", "gold", "jingle", "collect", "pickup", "treasure", "rich", "shop", "buy", "reward"] },
    AudioAlias { key: "rpg-audio/bookOpen", name: "Book Open", kind: AssetKind::Sound,
        categories: &["sound/ui"],
        aliases: &["book", "open", "page", "read", "menu", "journal", "medieval", "rpg"] },
    AudioAlias { key: "rpg-audio/bookClose", name: "Book Close", kind: AssetKind::Sound,
        categories: &["sound/ui"],
        aliases: &["book", "close", "shut", "read", "menu", "journal", "medieval", "rpg"] },
    AudioAlias { key: "rpg-audio/bookFlip", name: "Page Flip", kind: AssetKind::Sound,
        categories: &["sound/ui"],
        aliases: &["page", "flip", "turn", "book", "paper", "read", "menu", "next"] },
    AudioAlias { key: "rpg-audio/bookPlace", name: "Book Place", kind: AssetKind::Sound,
        categories: &["sound/ui"],
        aliases: &["book", "place", "put", "down", "thud", "menu", "medieval"] },
    AudioAlias { key: "rpg-audio/cloth", name: "Cloth", kind: AssetKind::Sound,
        categories: &["sound/ambient"],
        aliases: &["cloth", "fabric", "rustle", "clothes", "equip", "swish", "medieval"] },
    AudioAlias { key: "rpg-audio/clothBelt", name: "Cloth Belt", kind: AssetKind::Sound,
        categories: &["sound/ambient"],
        aliases: &["belt", "cloth", "buckle", "equip", "armour", "armor", "medieval"] },
    AudioAlias { key: "rpg-audio/beltHandle", name: "Belt Handle", kind: AssetKind::Sound,
        categories: &["sound/ambient"],
        aliases: &["belt", "leather", "handle", "equip", "inventory", "medieval"] },
    AudioAlias { key: "rpg-audio/dropLeather", name: "Drop Leather", kind: AssetKind::Sound,
        categories: &["sound/ui"],
        aliases: &["leather", "drop", "place", "inventory", "item", "medieval", "bag"] },
    AudioAlias { key: "rpg-audio/handleSmallLeather", name: "Leather Handle", kind: AssetKind::Sound,
        categories: &["sound/ui"],
        aliases: &["leather", "handle", "bag", "pouch", "inventory", "item", "medieval"] },
    AudioAlias { key: "rpg-audio/metalClick", name: "Metal Click", kind: AssetKind::Sound,
        categories: &["sound/ui"],
        aliases: &["metal", "click", "latch", "lock", "mechanism", "equip", "medieval"] },
    AudioAlias { key: "rpg-audio/metalLatch", name: "Metal Latch", kind: AssetKind::Sound,
        categories: &["sound/ui"],
        aliases: &["metal", "latch", "lock", "chest", "click", "mechanism", "open", "medieval"] },
    AudioAlias { key: "rpg-audio/metalPot", name: "Metal Pot", kind: AssetKind::Sound,
        categories: &["sound/impact"],
        aliases: &["pot", "metal", "pan", "clang", "kitchen", "cooking", "medieval", "hit"] },
    // ------------------------------------------------------------- music
    AudioAlias { key: "music-jingles/jingles_HIT", name: "Jingle (hit)", kind: AssetKind::Music,
        categories: &["music/jingle"],
        aliases: &["jingle", "music", "sting", "hit", "short", "fanfare", "tune", "melody"] },
    AudioAlias { key: "music-jingles/jingles_NES", name: "Jingle (NES)", kind: AssetKind::Music,
        categories: &["music/jingle"],
        aliases: &["jingle", "music", "nes", "retro", "8-bit", "chiptune", "arcade", "sting", "happy", "victory", "win", "tune"] },
    AudioAlias { key: "music-jingles/jingles_PIZZI", name: "Jingle (pizzicato)", kind: AssetKind::Music,
        categories: &["music/jingle"],
        aliases: &["jingle", "music", "pizzicato", "strings", "playful", "cute", "light", "happy", "sting", "tune"] },
    AudioAlias { key: "music-jingles/jingles_SAX", name: "Jingle (sax)", kind: AssetKind::Music,
        categories: &["music/jingle"],
        aliases: &["jingle", "music", "sax", "saxophone", "jazzy", "smooth", "sting", "happy", "tune"] },
    AudioAlias { key: "music-jingles/jingles_STEEL", name: "Jingle (steel drum)", kind: AssetKind::Music,
        categories: &["music/jingle"],
        aliases: &["jingle", "music", "steel drum", "tropical", "happy", "cheerful", "sting", "tune", "island"] },
];

/// Extra query expansions that only make sense for audio.
pub const AUDIO_SYNONYMS: &[(&str, &[&str])] = &[
    ("sfx", &["sound"]),
    ("noise", &["sound"]),
    ("audio", &["sound"]),
    ("smash", &["impact", "crash", "break"]),
    ("crash", &["impact", "smash"]),
    ("bump", &["impact", "hit"]),
    ("thud", &["impact", "soft"]),
    ("clang", &["metal", "impact"]),
    ("bang", &["impact", "explosion"]),
    ("boom", &["explosion"]),
    ("pew", &["laser"]),
    ("shoot", &["laser", "weapon"]),
    ("gunshot", &["laser", "weapon"]),
    ("fanfare", &["jingle", "victory"]),
    ("victory", &["win", "jingle"]),
    ("win", &["victory", "jingle", "powerup"]),
    ("winning", &["victory", "win", "jingle"]),
    ("lose", &["fail", "error", "down"]),
    ("losing", &["lose", "fail"]),
    ("gameover", &["lose", "fail", "down"]),
    ("background", &["music", "loop", "ambient"]),
    ("soundtrack", &["music", "jingle"]),
    ("song", &["music", "jingle"]),
    ("tune", &["music", "jingle"]),
    ("chiptune", &["8-bit", "retro", "nes"]),
    ("footsteps", &["footstep"]),
    ("splash", &["water", "slime"]),
    ("whoosh", &["swish", "cloth"]),
    ("skid", &["engine", "tyre"]),
    ("beep", &["tone", "ui"]),
];

pub fn lookup(key: &str) -> Option<&'static AudioAlias> {
    AUDIO_ALIASES.iter().find(|a| a.key == key)
}

/// Strip Kenney's variant suffix so `footstep_wood_003` maps to the curated
/// `footstep_wood` family.
pub fn family_of(stem: &str) -> String {
    let trimmed = stem.trim_end_matches(|c: char| c.is_ascii_digit());
    trimmed.trim_end_matches(['_', '-', ' ']).to_string()
}
