//! Offline source-native asset bake. No renderer, store, model inference or
//! runtime CSG dependency: a checked Splash program becomes a bundled mesh.
//! `bake <source.splash> <output.rs|output.glb>`; Rust output is NamedPart data.
use makepad_csg::{evaluate_program, mesh_document, CsgBudgets};
use std::{fmt::Write, path::Path};

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let args: Vec<_> = std::env::args().skip(1).collect();
    if args.len() != 2 { return Err("usage: bake <source.splash> <output.rs|output.glb>".into()); }
    let source = std::fs::read_to_string(&args[0])?;
    let model = mesh_document(evaluate_program(&source, CsgBudgets::default())?, |_| {})?;
    if model.rig.is_some() || model.parts.iter().any(|p| p.animation.is_some() || p.parent.is_some()) {
        return Err("static bake refuses rigs/animation; use ModelProgram GLB for animated assets".into());
    }
    let mut hash = 0xcbf29ce484222325u64;
    for b in source.bytes() { hash = (hash ^ u64::from(b)).wrapping_mul(0x100000001b3); }
    let positions: Vec<Vec<[f32;3]>> = model.parts.iter().map(|p| p.mesh.vertices.iter()
        .map(|v| [v.x as f32,v.y as f32,v.z as f32]).collect()).collect();
    let indices: Vec<Vec<u32>> = model.parts.iter().map(|p| p.mesh.triangles.iter().flatten().copied().collect()).collect();
    let mut min = [f32::INFINITY;3];
    let mut max = [f32::NEG_INFINITY;3];
    for points in &positions { for p in points { for axis in 0..3 {
        if !p[axis].is_finite() { return Err("nonfinite baked coordinate".into()); }
        min[axis] = min[axis].min(p[axis]); max[axis] = max[axis].max(p[axis]);
    } } }
    for (points, triangles) in positions.iter().zip(&indices) {
        for t in triangles.chunks_exact(3) {
            let [a,b,c] = [points[t[0] as usize],points[t[1] as usize],points[t[2] as usize]];
            let u = [b[0]-a[0],b[1]-a[1],b[2]-a[2]];
            let v = [c[0]-a[0],c[1]-a[1],c[2]-a[2]];
            let cross = [u[1]*v[2]-u[2]*v[1],u[2]*v[0]-u[0]*v[2],u[0]*v[1]-u[1]*v[0]];
            let area_squared = cross.iter().map(|x| x*x).sum::<f32>();
            if !area_squared.is_finite() || area_squared <= 1.0e-18 {
                return Err("float32 bake collapsed a triangle".into());
            }
        }
    }
    let output = Path::new(&args[1]);
    match output.extension().and_then(|e| e.to_str()) {
        Some("rs") => {
            let mut out = format!("// Generated by makepad-csg example bake. EDIT THE .splash SOURCE, not this file.\n// Source FNV-1a: {hash:016x}; {} closed manifold parts, {} triangles.\n", model.parts.len(),model.triangles);
            writeln!(out,"pub const SOURCE_HASH: u64 = 0x{hash:016x};\npub const BOUNDS: ([f32;3],[f32;3]) = ({min:?},{max:?});")?;
            out.push_str("pub fn parts() -> Vec<crate::surface::NamedPart> {\n    vec![\n");
            for (i,part) in model.parts.iter().enumerate() {
                writeln!(out,"        crate::surface::NamedPart {{ name: {:?}, color: {:?}, mesh: crate::ribbon::PartMesh {{ positions: P{i}.to_vec(), indices: I{i}.to_vec() }} }},",part.name,part.color)?;
            }
            out.push_str("    ]\n}\n");
            for (i,(points,triangles)) in positions.iter().zip(&indices).enumerate() {
                writeln!(out,"const P{i}: &[[f32;3]] = &[")?;
                for p in points { writeln!(out,"    {p:?},")?; }
                writeln!(out,"];\nconst I{i}: &[u32] = &[")?;
                for t in triangles.chunks(18) { writeln!(out,"    {},",t.iter().map(u32::to_string).collect::<Vec<_>>().join(","))?; }
                out.push_str("];\n");
            }
            std::fs::write(output,out)?;
        }
        Some("glb") => {
            let parts: Vec<_> = model.parts.iter().enumerate().map(|(i,p)| makepad_gltf::GlbNamedPart {
                name: &p.name, positions: &positions[i], indices: &indices[i], pivot: p.pivot,
                color: p.color, parent: None, animation: None,
            }).collect();
            let bytes = makepad_gltf::write_glb_named_parts(&parts);
            makepad_gltf::load_gltf_from_bytes(&bytes,None)?;
            std::fs::write(output,bytes)?;
        }
        _ => return Err("output must end in .rs or .glb".into()),
    }
    eprintln!("baked {} parts, {} triangles, {} vertices; bounds {min:?}..{max:?}; source {hash:016x}",model.parts.len(),model.triangles,positions.iter().map(Vec::len).sum::<usize>());
    Ok(())
}
