/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package dev.makepad.android;

public final class R {
    public static final class attr {
    }
    public static final class id {
        public static final int menu_copy=0x7f030000;
        public static final int menu_cut=0x7f030001;
        public static final int menu_paste=0x7f030002;
    }
    public static final class menu {
        public static final int context_menu=0x7f020000;
    }
}
