use {
    crate::makepad_platform::*
};

live_design! {
    use link::theme::*;
    pub STUDIO_PALETTE_1 = #B2FF64
    pub STUDIO_PALETTE_2 = #80FFBF
    pub STUDIO_PALETTE_3 = #80BFFF
    pub STUDIO_PALETTE_4 = #BF80FF
    pub STUDIO_PALETTE_5 = #FF80BF
    pub STUDIO_PALETTE_6 = #FFB368
    pub STUDIO_PALETTE_7 = #FFD864
    
    pub STUDIO_COLOR_FILE = (THEME_COLOR_TEXT)
    pub STUDIO_COLOR_FOLDER = (THEME_COLOR_TEXT)
    pub STUDIO_COLOR_LAYOUT = (STUDIO_PALETTE_6)
    pub STUDIO_COLOR_WIDGET = (STUDIO_PALETTE_2)
    pub STUDIO_COLOR_ASSET = (STUDIO_PALETTE_5)
    pub STUDIO_COLOR_TEXT = (STUDIO_PALETTE_1)
}