[package]
name = "makepad-example-xr-net"
version = "0.9.0"
authors = ["Makepad <info@makepad.nl>"]
edition = "2021"
description = "Makepad xr-net quest example"
license = "MIT OR Apache-2.0"
metadata.makepad-auto-version = "db3R5Gxh5Njhx8E-8kuZ2plQ1AI="

[dependencies]
makepad-widgets = { path = "../../widgets", version = "1.0.0" }
makepad-xr-net = { path = "../../libs/xr_net", version = "1.0.0" }
makepad-miniz  = { path = "../../libs/miniz", version = "1.0.0" }
