[package]
name = "makepad-example-simple"
version = "0.6.0"
authors = ["Makepad <info@makepad.nl>"]
edition = "2021"
description = "Makepad simple example"
license = "MIT OR Apache-2.0"
metadata.makepad-auto-version = "db3R5Gxh5Njhx8E-8kuZ2plQ1AI="

[dependencies]
makepad-widgets = { path = "../../widgets", version = "0.6.0" }

[target.'cfg(target_env = "ohos")'.dependencies]
napi-derive-ohos = "0.0.9"  ## now at 1.0.4
napi-ohos = "0.1.3"         ## now at 1.0.4
