//! Makepad Mixer — LR-Mix control surface over OSC/UDP.
//!
//! Screens: DISCOVERY (scan a user-entered target for consoles, list the
//! replies, connect) and the SURFACE (a splash-layout channel-strip board
//! driven entirely by the console's own state). See src/surface.rs for the
//! layout slot contract and makepad_mixer::safety for the wire rules.
//!
//! It runs itself: at launch one `/xinfo` query goes to the local
//! broadcast, repeated about once a second until a console answers, and the
//! first one that does is connected and drawn. Lose it and the search
//! starts again. There is no target field, no connect button and no
//! disconnect — the surface is either up or looking for its desk.
//!
//! The surface is LIVE: what you move on it moves on the console. The wire
//! is still the closed whitelist in `safety.rs` — faders, mutes, pan,
//! preamp gain, EQ — and phantom power, scenes and presets are not
//! expressible on it at all.
//!
//!   makepad-mixer                the app
//!   --layout=compact             start on a different surface layout
//!   MIXER_RX_LOG=1               log every answer the console sends
//!
//! The app icon lives in resources/ and is generated by the script beside
//! it; a plain `cargo build` embeds the workspace icon instead, so build it
//! with the icon like this (from the repo root):
//!
//!   R=$PWD/apps/mixer/resources; MAKEPAD_APP_ICON_32=$R/icon_32.png \
//!   MAKEPAD_APP_ICON_64=$R/icon_64.png MAKEPAD_APP_ICON_128=$R/icon_128.png \
//!   MAKEPAD_APP_ICON_256=$R/icon_256.png MAKEPAD_APP_ICON_512=$R/icon_512.png \
//!   MAKEPAD_APP_ICON_1024=$R/icon_1024.png MAKEPAD_APP_ICON_ICO=$R/icon.ico \
//!   cargo build --release -p makepad-mixer

pub use makepad_widgets;
use makepad_mixer::client::{guess_directed_broadcast, Client, Cmd, Evt};
use makepad_mixer::model::MixerModel;
use makepad_widgets::*;
use std::net::SocketAddr;
use std::sync::Arc;

mod surface;
use surface::SurfaceBinder;

app_main!(App);

/// Posted by the client thread whenever new events are queued.
#[derive(Debug)]
struct NetPing;

const LAYOUTS: &[(&str, &str)] = &[("LR MIX", "lr_mix"), ("COMPACT", "compact")];

/// Reconcile passes after the initial sweep, and how far apart they sit.
const RESWEEP_ROUNDS: u32 = 8;
const RESWEEP_EVERY: std::time::Duration = std::time::Duration::from_millis(1200);

fn load_layout_body(name: &str) -> String {
    let candidates = [
        format!("apps/mixer/layouts/{name}.splash"),
        format!("{}/layouts/{name}.splash", env!("CARGO_MANIFEST_DIR")),
    ];
    for c in &candidates {
        if let Ok(s) = std::fs::read_to_string(c) {
            return s;
        }
    }
    match name {
        "lr_mix" => include_str!("../layouts/lr_mix.splash").to_string(),
        "compact" => include_str!("../layouts/compact.splash").to_string(),
        _ => String::new(),
    }
}

script_mod! {
    use mod.prelude.widgets.*

    startup() do #(App::script_component(vm)){
        ui: Root{
            main_window := Window{
                window.title: "Mixer"
                window.inner_size: vec2(1268, 716)
                pass.clear_color: #x07090d
                body +: {
                    width: Fill
                    height: Fill
                    flow: Down

                    searching := View{
                        width: Fill
                        height: Fill
                        flow: Down
                        align: Align{x: 0.5, y: 0.5}
                        spacing: 14

                        Label{
                            text: "Searching for your mixer"
                            draw_text.color: #xe8eef6
                            draw_text.text_style: theme.font_bold{font_size: 17.0}
                        }
                        search_note := Label{
                            text: "listening for a console on the local network"
                            draw_text.color: #x8d99aa
                            draw_text.text_style.font_size: 9.0
                        }
                        LoadingSpinner{
                            width: 34
                            height: 34
                        }
                    }

                    surface_panel := View{
                        visible: false
                        width: Fill
                        height: Fill
                        flow: Down
                        surface := Splash{
                            width: Fill
                            height: Fill
                        }
                    }
                }
            }
        }
    }
}

#[derive(Script, ScriptHook)]
pub struct App {
    #[live]
    ui: WidgetRef,
    #[rust]
    client: Option<Client>,
    #[rust]
    model: MixerModel,
    #[rust]
    binder: SurfaceBinder,
    #[rust]
    layout_idx: usize,
    #[rust]
    connected: Option<SocketAddr>,
    /// One-shot re-request pass: after the sweep drains, any parameter the
    /// console never answered is queried again instead of staying blank.
    /// Reconcile rounds run so far: after the sweep drains, anything the
    /// console did not answer is asked for again, round after round, until
    /// nothing is missing (or the cap is reached).
    #[rust]
    resweep_rounds: u32,
    #[rust]
    sweep_drained_at: Option<std::time::Instant>,
}

impl App {
    fn splash_ref(&self, cx: &mut Cx) -> WidgetRef {
        self.ui.widget(cx, ids!(surface))
    }

    fn load_layout(&mut self, cx: &mut Cx) {
        let (_label, file) = LAYOUTS[self.layout_idx];
        let body = load_layout_body(file);
        let splash = self.splash_ref(cx);
        splash.set_text(cx, &body);
        self.binder.rebind(cx, &splash);
        self.binder.sync_all(cx, &self.model);
        self.ui.redraw(cx);
    }

    /// The whole app is two pages: the search page, and the surface.
    fn show_surface(&mut self, cx: &mut Cx, on: bool) {
        self.ui.view(cx, ids!(searching)).set_visible(cx, !on);
        self.ui.view(cx, ids!(surface_panel)).set_visible(cx, on);
        self.ui.redraw(cx);
    }

    /// The one status line, at the top of the surface layout.
    fn note(&mut self, cx: &mut Cx, text: &str) {
        self.binder.set_note(cx, text);
        let _ = self.ui.label(cx, ids!(search_note)).set_text(cx, text);
    }

    fn drain_net(&mut self, cx: &mut Cx) {
        let Some(client) = &self.client else { return };
        let mut sync_needed = false;
        let mut events = Vec::new();
        while let Ok(e) = client.evt_rx.try_recv() {
            events.push(e);
        }
        for e in events {
            match e {
                Evt::Found { info, from } => {
                    // First console that answers wins — no list, no choice.
                    if self.connected.is_none() {
                        let what = info.model.as_deref().unwrap_or("mixer").to_string();
                        println!("[mixer] connecting to {what} at {from}");
                        self.note(cx, &format!("found {what} — reading its state"));
                        if let Some(client) = &self.client {
                            client.cmd(Cmd::Connect { addr: from });
                        }
                    }
                }
                Evt::Connected { addr } => {
                    self.connected = Some(addr);
                    self.model.clear();
                    self.resweep_rounds = 0;
                    self.sweep_drained_at = None;
                    // The surface is a control surface: it moves the desk.
                    if let Some(client) = &self.client {
                        client.cmd(Cmd::SetControl(true));
                    }
                    self.show_surface(cx, true);
                    self.binder.sync_all(cx, &self.model);
                }
                Evt::Disconnected => {
                    self.connected = None;
                    self.show_surface(cx, false);
                    self.note(cx, "lost the console — searching again");
                }
                Evt::Info(info) => {
                    self.model.device = Some(info);
                }
                Evt::Param(p, v) => {
                    if self.model.apply(p, v) {
                        if self.binder.slot_count() > 0 {
                            self.binder.push_param(cx, &self.model, p);
                        }
                        sync_needed = true;
                    }
                }
                Evt::Meters { bank, vals } => {
                    self.binder.push_meters(cx, &self.model, bank, &vals);
                }
                Evt::Health { rx_age, stale, sweep_left } => {
                    // Reconcile: the console drops answers when it is busy,
                    // so keep asking for what is still blank until the
                    // surface is complete. Names, colours and link state
                    // are exactly what goes missing.
                    if sweep_left == 0 && self.resweep_rounds < RESWEEP_ROUNDS {
                        let now = std::time::Instant::now();
                        let due = match self.sweep_drained_at {
                            None => {
                                self.sweep_drained_at = Some(now);
                                false
                            }
                            Some(t) => now.duration_since(t) >= RESWEEP_EVERY,
                        };
                        if due {
                            self.sweep_drained_at = Some(now);
                            let missing = self.binder.missing_params(&self.model);
                            self.resweep_rounds += 1;
                            if missing.is_empty() {
                                println!(
                                    "[mixer] surface complete after {} reconcile round(s)",
                                    self.resweep_rounds - 1
                                );
                                self.resweep_rounds = RESWEEP_ROUNDS;
                            } else {
                                println!(
                                    "[mixer] reconcile {}/{}: re-requesting {} unanswered parameters",
                                    self.resweep_rounds,
                                    RESWEEP_ROUNDS,
                                    missing.len()
                                );
                                if let Some(client) = &self.client {
                                    for p in missing {
                                        client.cmd(Cmd::Get(p));
                                    }
                                }
                            }
                        }
                    }
                    let dev = self
                        .model
                        .device
                        .as_ref()
                        .map(|d| d.summary())
                        .unwrap_or_default();
                    let txt = if stale {
                        format!(
                            "{dev} — nothing heard for {:.0}s",
                            rx_age.as_secs_f32()
                        )
                    } else if sweep_left > 0 {
                        format!("{dev} · reading state ({} left)", sweep_left)
                    } else {
                        String::new()
                    };
                    self.note(cx, &txt);
                }
                Evt::Note(n) => {
                    println!("[mixer] {n}");
                }
            }
        }
        let _ = sync_needed;
    }

}

impl MatchEvent for App {
    fn handle_startup(&mut self, cx: &mut Cx) {
        let args: Vec<String> = std::env::args().collect();
        if let Some(l) = args.iter().find_map(|a| a.strip_prefix("--layout=")) {
            if let Some(i) = LAYOUTS.iter().position(|(_, f)| *f == l) {
                self.layout_idx = i;
            }
        }

        let notify: Arc<dyn Fn() + Send + Sync> = Arc::new(|| Cx::post_action(NetPing));
        match Client::start(notify) {
            Ok(c) => {
                println!("[mixer] client socket bound to {}", c.local_addr);
                self.client = Some(c);
            }
            Err(e) => log!("client failed to start: {e}"),
        }

        self.load_layout(cx);
        self.show_surface(cx, false);

        // Discovery is automatic and stays automatic: one /xinfo query to
        // the local broadcast, repeated about once a second for as long as
        // no console is connected. Nothing else goes out unbidden.
        match guess_directed_broadcast() {
            Some(target) => {
                println!("[mixer] searching for a console on {target}");
                if let Some(client) = &self.client {
                    client.cmd(Cmd::Scan { target });
                }
            }
            None => {
                self.note(cx, "no network interface to search on");
            }
        }
    }

    fn handle_actions(&mut self, cx: &mut Cx, actions: &Actions) {
        for action in actions {
            if action.downcast_ref::<NetPing>().is_some() {
                self.drain_net(cx);
                break;
            }
        }

        // Surface gestures. The app is a control surface — what you move on
        // it moves on the desk. (The wire is still the closed whitelist:
        // faders, mutes, pan, preamp gain, EQ. Phantom power, scenes and
        // presets are not expressible, see safety.rs.)
        let cmds = self.binder.handle_actions(cx, actions, &self.model);
        if !cmds.is_empty() {
            if let Some(client) = &self.client {
                for (p, v) in cmds {
                    client.cmd(Cmd::Set(p, v));
                }
            }
        }
    }
}

impl AppMain for App {
    fn script_mod(vm: &mut ScriptVm) -> ScriptValue {
        crate::makepad_widgets::script_mod(vm);
        self::script_mod(vm)
    }

    fn handle_event(&mut self, cx: &mut Cx, event: &Event) {
        self.match_event(cx, event);
        self.ui.handle_event(cx, event, &mut Scope::empty());
    }
}
