//! GENERATED by tools/rapid/std-next/check/src/gen_fmt.rs (`rapid-std-gen fmt ../core`); do not edit.

use super::super::{Binary, Debug, Display, Formatter, LowerHex, Octal, Result, UpperHex};
use super::{fmt_radix_u128, fmt_radix_u64, fmt_u128, fmt_u64};

impl Display for i8 {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result {
        fmt_u64(self.unsigned_abs() as u64, *self >= 0, f)
    }
}
impl Debug for i8 {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result {
        if f.debug_lower_hex() {
            LowerHex::fmt(self, f)
        } else if f.debug_upper_hex() {
            UpperHex::fmt(self, f)
        } else {
            Display::fmt(self, f)
        }
    }
}
impl LowerHex for i8 {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result {
        fmt_radix_u64(*self as u8 as u64, 4, false, f)
    }
}
impl UpperHex for i8 {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result {
        fmt_radix_u64(*self as u8 as u64, 4, true, f)
    }
}
impl Octal for i8 {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result {
        fmt_radix_u64(*self as u8 as u64, 3, false, f)
    }
}
impl Binary for i8 {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result {
        fmt_radix_u64(*self as u8 as u64, 1, false, f)
    }
}

impl Display for i16 {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result {
        fmt_u64(self.unsigned_abs() as u64, *self >= 0, f)
    }
}
impl Debug for i16 {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result {
        if f.debug_lower_hex() {
            LowerHex::fmt(self, f)
        } else if f.debug_upper_hex() {
            UpperHex::fmt(self, f)
        } else {
            Display::fmt(self, f)
        }
    }
}
impl LowerHex for i16 {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result {
        fmt_radix_u64(*self as u16 as u64, 4, false, f)
    }
}
impl UpperHex for i16 {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result {
        fmt_radix_u64(*self as u16 as u64, 4, true, f)
    }
}
impl Octal for i16 {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result {
        fmt_radix_u64(*self as u16 as u64, 3, false, f)
    }
}
impl Binary for i16 {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result {
        fmt_radix_u64(*self as u16 as u64, 1, false, f)
    }
}

impl Display for i32 {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result {
        fmt_u64(self.unsigned_abs() as u64, *self >= 0, f)
    }
}
impl Debug for i32 {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result {
        if f.debug_lower_hex() {
            LowerHex::fmt(self, f)
        } else if f.debug_upper_hex() {
            UpperHex::fmt(self, f)
        } else {
            Display::fmt(self, f)
        }
    }
}
impl LowerHex for i32 {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result {
        fmt_radix_u64(*self as u32 as u64, 4, false, f)
    }
}
impl UpperHex for i32 {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result {
        fmt_radix_u64(*self as u32 as u64, 4, true, f)
    }
}
impl Octal for i32 {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result {
        fmt_radix_u64(*self as u32 as u64, 3, false, f)
    }
}
impl Binary for i32 {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result {
        fmt_radix_u64(*self as u32 as u64, 1, false, f)
    }
}

impl Display for i64 {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result {
        fmt_u64(self.unsigned_abs() as u64, *self >= 0, f)
    }
}
impl Debug for i64 {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result {
        if f.debug_lower_hex() {
            LowerHex::fmt(self, f)
        } else if f.debug_upper_hex() {
            UpperHex::fmt(self, f)
        } else {
            Display::fmt(self, f)
        }
    }
}
impl LowerHex for i64 {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result {
        fmt_radix_u64(*self as u64 as u64, 4, false, f)
    }
}
impl UpperHex for i64 {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result {
        fmt_radix_u64(*self as u64 as u64, 4, true, f)
    }
}
impl Octal for i64 {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result {
        fmt_radix_u64(*self as u64 as u64, 3, false, f)
    }
}
impl Binary for i64 {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result {
        fmt_radix_u64(*self as u64 as u64, 1, false, f)
    }
}

impl Display for isize {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result {
        fmt_u64(self.unsigned_abs() as u64, *self >= 0, f)
    }
}
impl Debug for isize {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result {
        if f.debug_lower_hex() {
            LowerHex::fmt(self, f)
        } else if f.debug_upper_hex() {
            UpperHex::fmt(self, f)
        } else {
            Display::fmt(self, f)
        }
    }
}
impl LowerHex for isize {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result {
        fmt_radix_u64(*self as usize as u64, 4, false, f)
    }
}
impl UpperHex for isize {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result {
        fmt_radix_u64(*self as usize as u64, 4, true, f)
    }
}
impl Octal for isize {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result {
        fmt_radix_u64(*self as usize as u64, 3, false, f)
    }
}
impl Binary for isize {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result {
        fmt_radix_u64(*self as usize as u64, 1, false, f)
    }
}

impl Display for i128 {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result {
        fmt_u128(self.unsigned_abs() as u128, *self >= 0, f)
    }
}
impl Debug for i128 {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result {
        if f.debug_lower_hex() {
            LowerHex::fmt(self, f)
        } else if f.debug_upper_hex() {
            UpperHex::fmt(self, f)
        } else {
            Display::fmt(self, f)
        }
    }
}
impl LowerHex for i128 {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result {
        fmt_radix_u128(*self as u128 as u128, 4, false, f)
    }
}
impl UpperHex for i128 {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result {
        fmt_radix_u128(*self as u128 as u128, 4, true, f)
    }
}
impl Octal for i128 {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result {
        fmt_radix_u128(*self as u128 as u128, 3, false, f)
    }
}
impl Binary for i128 {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result {
        fmt_radix_u128(*self as u128 as u128, 1, false, f)
    }
}

impl Display for u8 {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result {
        fmt_u64(*self as u64, true, f)
    }
}
impl Debug for u8 {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result {
        if f.debug_lower_hex() {
            LowerHex::fmt(self, f)
        } else if f.debug_upper_hex() {
            UpperHex::fmt(self, f)
        } else {
            Display::fmt(self, f)
        }
    }
}
impl LowerHex for u8 {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result {
        fmt_radix_u64(*self as u64, 4, false, f)
    }
}
impl UpperHex for u8 {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result {
        fmt_radix_u64(*self as u64, 4, true, f)
    }
}
impl Octal for u8 {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result {
        fmt_radix_u64(*self as u64, 3, false, f)
    }
}
impl Binary for u8 {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result {
        fmt_radix_u64(*self as u64, 1, false, f)
    }
}

impl Display for u16 {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result {
        fmt_u64(*self as u64, true, f)
    }
}
impl Debug for u16 {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result {
        if f.debug_lower_hex() {
            LowerHex::fmt(self, f)
        } else if f.debug_upper_hex() {
            UpperHex::fmt(self, f)
        } else {
            Display::fmt(self, f)
        }
    }
}
impl LowerHex for u16 {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result {
        fmt_radix_u64(*self as u64, 4, false, f)
    }
}
impl UpperHex for u16 {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result {
        fmt_radix_u64(*self as u64, 4, true, f)
    }
}
impl Octal for u16 {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result {
        fmt_radix_u64(*self as u64, 3, false, f)
    }
}
impl Binary for u16 {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result {
        fmt_radix_u64(*self as u64, 1, false, f)
    }
}

impl Display for u32 {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result {
        fmt_u64(*self as u64, true, f)
    }
}
impl Debug for u32 {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result {
        if f.debug_lower_hex() {
            LowerHex::fmt(self, f)
        } else if f.debug_upper_hex() {
            UpperHex::fmt(self, f)
        } else {
            Display::fmt(self, f)
        }
    }
}
impl LowerHex for u32 {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result {
        fmt_radix_u64(*self as u64, 4, false, f)
    }
}
impl UpperHex for u32 {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result {
        fmt_radix_u64(*self as u64, 4, true, f)
    }
}
impl Octal for u32 {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result {
        fmt_radix_u64(*self as u64, 3, false, f)
    }
}
impl Binary for u32 {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result {
        fmt_radix_u64(*self as u64, 1, false, f)
    }
}

impl Display for u64 {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result {
        fmt_u64(*self as u64, true, f)
    }
}
impl Debug for u64 {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result {
        if f.debug_lower_hex() {
            LowerHex::fmt(self, f)
        } else if f.debug_upper_hex() {
            UpperHex::fmt(self, f)
        } else {
            Display::fmt(self, f)
        }
    }
}
impl LowerHex for u64 {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result {
        fmt_radix_u64(*self as u64, 4, false, f)
    }
}
impl UpperHex for u64 {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result {
        fmt_radix_u64(*self as u64, 4, true, f)
    }
}
impl Octal for u64 {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result {
        fmt_radix_u64(*self as u64, 3, false, f)
    }
}
impl Binary for u64 {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result {
        fmt_radix_u64(*self as u64, 1, false, f)
    }
}

impl Display for usize {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result {
        fmt_u64(*self as u64, true, f)
    }
}
impl Debug for usize {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result {
        if f.debug_lower_hex() {
            LowerHex::fmt(self, f)
        } else if f.debug_upper_hex() {
            UpperHex::fmt(self, f)
        } else {
            Display::fmt(self, f)
        }
    }
}
impl LowerHex for usize {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result {
        fmt_radix_u64(*self as u64, 4, false, f)
    }
}
impl UpperHex for usize {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result {
        fmt_radix_u64(*self as u64, 4, true, f)
    }
}
impl Octal for usize {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result {
        fmt_radix_u64(*self as u64, 3, false, f)
    }
}
impl Binary for usize {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result {
        fmt_radix_u64(*self as u64, 1, false, f)
    }
}

impl Display for u128 {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result {
        fmt_u128(*self as u128, true, f)
    }
}
impl Debug for u128 {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result {
        if f.debug_lower_hex() {
            LowerHex::fmt(self, f)
        } else if f.debug_upper_hex() {
            UpperHex::fmt(self, f)
        } else {
            Display::fmt(self, f)
        }
    }
}
impl LowerHex for u128 {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result {
        fmt_radix_u128(*self as u128, 4, false, f)
    }
}
impl UpperHex for u128 {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result {
        fmt_radix_u128(*self as u128, 4, true, f)
    }
}
impl Octal for u128 {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result {
        fmt_radix_u128(*self as u128, 3, false, f)
    }
}
impl Binary for u128 {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result {
        fmt_radix_u128(*self as u128, 1, false, f)
    }
}
