/// Detail-layer keys consumed by the renderer's way/polygon paths.
pub const DETAIL_WAY_KEYS: &[&str] = &[
    "layer",
    "bridge",
    "tunnel",
    "highway",
    "railway",
    "width",
    "barrier",
    "area",
    "name",
    "attraction",
    "zoo",
    "tourism",
    "public_transport",
    "landuse",
    "leisure",
    "natural",
    "building",
    "building:part",
    "height",
    "building:levels",
    "min_height",
    "building:min_level",
    "location",
    "place",
    "parking",
    "surface",
    "access",
    "service",
    "link",
    "rail",
    "waterway",
    "ref",
];

/// Additional keys consumed by point icon/routing code.
pub const DETAIL_POINT_EXTRA_KEYS: &[&str] = &[
    "amenity",
    "brand",
    "craft",
    "entrance",
    "historic",
    "max_kw",
    "office",
    "operator",
    "shop",
    "osm_layer",
    "kerb",
    "bus",
    "shelter",
];
